rnmapbox/maps

- README.md
- docs/GettingStarted.md
Adding a Getting Started guide to have an easier ramp up for newbies to whom the example folder might be too daunting.
This commit includes very basic section for:
* setting up the accessToken
* disabling telemetry
* showing a simple map
Feedback welcome :)
> docs: add getting started guide

- scripts/autogenHelpers/globals.js
- scripts/autogenerate.js
- scripts/templates/RCTMGLStyleFactory.java.ejs
`autogenerate.js` still referenced old versions and the old package name.
> Update code generation

- example/src/examples/FitBounds.js
Updated FitBounds in the example app to the new Camera api. 
One issue on ios is that the initial visible bounds is set when the view is small (64x64) and as we resize we'll see much larger area. So `resize` after `set-bounds` is not same as `set-bounds` after `resize` which is not nice. Android seems to work.
I guess we could store where the last update to the camera came from and if it was from `Camera` properties, we need to reapply after view resize. (We need to at least implement https://github.com/nitaliano/react-native-mapbox-gl/pull/1255 , which only fixes the issue for iniital layout)
`resize` after `setbounds`:
`set bound` after `resize`:
> Updated FitBounds for the new Camera api

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/RCTMGLCamera.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/RCTMGLCameraManager.java
- ios/RCTMGL/RCTMGLCamera.h
- ios/RCTMGL/RCTMGLCamera.m
- ios/RCTMGL/RCTMGLCameraManager.m
- ios/RCTMGL/RCTMGLMapView.h
- ios/RCTMGL/RCTMGLMapView.m
- javascript/components/Camera.js
and suport Camera#minZoomLevel and Camera#maxZoomLevel on ios
ios part of nitaliano/react-native-mapbox-gl#1255 was lost during the merge, this fixes that, also adds minZoomLevel/maxZoomLevel to camera (both android and ios)
See #30
> Reapply camera on initial layout 

- CHANGELOG.md
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/RCTMGLCamera.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/events/MapUserTrackingModeEvent.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/location/UserTrackingMode.java
- example/src/examples/SetUserTrackingModes.js
- ios/RCTMGL/RCTMGLCamera.h
- ios/RCTMGL/RCTMGLCamera.m
- ios/RCTMGL/RCTMGLCameraManager.m
- ios/RCTMGL/RCTMGLEventTypes.m
- ios/RCTMGL/RCTMGLMapView.h
- ios/RCTMGL/RCTMGLMapView.m
- ios/RCTMGL/RCTMGLMapViewManager.m
- ios/RCTMGL/RCTMGLUserLocation.h
- ios/RCTMGL/RCTMGLUserLocation.m
- javascript/components/Camera.js
- javascript/components/UserLocation.js
- javascript/index.js
Also fixed erros on ios, android:
- Use an invisible user location annotation for builtin location annotation , so we can use our own annotation for location [ios/android]
- `UserLocation` starts/stops locationManager as needed. [javascript]
- implement `onUserTrackingModeChange`  (see https://github.com/nitaliano/react-native-mapbox-gl/pull/897 for original impl) [ios and android]
> Ported SetUserTrackingModes to the new UserLocation/Camera api

- ios/RCTMGL/RCTMGLStyle.m
A proposed fix for https://github.com/react-native-mapbox/maps/issues/37.
When trying to build the latest version of @react-native-mapbox/maps in Xcode I get a "Semantic Issue" in RCTMGLStyle.m line 1470 'rasterResampling' is unavailable: Use rasterResamplingMode instead.
> Fix: rename rasterResampling to rasterResamplingMode

- ios/install.md
Following the current iOS pods install guide caused me to get stuck during build on the error 'folly/Portability.h' file not found. A solution and more info on this error can found at [https://github.com/facebook/react-native/issues/24192](https://github.com/facebook/react-native/issues/24192). This PR adds solution to iOS pods install guide.
> Update: Add Folly and cleanup to fix folly/Portability.h file not found

- android/rctmgl/build.gradle
Building on Android currently gives an error about Turf functions being undefined.
This is because mapbox's turf plugin was missing from dependencies. This branch fixes that.
> Added missing turf plugin

- ios/RCTMGL.xcodeproj/project.pbxproj
If you currently follow the manual installation guide xcode will fail to build the project. Steps to reproduce the issue is to create a new react-native init project, add react-native-mapbox/maps and try the manual installation.
This removes FilterList reference and adds UserLocation reference to RCTMGL.xcodeproj/project.pbxproj solving the issues.
> Bugfix - Remove FilterList and add UserLocation in xcode project

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyle.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleFactory.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleValue.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/utils/ConvertUtils.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/utils/DownloadMapImageTask.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/utils/ImageEntry.java
- ios/RCTMGL/RCTMGLImageQueue.h
- ios/RCTMGL/RCTMGLImageQueue.m
- ios/RCTMGL/RCTMGLImageQueueOperation.h
- ios/RCTMGL/RCTMGLImageQueueOperation.m
- ios/RCTMGL/RCTMGLLayer.m
- ios/RCTMGL/RCTMGLStyle.m
- ios/RCTMGL/RCTMGLStyleValue.h
- ios/RCTMGL/RCTMGLStyleValue.m
- ios/RCTMGL/RCTMGLUtils.h
- ios/RCTMGL/RCTMGLUtils.m
- javascript/components/AbstractLayer.js
Fixes: #68 
Use imageScale from react native vs trying to figure out.
Before #1206 mapbox worked for static images without `@2x` and `@3x` suffixes.
#1206 fixed that for the case the image had same resolution as the device (so `@3x` on 3x device).
This PR should work for normal and scaled images (`@2x`...)
https://github.com/nitaliano/react-native-mapbox-gl/pull/1206
> iOS: fix asset image scale

- CHANGELOG.md
- README.md
- android/rctmgl/build.gradle
- package.json
- scripts/autogenerate.js
Bump ios mapbox-gl-native sdk to 5.0 and android mapbox-gl-native to 8.0. 
See https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v5.0.0 and https://github.com/mapbox/mapbox-gl-native/releases/tag/android-v8.0.0
> Update ios sdk to 5.0.0 and android to 8.0.0

- javascript/components/MapView.js
I've recently seen a few warnings regarding MapView trying to update its state while being unmounted. I found three places where this warning could originate from;
https://github.com/react-native-mapbox-gl/maps/blob/9e3310ae56ad6872437d3a82ee1e5f9fd2bedc90/javascript/components/MapView.js#L669 https://github.com/react-native-mapbox-gl/maps/blob/9e3310ae56ad6872437d3a82ee1e5f9fd2bedc90/javascript/components/MapView.js#L676 https://github.com/react-native-mapbox-gl/maps/blob/9e3310ae56ad6872437d3a82ee1e5f9fd2bedc90/javascript/components/MapView.js#L748-L752
I have previously used a variable in my own projects which I can query when setting state. This will allow me to cancel or inhibit `setState` when the component is unmounted. What do you think about this solution?
> Inhibits state updates when MapView is unmounted

- __tests__/interface.test.js
- android/rctmgl/src/main/java/com/mapbox/rctmgl/RCTMGLPackage.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleFactory.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/layers/RCTMGLHeatmapLayer.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/layers/RCTMGLHeatmapLayerManager.java
- docs/HeatmapLayer.md
- ios/RCTMGL/RCTMGLHeatmapLayer.h
- ios/RCTMGL/RCTMGLHeatmapLayer.m
- ios/RCTMGL/RCTMGLHeatmapLayerManager.h
- ios/RCTMGL/RCTMGLHeatmapLayerManager.m
- javascript/components/HeatmapLayer.js
- javascript/index.js
Related to issue: @react-native-mapbox-gl/maps#115
Adds support for HeatmapLayer in Style Layers for Android and iOS.
- On Android, Heatmap Layer appears to be working, at least for the examples provided for the native Mapbox SDK
- RCTMGLHeatmapLayer.java created based on RCTMGLCircleLayer
- RCTMGLHeatmapLayerManager.java based on RCTMGLCircleLayerManager
- Styles were already present under RCTMGLStyle.java
- Added to RCTMGLHeatmapLayerManager to RCTMGLPackage so that it works in React Native
- On iOS, the project does not run, possibly missing changes higher up in the library.
- RCTMLGHeatmapLayer.m and .h created based on RCTMGLCircleLayer.m and h
- RCTMGLHeatmapLayerManager.m and .h created based on RCTMGLCircleLayerManager.m and h
TODO:
Test style properties and expressions for …
> [WIP] Enable HeatmapLayer Support

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/RCTMGLCamera.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/RCTMGLCameraManager.java
- docs/Camera.md
- docs/PointAnnotation.md
- docs/ShapeSource.md
- docs/VectorSource.md
- docs/docs.json
- example/src/examples/SetUserTrackingModes.js
- ios/RCTMGL/RCTMGLCamera.h
- ios/RCTMGL/RCTMGLCamera.m
- ios/RCTMGL/RCTMGLCameraManager.m
- javascript/components/Camera.js
- package.json
- scripts/autogenHelpers/DocJSONBuilder.js
- scripts/autogenHelpers/globals.js
`Camera` has `centerCoordinate` bounds `bounds`, `zoomLevel` for moving `Camera` around in a `MapView`. Ideally those would affect the current state of camera. 
In a lot of cases we'd just want to define where the map camera should be initially and later we'd follow user's location, or just let the user change camera, by pinch-zoom etc.
Right now we can set initial camera position by setting `centerCoordinate` and `zoomLevel` for example and specify `animationDuration={0}`. This however does not work if we set `followUserLocation`.
This proposal would add a new `defaultSettings` like this:
```js
<MapView>
<Camera
defaultSettings={{
centerCoordinate: [-111.8678, 40.2866],
zoomLevel: 16,
}}
followUserLocation
followUserMode="normal"
/>
</MapView>
```
If we use an analogy of `Camera` is like …
> Implement Camera defaultSettings

- ios/RCTMGL/RCTMGLShapeSource.m
Fixed error when invoking setImage with nil placeholder image introduced with #143
> Fixed error when adding ShapeSource with images

- README.md
- __tests__/interface.test.js
- docs/ShapeSource.md
- docs/docs.json
- example/src/examples/ShapeSourceIcon.js
- javascript/components/Images.js
- javascript/components/ShapeSource.js
- javascript/index.js
See https://github.com/react-native-mapbox-gl/maps/pull/143#issuecomment-503685328
This just introduces a js Images component with images prop, and deprecates ShapeSource#images. (Images is backed by ShapeSource for now, but the intent is to have a separate native component)
> Introduce Images, and deprecate ShapeSource#images

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/CameraStop.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/CameraUpdateItem.java
- ios/RCTMGL/CameraStop.h
- ios/RCTMGL/CameraStop.m
- ios/RCTMGL/CameraUpdateItem.m
This PR adds support for using `bounds` when updating camera with `Flight` or `Ease` animation mode.
Fixes:
- iOS: Always used `Move` when `bounds` was provided, regardless of `animationMode`
- Android: Always  used `Flight` when bounds was provided, regardless of `animationMode`
- Android: Wasn't able to handle negative animationDuration. On iOS this adds [specific behavior](https://docs.mapbox.com/ios/api/maps/5.1.0/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)flyToCamera:withDuration:completionHandler:) to flight mode camera updates.
- Android: In the process of testing the two animation modes with `bounds` I also found that Android behaved incorrectly when combing the update with `pitch` and `bearing`. In order for Android to correctly use `bounds` + `pitch` / `bearing` I updated …
> Added support for bounds with flight/ease camera animations

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLRasterSource.java
`tileSize` is an optional property for react-native-mapbox-gl, but android apps will crash if it is not set.
How it happens: 
1. `mTileSize` (java.lang.Integer) is null
2. in `makeSource()` it gets implicitly casted to a native int when constructing the new RasterSource
3. this implicit cast calls java.lang.Integer.intValue on a null pointer
> Fixed crash on android if RasterSource.tileSize is null

- ios/RCTMGL/RCTMGLLayer.h
- ios/RCTMGL/RCTMGLLayer.m
- ios/RCTMGL/RCTMGLSymbolLayer.m
Currently on iOS, If the root style has a layer, and you are modifying the style of the layer by adding a child of the MapView with the same layer id, the layer's filter gets cleared. This happens because there is a missing `_filter == nil` check in RCTMGLSymbolLayer.m. The other layer types have this check in place.
Also in the PR I fixed a few invalid argument types (filters can now be any expression) and added a few more null checks.
> Fix for SymbolLayer Filter Being Removed When Runtime Styling (iOS)

- ios/RCTMGL/MGLModule.m
The argument type for setTelemetryEnabled on iOS should be a `BOOL` instead of a `BOOL *`. It worked as it was because ultimately both bools and pointers are just integers which can either be 0 or non-zero, but this is more clear at least.
> Fixed setTelemetryEnabled argument type (should be literal not pointer)

- android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLOfflineModule.java
- ios/RCTMGL/MGLOfflineModule.m
When deleting offline packs you can run into some hard crashes if you try to delete an offline pack that has already been deleted or that is still downloading. Obscure crashes can also happen when sending progress events for offline packs that are in an invalid state.
This PR puts more checks in place so that these cases are handled more gracefully. We have been using these checks in production and have seen an increase in stability.
> Improved stability of offline manager

- javascript/components/Camera.js
`paddingLeft` would never be checked when camera bounds change
> Fix typo in camera bounds check

- __tests__/__mocks__/react-native-mapbox-gl.mock.js
To test my app that uses `@react-native-mapbox-gl/maps` I have to mock it. So I found that this package already has some mock setup, and I use it like this:
```
setupFilesAfterEnv: [
'<rootDir>/jest.setup.ts',
'<rootDir>/node_modules/react-native-gesture-handler/jestSetup.js',
'<rootDir>/node_modules/@react-native-mapbox-gl/maps/__tests__/__mocks__/react-native-mapbox-gl.mock.js',
],
```
Currently this file is a bit outdated and jest will complain about missing native module. This PR made it work for me.
> Add  MGLLocationModule mock

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/AbstractEvent.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/AbstractEventEmitter.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/RCTMGLCamera.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/events/AbstractEvent.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/events/AndroidCallbackEvent.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/events/IEvent.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/events/LocationEvent.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/events/MapChangeEvent.java
- javascript/components/Camera.js
- javascript/components/MapView.js
- javascript/components/NativeBridgeComponent.js
I noticed that callbacks on Android don't always work. Here's some example code:
```js
const time = Date.now();
let hasResult = false;
const zoom1 = this._map.getZoom();
const zoom2 = this._map.getZoom();
const zoom3 = this._map.getZoom();
console.log(`Request Zoom: ${time}`);
Promise.all([zoom1, zoom2, zoom3]).then(values => {
hasResult = true;
console.log(`Received Zoom: ${time}`);
this.setState({zoom: values[0]});
});
setTimeout(() => {
if (!hasResult) {
console.log(`Request Zoom: ${time} timed-out`);
}
}, 1000);
```
In which I added the following in `_runNativeCommand` inside `MapView.js` for debugging purposes.
```
console.log(``${methodName}: ${callbackID}`)
```
This is the output:
```js
getZoom: 1561558978423
getZoom: 1561558978424
getZoom: 1561558978424
Request Zoom: 1561558978423 …
```
> Fix Android sometimes missing callbacks

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/RCTMGLCamera.java
Fixes: #193
It seems that setMin/MaxZoom cancels pending camera transitions, so we should do this before applying camera
> Android setMin/MaxZoom before applying camera

- package.json
Travis tests have been failing for some days with the error:
```
Cannot find module '@babel/runtime/helpers/objectSpread2' from 'index.js'
```
Locally jest tests were running fine but after running `node_modules/.bin/jest --clearCache` I could reproduce the failing tests locally as well. I'm not sure yet why this error suddenly started showing up but after some searching I found several hints to update `@babel/runtime`. I tried it and that fixed the failing tests locally.
Let's see if it now runs on Travis too.
> Jest: Fixed 'Cannot find module'

- ios/RCTMGL/CameraUpdateItem.m
Our app suffered from a weird camera issue that only happened on physical iOS devices. It seemed to zoom to somewhat random surrounding areas on physical devices while running normally within the simulator under the same parameters.
I narrowed it down to this call where the `camera: fittingCoordinateBounds` that is used to calculate the target `centerCoordinate` / `altitude` from incoming `bounds`. The idea is that this call uses the current camera configuration (taking into account target `pitch` / `heading`). However it was given the `_cameraStop` that contained possible invalid properties. Such as a `pitch` + `heading` with a `nil` value and a coordinate value of `0,0` in case the client only updates with `bounds`. This call should have used `nextCamera` in the first place since that …
> Fixed bug where camera moves to incorrect position on physical iOS devices

- example/README.md
I don't know why it was written to create a file called `accesstoken` in the root of the example project because that's not how it works ! I changed the readme following what I did and it worked.
> fixing incorrect accessToken file instruction

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/RCTMGLCamera.java
I noticed that map padding is reset when enabling `followUserLocation` on `Camera`.
The way we build a new `LocationComponentOptions` in order to enable tracking camera mode constructs an options object with a default padding of `0` which is then [applied by Mapbox](https://github.com/mapbox/mapbox-gl-native/blob/41980af4692006054a0fb851b2aacf9ddbfd9668/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponent.java#L1295-L1302) resetting any padding currently present on the map.
_Note: I'm in the midst of refactoring the use of `locationComponent` a bit for #215 but for now this simple patch should fix that single issue._
> Fixed padding being reset when enabling followUserLocation

- docs/PointAnnotation.md
- docs/docs.json
- javascript/components/PointAnnotation.js
related to [#54](https://github.com/react-native-mapbox-gl/maps/issues/54): I spent to much time trying to fix a bug on a PointAnnotation... if it was clearer, it would have been much better !
> Make it clear PointAnnotation is deprecated

- android/rctmgl/src/main/java/com/mapbox/rctmgl/utils/BitmapUtils.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/utils/DownloadMapImageTask.java
Currently images are loaded using a custom implementation to create bitmap from urls or resources. This changes it to leverage the Fresco image pipeline instead which is used by react-native images. This will allow sharing the image cache with other RN images and supporting more formats (webp for example).
Based loosely on https://github.com/react-native-community/react-native-maps/blob/master/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapMarker.java and https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/image/ImageLoaderModule.java#L72
Tested that images local and remote images work in both debug and release modes.
> Use Fresco image pipeline to load images on Android

- ios/RCTMGL/RCTMGLShapeSource.h
- ios/RCTMGL/RCTMGLShapeSource.m
Fixes a spelling error that caused the ShapeSource `tolerance` prop to crash on iOS.
Re: https://github.com/nitaliano/react-native-mapbox-gl/issues/1394
> Fix ShapeSource tolerance prop on iOS

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/annotation/RCTMGLCalloutManager.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/annotation/RCTMGLPointAnnotationManager.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/RCTMGLCameraManager.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLAndroidTextureMapViewManager.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/layers/RCTMGLBackgroundLayerManager.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/layers/RCTMGLCircleLayerManager.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/layers/RCTMGLFillExtrusionLayerManager.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/layers/RCTMGLFillLayerManager.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/layers/RCTMGLHeatmapLayerManager.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/layers/RCTMGLLineLayerManager.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/layers/RCTMGLRasterLayerManager.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/layers/RCTMGLSymbolLayerManager.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/light/RCTMGLLightManager.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLImageSourceManager.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLRasterSourceManager.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLShapeSourceManager.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLVectorSourceManager.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLLocationModule.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLModule.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLOfflineModule.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLSnapshotModule.java
- example/android/app/build.gradle
When using proguard class names will get minified so it is not safe to use them for the module name. This simply replaces it by static strings. Also add `@ReactModule` annotation to native modules.
Tested in the example app.
> Don't use class.getSimpleName for module names to fix proguard compat

- javascript/components/Camera.js
- javascript/components/MapView.js
In reference to https://github.com/react-native-mapbox-gl/maps/issues/289
This suppresses the warning from showing up when people use the component. However we should look to refactor to `componentDidUpdate` as suggested here: https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops
My head is not right into how this component is working in terms of NativeComponent etc. and I have not worked out how to run tests or anything like that so I don't want to provide a `componentDidUpdate` version at this point. Someone who has been working on this should be able to refactor the components pretty quickly to use the `componentDidUpdate` methods to sync the nativeComponents. This PR can help by however preventing people attempting to use this component and getting bad DX which …
> Prevent componentWillReceiveProps warning from showing.

- CHANGELOG.md
- android/rctmgl/build.gradle
- package.json
- scripts/autogenerate.js
Version 8.1.0 / 5.1.0 has a bug when using content insets. Bump native lib versions to bring in the fix https://github.com/mapbox/mapbox-gl-native/pull/15130.
> Bump native deps to fix collisions with content insets

- example/README.md
Example project setup explanation is not correct. A postinstall hook automatically creates the env.json file. Instead, a file named `access` file needs to be provided.
> Update example readme

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLVectorSource.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLVectorSourceManager.java
- example/src/examples/CustomVectorSource.js
- ios/RCTMGL/RCTMGLVectorSource.h
- ios/RCTMGL/RCTMGLVectorSource.m
- ios/RCTMGL/RCTMGLVectorSourceManager.h
- ios/RCTMGL/RCTMGLVectorSourceManager.m
- javascript/components/MapView.js
- javascript/components/NativeBridgeComponent.js
- javascript/components/VectorSource.js
Implement `VectorSource#features` via [VectorSource#querySourceFeatures](https://docs.mapbox.com/android/api/map-sdk/7.2.0/com/mapbox/mapboxsdk/style/sources/VectorSource.html#querySourceFeatures-java.lang.String:A-com.mapbox.mapboxsdk.style.expressions.Expression-)  and [MGLVectorTitleSource#featuresInSourceLayersWithIdentifiers:predicate:](https://docs.mapbox.com/ios/api/maps/5.2.0/Classes/MGLVectorTileSource.html#/c:objc(cs)MGLVectorTileSource(im)featuresInSourceLayersWithIdentifiers:predicate:)
> implement VectorSource#features

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
The issue documented in the previous mapbox project ([issue #953)](https://github.com/nitaliano/react-native-mapbox-gl/issues/953) is still occurring on Android. Seems like childview casts should all be checked in a similar way and this does not appear to cause any side effects.
see https://github.com/nitaliano/react-native-mapbox-gl/issues/953
> childview check for instanceof ViewGroup in RCTMGLMapView

- javascript/utils/AnimatedPoint.js
These methods seem to reference `coordinates` when the values inside use points, so this would be crashing.
Also generally better to do animated value `.setValue` instead of `._value=` since I think the later is supposed to be immutable.
> Fix AnimatedPoint setValue and setOffset methods

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
These changes have been part of the repo once or twice before, but guess they got lost when transferring ownership? We are experiencing a few crashes because of this.
More information here:
https://github.com/nitaliano/react-native-mapbox-gl/pull/1580
> Regression: Trying to remove a view index above child count 0

- javascript/components/UserLocation.js
I'm using `UserLocation` component like this:
```tsx
<Mapbox.UserLocation visible={locationPermissionGranted} />
```
Currently, when `UserLocation` mounts, it calls `getLastKnownLocation` even when visible is set to false. And `getLastKnownLocation` crashes on Android when permissions are denied.
This PR makes `UserLocation` request initial location only when it's really needed.
As a side-effect I remove a call to `locationManager.stop();` which was never called. The `stop` method doesn't even exist anymore.
> fix calls to getLastKnownLocation in UserLocation

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
This PR fixes issue with inability to set `scrollEnabled` to `true` after setting it to `false` on Android.
Relates to  https://github.com/react-native-mapbox-gl/maps/issues/211. (all the details and steps are there)
> Fix setting scroll on android

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/layers/RCTLayer.java
If layers are added to the map before the style is loaded a null pointer exception is thrown. This PR adds checks so that apps won't crash.
As far as I can tell, checking if the style is null and simply aborting is safe because the layers will be re-added when the style loads here: 
https://github.com/react-native-mapbox-gl/maps/blob/master/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTSource.java#L134
> Prevent crash if layers added to the map before style loads

- ios/RCTMGL/RCTMGLImageQueueOperation.m
The image loader module should now be loaded using this https://github.com/facebook/react-native/blob/80f64f1e5bddad6e4df88efa4c28e09db7462d04/Libraries/Image/RCTImageViewManager.m#L92.
The method was added 10 months ago so it should be fine for backwards compat.
Tested that the project builds and examples with images still work.
> Use `[RCTBridge moduleForName]` instead of deprecated `[RCTBridge imageLoader]`

- javascript/components/Camera.js
Despite `this.camera.fitBounds(northEastCoordinates, southWestCoordinates[, padding][, animationDuration])` accepts `animationDuration` parameter, the animation does not work on Android. The reason for this is that this method sets `animationMode` to `Camera.Mode.Move` which is mapped later to `CameraModes.None` which in turn causes absence of animation.
I propose to use `Camera.Mode.Ease` for cases when `animationDuration` is not equal to `0.0` as in this case it is properly mapped and causes animation to appear. Other solution is to always use `Camera.Mode.Ease` animation in this method instead of `Camera.Mode.Move`, which will simplify the fix even more.
> Fix camera fitBounds animation android

- README.md
- docs/CustomHttpHeaders.md
- ios/RCTMGL.xcodeproj/project.pbxproj
- ios/RCTMGL/MGLCustomHeaders.h
- ios/RCTMGL/MGLCustomHeaders.m
- ios/RCTMGL/MGLModule.m
Second part of my custom headers pull req. Adding iOS implementation.
Uses method swizzling as the [MGLNetworkConfiguration sessionConfiguration] is used once early on and does not allow adding of headers at runtime.
> Implementation of custom headers for iOS

- ios/RCTMGL/RCTMGLLayer.m
Fix incorrect casting of object NSNumber to primitive NSUInteger. This incorrect casting resulted in a crash on iOS when using layerIndex. 
This PR should fix the issue: https://github.com/react-native-mapbox-gl/maps/issues/66
Closes: #66
> Fix casting of NSNumber to NSUInteger in RCTMGLLayer

- ios/RCTMGL/RCTMGLMapViewManager.m
> FIX-348: Don't trigger a regionDidChange event on cancelled animations

- .eslintrc.js
- android/rctmgl/build.gradle
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
- example/src/App.js
- example/src/examples/DriveTheLine.js
- example/src/examples/SetUserTrackingModes.js
- example/src/examples/ShowPointAnnotation.js
- example/src/examples/ShowRegionDidChange.js
- example/src/examples/common/Bubble.js
- example/src/scenes/Demo.js
- example/src/scenes/Home.js
- javascript/components/Camera.js
- javascript/components/MapView.js
- javascript/components/NativeBridgeComponent.js
- javascript/components/UserLocation.js
- javascript/components/annotations/Annotation.js
- javascript/index.js
- javascript/utils/AnimatedPoint.js
- javascript/utils/geoUtils.js
>  Android camera event fixes + misc cleanup

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
This PR fixes issue when `scrollEnabled` is set to `false` but the dragging of map was already started. It interrupts the move gesture.
Relates to #377
> Interrupt move gesture when scrollEnabled is set to false

- android/rctmgl/src/main/java/com/mapbox/rctmgl/location/LocationManager.java
If the user denies the location permission, an Exception is raised and the current behavior is a complete crash at map display.
Here is the exception in adb:
```
09-10 20:12:38.529 15010 15066 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
09-10 20:12:38.529 15010 15066 E AndroidRuntime: Process: com.sparks, PID: 15010
09-10 20:12:38.529 15010 15066 E AndroidRuntime: java.lang.SecurityException: "passive" location provider requires ACCESS_FINE_LOCATION permission.
09-10 20:12:38.529 15010 15066 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:1950)
09-10 20:12:38.529 15010 15066 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1918)
09-10 20:12:38.529 15010 15066 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1868)
09-10 …
```
> 🤖 Fix crash when no location permission on Android

- ios/install.md
It did not compile and did have an error Framework not found till I added the framework to the search path
> Fix install instruction for iOS and auto linking

- CONTRIBUTING.md
- package.json
- scripts/autogenHelpers/DocJSONBuilder.js
This small change makes it unnecessary to globally install the `documentation` module. [When contributing a PR](https://github.com/react-native-mapbox-gl/maps/pull/384#issuecomment-532775880) I had failed to read the CONTRIBUTING.md which would have told me that it is necessary to globally install, so I was getting a confusing crash when running `npm run generate`. This will make future PRs smoother.
The other upside is that now we'll manage the version of `documentation` ourselves.
> documentation module no longer needs to be globally installed

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.java
- docs/MapView.md
- index.d.ts
- ios/RCTMGL/RCTMGLMapView.h
- ios/RCTMGL/RCTMGLMapView.m
- ios/RCTMGL/RCTMGLMapViewManager.m
- javascript/components/MapView.js
This PR features:
- Added numeral enum for compass position. 
https://docs.mapbox.com/ios/api/maps/5.0.0/Enums/MGLOrnamentPosition.html
(iOS only) Have not found gravity values for corners to work with [setCompassGravity](https://docs.mapbox.com/android/api/map-sdk/5.1.2/com/mapbox/mapboxsdk/maps/UiSettings.html#setCompassGravity-int-)
- Added use of compass margins (multiplied android values by 2 for better device scaling)
- Added info to docs.
> Add compass positioning and margins

- example/scripts/watch_rngl.js
- index.d.ts
Typescript related changes for #402
Also updated `copy:changes` script to copy `index.d.ts` from example directory.
> Typescript definitions for updated VectorSource / RasterSource

- index.d.ts
I've done an overhaul of the typings, tightening up the definitions and removing errors. I'd recommend applying #439 before this one if possible, as that also edits index.d.ts.
> Improve TypeScript typings

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
- example/src/examples/ChangeLayerColor.js
- example/src/examples/ShowAndHideLayer.js
- example/src/scenes/Home.js
- ios/RCTMGL/RCTMGLLayer.m
- ios/RCTMGL/RCTMGLMapView.h
- ios/RCTMGL/RCTMGLMapView.m
- ios/RCTMGL/RCTMGLMapViewManager.m
Provides functionality similar to:
- https://docs.mapbox.com/android/maps/examples/change-a-layers-color/
- https://docs.mapbox.com/android/maps/examples/show-and-hide-layer/
Allows overriding / customization of existing map layers by referencing them by `id`:
```jsx
<MapboxGL.FillLayer id="building" style={{visibility: "none"}} />
<MapboxGL.FillLayer id="water" style={{fillColor: "#556f8a}} />
```
> Allow existing layers to be updated

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
Looks like a copy-paste error, the variable that needs to be checked is `mCompassViewMargins` and not `mCompassEnabled`.
> Fix crash when with compass margins on Android

- javascript/components/Camera.js
By design Camera#defaultSettings should ignore followUserLocation.
So even if followUserLocation is set it should set initial camera position/zoom level etc. which will be corrected once the user location is available.
> defaultSettings should ignore followUserLocation

- index.d.ts
These function typings are rather useless at the moment, so set the correct types on them. 
I have tested these types in my own project, so they should work for others as well
> Improve TypeScript typings in `MapView`

- ios/RCTMGL/RCTMGLLayer.m
We need to allow empty setting empty filters too. So that a filter can be cleared.
Consider this:
```
<SymbolLayer filter={this.state.filter} ...>
```
Where `filter` changes from `nil` to `non-nil` then to `nil` again. The removed `if` statement prevents resetting the filter to nil.
Bug was introduced at:
https://github.com/react-native-mapbox-gl/maps/commit/3b03f649256f368d80741be05644ede0387f2a76#diff-79220b28bb9c8c50280ea315ef9a4f9cR81
> [IOS] Allow filters to be cleared

- CHANGELOG.md
- package.json
- scripts/autogenerate.js
Some important updates, fixes, and improvements starting at version 5.3 including major announcement for increasing tile limits for offline modes.
https://github.com/mapbox/mapbox-gl-native/blob/ios-v5.4.0/platform/ios/CHANGELOG.md
> Upgrade iOS SDK to 5.3.2 to include important new updates from Mapbox

- .travis.yml
- CONTRIBUTING.md
- javascript/utils/BridgeValue.js
- package.json
- scripts/autogenHelpers/DocJSONBuilder.js
- scripts/autogenerate.js
This change automatically generates the generated files in the precommit hook, simplifying contributors' workflows. 
I created this PR because I have noticed many commits where the
documentation hadn't been generated, then a later commit does generate
it which results in messy commits with unrelated changes. This should
ensure that any changes to generated files are committed with the actual
changes that caused them.
Also, when submitting a PR myself recently I forgot to generate documentation, @kristfal kindly reminded me to do so, and it slowed down the PR. I think this should make everyone's lives easier contributing to this project since we'll never have to remember this step.
The question is, do we want it to automatically include the generated file changes into your commit (by …
> Automatically generate files precommit

- ios/RCTMGL/RCTMGLMapView.m
Fix #497 This change fixes a memory leak by correctly removing the UIView.
RCTMGLMapView overrides `removeReactSubview` from the UIView+React.m class:
https://github.com/facebook/react-native/blob/aee88b6843cea63d6aa0b5879ad6ef9da4701846/React/Views/UIView%2BReact.m#L93
That method calls `[subview removeFromSuperview];` and the method in RCTMGLMapView did not.
Example app with memory usage:
```javascript
class App extends React.Component {
state = {
isLayerVisible: true,
};
constructor(props) {
super(props);
setInterval(() => {
this.setState({isLayerVisible: !this.state.isLayerVisible});
}, 1000);
}
render() {
return (
<View style={{flex: 1}}>
<MapboxGL.MapView style={{flex: 1}}>
{this.state.isLayerVisible && (
<MapboxGL.ShapeSource …
```
> Fix #497 Fix memory leak when removing subviews

- docs/Camera.md
- docs/docs.json
- javascript/components/Camera.js
In the [Camera props docs](https://github.com/react-native-mapbox-gl/maps/blob/master/docs/Camera.md#props) `followUserLocation` and `followUserMode` where missing descriptions. This PR adds descriptions for each.
> Adds descriptions for Camera followUserLocation followUserMode

- __tests__/__mocks__/react-native-mapbox-gl.mock.js
- __tests__/interface.test.js
- android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLModule.java
- docs/GettingStarted.md
- index.d.ts
We run a server on localhost to serve styles and tiles for offline maps. Recently, rctmgl has stopped showing any map when offline, and it appears due to the Android Mapbox SDK reading the system connection status and not trying to load the map when offline (I'm not sure why it sometimes works and sometimes doesn't).
According to [mapbox/mapbox-gl-native#12819](https://github.com/mapbox/mapbox-gl-native/issues/12819) the workaround for this it the `Mapbox.setConnected(true)` method. This PR exposes this method to React Native.
This is an Android-only method - there is ([currently](https://github.com/mapbox/mapbox-gl-native/pull/15650)) no equivalent iOS method.
I am not sure how to best document or write an Android-only method for this library - there don't seem to be any existing …
> Add setConnected() method [Android only]

- CHANGELOG.md
- package.json
- scripts/autogenerate.js
This PR updates the iOS SDK from 5.3.2 to 5.5.0.
In the SDK prior to v 5.4.0 a pinch on the map rotates the map to easily. This was fixed when [this pr](https://github.com/mapbox/mapbox-gl-native/pull/15562) got merged. The PR added a threshold of 3 degrees before the map starts to rotate.
> Update iOS SDK to 5.5.0

- ios/RCTMGL/RCTMGLMapViewManager.m
Issue #431 is occurring because of a mismatch in the JS->iOS bridge. The JS API accepts an array of strings for the query filter, but the iOS API was expecting an array of dictionaries.
This caused the bridging code to throw an error whenever a non-null filter array was passed in.
I'm not an iOS developer by trade, nor am I super familiar with this library, so there might be more work to do. That said, this change fixes #431 for me.
Closes: #431
> Make query filter parameters consistent with JS API

- index.d.ts
Types for `MapboxGL.snapshotManager.takeSnap` seemed incorrect and this fixes for my use. Not sure if it's a 100% correct.
> snapshotManager types fix

- __tests__/components/UserLocation.test.js
- javascript/components/UserLocation.js
- package.json
Noticed we didn't have tests for the js components.
This PR adds `react-native-testing-library` to the dev dependencies.
Which is a nice way to test RN uis I think.
Had to resort to to some weird `setTimeout` magic, as the UserLocation is rendering asynchronously 🤷‍♂ 
Edit: Added more, will leave it at that.
Additionally added some todos for `UserLocation`
Looking forward to a review.
> test: UserLocation tests with react-native-testing-library

- android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLOfflineModule.java
- docs/OfflineManager.md
- docs/docs.json
- ios/RCTMGL/MGLOfflineModule.m
- javascript/modules/offline/offlineManager.js
I added a function for calling the native resetDatabase function to clear the ambient cache and reinitialize the offline manager.
> Expose native resetDatabase function

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
There is a slight potential that multiple invocation to the same method are not fulfilled on Android. Only the last invocation will receive a callback. It's not easy to reproduce but I've experienced it a couple of times and found this to be the cause.
Only affected by calling methods before the map initialized. If the code manages to invoke the same method more than once before the map is initialized only the last invocation receives the callback meaning that some promises won't fulfil. 
The `args` were stored in `mPreRenderMethods` (Map) by `methodID`. In android `args` contains a unique `callbackID`for each invocation of that method. Multiple invocation to the same method can cancel out the previous `callbackID` stored in this `Map`
> Fixed methods/callbacks not all being executed when map is not yet ready

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/LayerSourceInfo.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.java
- docs/MapView.md
- docs/docs.json
- example/src/examples/SourceLayerVisibility.js
- example/src/scenes/Home.js
- index.d.ts
- ios/RCTMGL/RCTMGLMapView.h
- ios/RCTMGL/RCTMGLMapView.m
- ios/RCTMGL/RCTMGLMapViewManager.m
- javascript/components/MapView.js
This PR adds the possibility to toggle the visibility of layers by `source` / `source-layer`.  If the [source](https://docs.mapbox.com/mapbox-gl-js/style-spec/#layer-source) or [source-layer](https://docs.mapbox.com/mapbox-gl-js/style-spec/#layer-source-layer) is known this function can be used to toggle all attached layers.
This could be useful when one or more style layers need to be shown or hidden without knowing each individual style layer identifier.
> Added ability to set layer visibility by sourceId / sourceLayerId

- android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLOfflineModule.java
- docs/OfflineManager.md
- docs/docs.json
- ios/RCTMGL/MGLOfflineModule.m
- javascript/modules/offline/OfflinePack.js
- javascript/modules/offline/offlineManager.js
This adds `mergeOfflineRegions` method to the offline manager. Tested and working on iOS and Android.
I decided to use the name `mergeOfflineRegions` (which is what it's called in the Android SDK) because it made more sense to me than naming it `addContentsOfFile` or `addContentsOfURL` (as it's called in the iOS SDK).
I originally started making an example to demonstrate it in the example app, but since the side-loaded database must be generated using the same version of the Mapbox SDK that the client is using, such an example would break whenever we update either of our iOS or Android SDK versions.
This resolves #574.
> Add mergeOfflineRegions method to enable side-loading tiles

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
Android: Add private `getDisplayDensity()` function for getting display density and use density to multiple the point in view's x/y coords.
Has been tested two different Android devices with different densities and it now works the same way as iOS does.
Closes #576
> Fix `getCoordinateFromView()` calculation on Android

- android/rctmgl/build.gradle
- scripts/autogenerate.js
Increased the android sdk version to `8.6.1` as we have increased crash reports and that release seems to have fixed a native crash from `8.6.0`.
Would love to get your opinion on this guys.
Might be related to:
#626 
#625
#622 
#613
> build: Increase android sdk version to 8.6.1

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
The `getCoordinateFromView` method got fixed recently in this PR https://github.com/react-native-mapbox-gl/maps/pull/619, but the `getPointInView()` had the same problem (only in the opposite direction).
This PR should fix this, but I've only tested on my phone. The fact it did work on my phone and that it is so simple (just do the inverse operation to the one added to `getCoordinateFromView`) gives me confidence it is correct, but feel free to test it further.
> Fix `getPointInView()` calculation on Android

- javascript/components/UserLocation.js
Previously this was only checked on update
and even there it was only set when changed on runtime.
This is basically fixing my bug 😞
> fix(user-location): Add minDisplacement on mount

- docs/MapView.md
- docs/docs.json
- javascript/components/MapView.js
This simple change fixes the `propType` defined for `MapView`'s `compassViewPosition` prop.
It had been set to `string`, but should be `number`. The [corresponding TypeScript type](https://github.com/react-native-mapbox-gl/maps/blob/master/index.d.ts#L334) is already correct so this is the only change required.
> Change compassViewPosition propType from string to number

- javascript/index.js
This PR adds named export for main library components in order to let us do for example `import {MapView, UserLocation} from '@react-native-mapbox-gl/maps';`
> Adds named export for library functions

- javascript/components/UserLocation.js
UserLocation component wouldn't stop `locationManager` on unmounts.
On unmounts, we call `await this.setLocationManager({running: false});`
https://github.com/react-native-mapbox-gl/maps/blob/c8fbd5bf344a7a11545f0cabc6fce9f63a73cf58/javascript/components/UserLocation.js#L130-L147
I went for an `else if` to be very specific about when it's supposed to stop.
This resolves #663 
Looking forward to a review
Thanks in advance
> fix(user-location): stop locationManager on unmount

- __tests__/components/Camera.test.js
- javascript/components/Camera.js
This adds tests for the `Camera` component.
Notice, there aren't any tests for `#_getAlignment` as it's not used anywhere.
Follow-up tickets could be:
* remove obsolete methods
* add early exits in methods when arguments are malformed/ missing
* see if we can consolidate methods/ functions (`createStopConfig` is also defined in `MapView`)
> test(camera): Add tests for camera component

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/annotation/RCTMGLMarkerView.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
- example/src/examples/MarkerView.js
When marker view got added before MapView reflow, the marker view got resized to full size of mapview. Now MarkerView's are added only after reflow finished.
https://github.com/react-native-mapbox-gl/maps/blob/b2f418ba5faf254565e5b7ea80de740e0f8c0a91/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java#L461-L470
> Fix MarkerView race with reflow

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/annotation/RCTMGLPointAnnotation.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/annotation/RCTMGLPointAnnotationManager.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
- docs/PointAnnotation.md
- docs/docs.json
- example/src/examples/ShowPointAnnotation.js
- javascript/components/PointAnnotation.js
Fixes: #469 
Images placed inside PointAnnotation was not rendered an android. On android we render PointAnnotations by rendering the RN Views to an bitmaps and using SymbolLayer to display the map.
There is 2 issue with images
1.) React Native Images are based on Fresco on android, and Fresco is detecting that a view is not attached to a window, and in such cases, it'll not load the image.
2.) Images might take a while to load and we've dont renrender the bitmaps. (Only when layout has changed)
Solutions:
1.) we add the views to an invisible parent view inside the map, so fresco detects that they are still attached
2.) there is a new `PointAnnotation#refresh` that you can call from `Image#onLoad` to request a re-render once the image has loaded
```es6
class AnnotationWithRemoteImage …
```
> Implement refresh for PointAnnotation on android and fix Images

- .eslintrc.js
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLImageSource.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLRasterSource.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLShapeSource.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLVectorSource.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTSource.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/events/FeatureClickEvent.java
- docs/ShapeSource.md
- docs/VectorSource.md
- docs/docs.json
- example/src/examples/CustomIcon.js
- example/src/examples/CustomVectorSource.js
- ios/RCTMGL/RCTMGLMapViewManager.m
- javascript/components/ShapeSource.js
- javascript/components/VectorSource.js
- javascript/utils/deprecation.js
Currently in ShapeSource/VectorSource onPress returns a single feature, we also cannot get location of press.
```es6
onPress(e) {
const feature = e.nativeEvent.payload;
...
}
```
With the new version the above works, but deprecated, and you can now access all the features that were at the point of click via: `features`  (the old `payload` only contained the first feature) There is also additional coordinates and point describing the location of the press
```es6
onPress({features, coordinates, point}) {
...
}
```
Fixes: #611
> ShapeShource#onPress e.nativeEvent is now deprecated, use e.features

- example/ios/Podfile
- ios/NoUseFrameworks-MapboxMobileEvents/NoUseFrameworks-MapboxMobileEvents.podspec.json
This is a possible workaround for `use_frameworks!`
If you don't want `use_frameworks!` in your podfile use the `pod 'NoUseFrameworks-MapboxMobileEvents' ...` line bellow:
```ruby
pod 'NoUseFrameworks-MapboxMobileEvents',  :podspec => '../node_modules/@react-native-mapbox-gl/maps/ios/NoUseFrameworks-MapboxMobileEvents/NoUseFrameworks-MapboxMobileEvents.podspec.json'
```
Note: you can test this PR with this in your packages.json
"@react-native-mapbox-gl/maps": "mfazekas/maps-1#allow-no-use-frameworks"
See https://github.com/mapbox/mapbox-gl-native-ios/issues/154
> Allow to be consumed without use_frameworks!

- __tests__/components/UserLocation.test.js
- example/src/examples/SetDisplacement.js
- example/src/examples/SetHeading.js
- example/src/examples/SetPitch.js
- example/src/examples/ShowMap.js
- javascript/components/UserLocation.js
- javascript/modules/location/locationManager.js
Replaced confusing set of three methods with just two
.start - starts locationManager service
.stop - stops locationManager service
.stop internally calls `dispose`, however stop is more sementic in our
usecases
remove .pause
> refactor(location-manager): #start, #pause, #dispose

- index.d.ts
This is just a simple change to offline manager types that I ran into an issue with in our project.
Commits:
* Change offline pack `styleURL` type to `string`, as is the case with `MapViewProps`
This is for consistency, and to avoid type errors.
> Fix types for styleURL

- __tests__/components/Callout.test.js
Another component test PR, I am getting into the flow :-)
* Please let me know, if you think the tests for custom styles became too detailed. 
* I think the [property `title`](https://github.com/react-native-mapbox-gl/maps/blob/master/index.d.ts#L655) should be required, as the component is like a tooltip, which doesn't make much sense without a text. WDYT? If no one objects, I'll add a small issue and take care of it.
> test(callout): add basic tests

- __tests__/interface.test.js
- __tests__/utils/animated/AnimatedCoordinatesArray.test.js
- example/src/examples/AnimatedLine.js
- javascript/index.js
- javascript/utils/animated/AnimatedCoordinatesArray.js
- javascript/utils/animated/AnimatedExtractCoordinateFromArray.js
- javascript/utils/animated/AnimatedRouteCoordinatesArray.js
- package.json
The question is if we want those to be part of the library.
I see those options:
- add those to the library as in this PR
- add those to a separate library like `@react-native-mapbox/maps-animations`
- add those as examples as they are simple
Added 2 new animated classes:
* AnimatedRouteCoordinatesArray - like animated coordinates array but instead of morphing points its animates the array as a route, eating the end of route.
* AnimatedExtractCoordinateFromArray - allows to extract a single point from an array usefull for showing the current point of the screen
```es6
route = new Animated.RouteCoordinatesArray([
....
]);
point = new Animated.ExtractCoordinateFromArray(route, -1);
...
this.route
.timing({
toValue: {end: {point: currentLocation}},
duration: 2000,
easing: Easing.linear,
}) …
```
> RFC: AnimatedRouteCoordinatesArray and AnimatedExtractCoordinateFromArray

- docs/Callout.md
- docs/docs.json
- index.d.ts
- javascript/components/Callout.js
Follow-up PR to #755 
The `Callout` component's purpose is to show a textual hint, which is passed as property titel. Therefore it should be mandatory.
> fix(callout): make title property required

- android/rctmgl/src/main/java/com/mapbox/rctmgl/utils/DownloadMapImageTask.java
- docs/Images.md
- docs/docs.json
- example/src/examples/ShapeSourceIcon.js
- javascript/components/Images.js
Deprecate `Images#images#assets` for `Images#nativeAssetImages`
Before:
```jsx
<Images
images={{
assets: ['pin'],
foo: {uri: 'http:///....png'}
}}
/>
```
After:
```jsx
<Images
nativeAssetImages={['pin']}
images={{
foo: {uri: 'http:///....png'}
}}
/>
```
> Use nativeAssets prop instead of Images#images#assets

- example/ios/Podfile
- react-native-mapbox-gl.podspec
This defaults to non use_frameworks! version so autolink just works.
To use the `use_frameworks!` variant:
```ruby
pod 'react-native-mapbox-gl/DynamicLibrary', :path => '../node_modules/@react-native-mapbox-gl/maps'
use_frameworks!
```
> Default to non use_frameworks! version

- javascript/components/MapView.js
As we've replaced underscore aka `_.debounce` with deounce `cancel` is now `clear`
> Use debounce.clear instead of _.debounce.cancel

- index.d.ts
- ios/RCTMGL/RCTMGLCamera.m
I am working on iOS and found out that camera not working when passing `stops`.
```
this.camera.setCamera({
stops: [
{ pitch: 45, animationDuration: 200 },
{ heading: 180, animationDuration: 300 },
]
})
```
So, this PR just fix the issue on iOS only. I will check Android later when start working on it.
> [iOS] fix camera with stops and add type definition

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/images/RCTMGLImages.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleFactory.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleValue.java
- scripts/templates/RCTMGLStyleFactory.java.ejs
Fixes: #792 
Another issue is that on android, if iconImage is a literal, not an expression, then the icon is not rendered
```jsx
<SymbolLayer style={{iconImage: 'an-icon'}} />
```
will log an error
`icon-image: expected a literal expression issue`
to work around that if iconImage is just a string we'll use `iconImage(str)` instead of `iconImage(Expression.literal(str))`
> Fix icon images and null check

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleValue.java
When no scale specified use the default one `ImageEntry.defaultScale`
> Use ImageEntry.defaultScale for images passed via style

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleFactory.java
- scripts/templates/RCTMGLStyleFactory.java.ejs
The last attmempt was not correct. 
Fixes:
```sh
E/Mbgl: {er.alert_client}[JNI]: Error setting property: icon-image expected a literal expression
```
> Fix android iconImage with literal string

- javascript/components/annotations/Annotation.js
- javascript/index.js
- javascript/utils/animated/Animated.js
Closes: #783
As I reported on https://github.com/react-native-mapbox-gl/maps/issues/783, I actually found that this component was importad on index.js:
https://github.com/react-native-mapbox-gl/maps/blob/424f931f880c84c9989bb3947e4aaddcdd2aec59/javascript/index.js#L11
Meanwhile it is imported back by index.js itself:
https://github.com/react-native-mapbox-gl/maps/blob/424f931f880c84c9989bb3947e4aaddcdd2aec59/javascript/components/annotations/Annotation.js#L5
Roughly, was change the call to the MapboxGL object to import only the Animated component:
https://github.com/react-native-mapbox-gl/maps/blob/424f931f880c84c9989bb3947e4aaddcdd2aec59/javascript/components/annotations/Annotation.js#L103-L118
> Remove require cycles on Annotation and maps/index

- ios/RCTMGL/RCTMGLImageQueueOperation.m
Closes: #383 
RCTMGLImageQueueOperation was leaking, as the OperationQueue did not know that we have finished them.
According to NSOperation [docs](https://developer.apple.com/documentation/foundation/nsoperation/1416837-start?language=objc) if we do async actions we should implement `isFinished` along with KVO notifications so observers know when we've finished.
The leak was visible in xcode debug memory graph 
, with RCTMGLImageQueueOperation count ever increasing.
> Fix image op queue leak

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/annotation/RCTMGLPointAnnotation.java
Fixes crash on point annotation click. 
```java
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getHeight()' on a null object reference
```
To reproduce:
```js
import {Button, View, Text} from 'react-native';
import {
MapView,
Camera,
PointAnnotation,
Callout,
} from '@react-native-mapbox-gl/maps';
class BugReportExample extends React.Component {
state = {
shorter: false,
};
render() {
return (
<>
<Button title="grow" onPress={() => this.setState({shorter: true})} />
{this.state.shorter && <View><Text>Placeholder ot make map smalelr</Text></View>}
<MapView style={{flex: 1}}>
<Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
<PointAnnotation
id="foo"
coordinate={[-74.00567, 40.71327]}
title={'Hello …
```
> Fix crash on point annotaitons callout

- index.d.ts
- `UserLocation.showsUserHeadingIndicator` should be optional and has default = false.
Note: I would leave this PR open. I will try to review the typing and there might be other issues.
> Fix Typing

- index.d.ts
Reverts react-native-mapbox-gl/maps#755
As @mfazekas correctly pointed out, if the `Callout` component is provided with a child, the title property is in fact not required, so it needs to remain optional.
Sorry for the extra work.
> Revert "fix(callout): make title property required"

- android/rctmgl/src/main/java/com/mapbox/rctmgl/events/PointAnnotationClickEvent.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/events/PointAnnotationDragEvent.java
- ios/RCTMGL/RCTMGLMapTouchEvent.h
- ios/RCTMGL/RCTMGLMapTouchEvent.m
If point annotations are created dynamically, id has to be included in events payload in order to identify them.
> Add point annotation id to event payload

- __tests__/components/CircleLayer.test.js
- javascript/components/CircleLayer.js
This is another small component test PR.
**Note:**
The last [commit](https://github.com/react-native-mapbox-gl/maps/commit/3ba775d48f8f5539397f7db14bfba8e23eaac9cb) contains one additional change in the component itself. 
I removed the local props declaration & spread of `sourceLayerID` from `this.props.sourceLayerID`, because – at least as far as I understand the code – `AbstractLayer` the component `CircleLayer` extends, has the method  `get baseProps()` which is already taking care of that. Or am I missing something here?
Counting on your eagle 👀 on this, dear reviewers!
> test(circle-layer): add basic tests

- __tests__/interface.test.js
- android/rctmgl/src/main/java/com/mapbox/rctmgl/RCTMGLPackage.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLLogging.java
- ios/RCTMGL/RCTMGLLogging.h
- ios/RCTMGL/RCTMGLLogging.m
- ios/RCTMGL/RCTMGLMapView.h
- ios/RCTMGL/RCTMGLMapView.m
- javascript/components/MapView.js
- javascript/index.js
- javascript/utils/Logger.js
Add Logging component so we can show errors from Mapbox in react native.
For example in current versions when a font is not found, some of annotations will not be rendered without any clue what's happened.
See #839,  #774
With this change we get a redbox error:
There is also an api for this:
```
import {Logger} from '@react-native-mapbox-gl/maps';
...
Logger.setLogLevel('verbose');
Logger.setLogCallback((log) => {
console.log('Mapbox log:', log);
return true;
});
```
* Set default Mapbox logging verbosity to warning. (Change it using `Logger.setLogLevel('verbose')`)
* Error/Warn mapbox log messages are treated as redbox/yellowbox errors/warnings. (Override it using `Logger.setLoggerCallback(log => { return true })`
> Add Logger

- android/rctmgl/build.gradle
Noticed, that when trying to run `detox` test builds it would fail with:
```shell
> Task :@react-native-mapbox-gl_maps:mergeExtDexDebugAndroidTest FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':@react-native-mapbox-gl_maps:mergeExtDexDebugAndroidTest'.
> Could not resolve all files for configuration ':@react-native-mapbox-gl_maps:debugAndroidTestRuntimeClasspath'.
> Failed to transform retrofit-2.7.1.jar (com.squareup.retrofit2:retrofit:2.7.1) to match attributes {artifactType=android-dex, dexing-enable-desugaring=false, dexing-is-debuggable=true, dexing-min-sdk=23, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
> Execution failed for DexingNoClasspathTransform: …
```
> Adding Java 8 compatibility options

- __tests__/components/MapView.test.js
- javascript/components/MapView.js
I was writing a test that needed to validate that a map was rendered into the UI for a specific screen. However, despite having the `testID` prop available to me on the `MapView` component, I wasn't able to use `getByTestId`. It turns out that the `MapView` component doesn't render the `testID` prop if it isn't being rendered on Android or iOS.
- Add `testID` to the props used when `MapView` is rendered outside of Android and iOS.
> test(mapView): add testId when rendered outside of android and ios

- javascript/components/MapView.js
This commit https://github.com/react-native-mapbox-gl/maps/commit/6a15169a426393abf915f2184dd6d0144dfaac6f introduced `testID` to the MapView component. 
Unfortunately it will crash when `mapView` is actually present, which would result in `false` within the check `!mapView && this.props.testID`, thus returning `false` to `testID`, which does only accept `String`.
Testable via example app `Map` => `Show Map` View.
Feedback/ review welcome
> fix(mapview): replace short-circuit with ternary

- android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLOfflineModule.java
- docs/OfflineManager.md
- docs/docs.json
- ios/RCTMGL/MGLOfflineModule.m
- javascript/modules/offline/offlineManager.js
This adds the `invalidateAmbientCache` method that is available in both the iOS and Android SDKs. Tested and working as expected in my app.
As a side note, I couldn't get `npm run generate` to work. It keeps failing on generating the docs, with the following error:
```
UnhandledPromiseRejectionWarning: Browserslist: caniuse-lite is outdated. Please run next command `npm update`
```
It appears to be failing on the `npx documentation build ${MODULES_PATH} -f json` command. I tried using different versions of `documentation` without any success. So I added the docs change by hand for now.
> add invalidateAmbientCache method

- .gitignore
- __tests__/utils/animated/AnimatedCoordinatesArray.test.js
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLShapeSource.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLShapeSourceManager.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLVectorSource.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/utils/ExpressionParser.java
- docs/ShapeSource.md
- docs/docs.json
- javascript/components/AbstractSource.js
- javascript/components/NativeBridgeComponent.js
- javascript/components/ShapeSource.js
> Implement ShapeSource.features and throw if source is not yet available

- .travis.yml
- react-native-mapbox-gl.podspec
- scripts/autogenerate.js
REACT_NATIVE_MAPBOX_MAPBOX_IOS_VERSION="~> 5.7" pod install
```
REACT_NATIVE_MAPBOX_MAPBOX_IOS_VERSION="~> 5.6.0" pod install --repo-update
```
or add
```
ENV['REACT_NATIVE_MAPBOX_MAPBOX_IOS_VERSION'] = '~> 5.6.0'
```
to your podfile before 
```
use_native_modules!
```
> Allow to customize used framework version

- android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLOfflineModule.java
- docs/OfflineManager.md
- docs/docs.json
- ios/RCTMGL/MGLOfflineModule.m
- javascript/modules/offline/offlineManager.js
This adds the invalidatePack method that is available in both the iOS and Android SDKs. Tested and working as expected in my app.
I didn't add it to the Examples project because, like invalidateAmbientCache, it is difficult to demonstrate it working without the vector tile service changing its tiles.
> add invalidatePack method

- index.d.ts
Based on feedback from #293.
NB: https://github.com/react-native-mapbox-gl/maps/blob/a60ae1509b6c3f7f417476ac066fc64f4d6920fe/android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLModule.java#L339
Will throw a null pointer exception when trying to `setTelemetryEnabled` without setting an accessToken.
```sh
java.lang.NullPointerException: Attempt to invoke interface method 'void com.mapbox.mapboxsdk.maps.TelemetryDefinition.setUserTelemetryRequestState(boolean)' on a null object reference
```
Follow-up ticket could be to remove the necessity to call `setAccessToken` when not using mapbox api at all.
Currently it's coupled with getting an instance:
https://github.com/react-native-mapbox-gl/maps/blob/a60ae1509b6c3f7f417476ac066fc64f4d6920fe/android/rctmgl/src/main/java/com/mapbox/rctmg …
> feat(TS): add 'null' as argument type for setAccessToken

- android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLOfflineModule.java
- docs/OfflineManager.md
- docs/docs.json
- example/src/examples/CacheManagement.js
- example/src/scenes/Home.js
- index.d.ts
- ios/RCTMGL/MGLOfflineModule.m
- javascript/modules/offline/offlineManager.js
#902 
This PR provides two additional methods to control mapbox cache `clearAmbientCache` and `setMaximumAmbientCacheSize`.  Also, this PR includes a new page 'Cache Management' in the example app, where those methods can be easily tested. In addition to them, I have included two others: `invalidateAmbientCache` and `resetDatabase`, which have been implemented earlier #899.
> Add clearAmbientCache and setMaximumAmbientCacheSize methods

- example/src/examples/SetHeading.js
`followUserLocation` prevents heading from being applied
have it enabled initially to get user location and disable afterwards
heading is now correctly applied when pushing option buttons
> fix(camera): heading example

- index.d.ts
- package.json
Fixes https://github.com/react-native-mapbox-gl/maps/issues/883
Fixes the TypeScript errors we are seeing in our app and mentioned in the above issue. Also moves `@types/geojson` from `devDependencies` to `dependencies` (could alternatively be a peer dependency I guess) - this is needed because those types are imported into the types definition for this package, so it's therefore not a dev dependency.
> fix(TS): geoJson errors

- README.md
- docs/MapboxGL.md
Correcting the omission of not having any docs for MapboxGL modules static methods
Unfortunately not auto-generated
> docs(mapboxGL): Add documentation for MapboxGL methods

- docs/MarkerView.md
- docs/docs.json
- javascript/components/MarkerView.js
Based on this [ticket](https://github.com/react-native-mapbox-gl/maps/issues/962) added a propTypes check for the passed children. On more than one element, it will display a warning, which will hopefully help people when debugging issue with multiple unwrapped children.
> fix(marker-view): Add children propType check to MarkerView

- android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLModule.java
- index.d.ts
This pull request addresses issue #937 
I replicated the behaviour of `getAccessToken()` on iOS in the native Android code. Both iOS and Android versions now return a promise that either resolves to a string, or is rejected if the access token is null. Previously, the Android version returned a promise that resolved to an object with an `accessToken` property having the value of the access token.
This is a breaking change, changing the interface of `getAccessToken()` on Android.
I completed manual testing from a basic app similar to the [getting started example](https://github.com/react-native-mapbox-gl/maps/blob/master/docs/GettingStarted.md), not knowing how or if I should add tests for native Android code:
- `getAccessToken()` returns a string equal to the access token set previously …
> fix(access-token): match iOS interface for getAccessToken() on Android

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/annotation/RCTMGLPointAnnotation.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/annotation/RCTMGLPointAnnotationManager.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/events/PointAnnotationDragEvent.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/events/constants/EventKeys.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/events/constants/EventTypes.java
- docs/PointAnnotation.md
- docs/docs.json
- example/src/examples/ShowPointAnnotation.js
- index.d.ts
- ios/RCTMGL/RCTMGLMapTouchEvent.h
- ios/RCTMGL/RCTMGLMapTouchEvent.m
- ios/RCTMGL/RCTMGLPointAnnotation.h
- ios/RCTMGL/RCTMGLPointAnnotation.m
- ios/RCTMGL/RCTMGLPointAnnotationManager.m
- javascript/components/PointAnnotation.js
Expose onDrag callback for iOS and Android. As mapbox on iOS [does not update coordinates on dragging](https://github.com/mapbox/mapbox-gl-native-ios/issues/251), this adds the calculations.
> Expose onDrag callback for iOS and Android

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/CameraStop.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/CameraUpdateQueue.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/RCTMGLCamera.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
> [android] Fix padding addition

- __tests__/components/SymbolLayer.test.js
For [Issue 974](https://github.com/react-native-mapbox-gl/maps/issues/974).
I'm not sure how to fully test "textVariableAnchor" & "textRadialOffset".
> Added test for SymbolLayer

- index.d.ts
As of [1], the values for this enum are no longer numbers, but strings.
See also docs for `followUserMode` at [2].
[1] https://github.com/react-native-mapbox-gl/maps/pull/33
[2] https://github.com/react-native-mapbox-gl/maps/blob/396e77c2c9025dfbc7f8b09914aceccccda2e2bd/docs/Camera.md#mapboxglcamera-
> fix: update type declaration of UserTrackingModes

- .eslintrc.js
- __tests__/components/MapView.test.js
- example/.eslintrc.js
- example/package.json
- example/src/examples/BugReportExample.js
- example/src/examples/CacheManagement.js
- example/src/examples/CreateOfflineRegion.js
- example/src/examples/DriveTheLine.js
- example/src/examples/IndoorBuilding.js
- example/src/examples/ShowPointAnnotation.js
- example/src/examples/SymbolCircleLayer/ShapeSource.tsx
- example/src/examples/TakeSnapshotWithMap.js
- example/src/examples/WatercolorRasterTiles.js
- example/src/examples/common/Bubble.js
- example/src/examples/common/MapHeader.js
- example/src/examples/common/TabBarPage.js
- example/src/scenes/Home.js
- package.json
We had the issue, that when linting either `root` together with `example` vs `/example` alone there would be inconsistent results. 
Also, one wasn't able to run `yarn lint` without having the dependencies installed in `/example`, however when installed it could lead to conflicting plugins....
Anyways, this change now allows us to either run `yarn lint` from `root` with or without installed dependencies in `/example` and also run `yarn lint` within `/example`. 
Both will result in the same output. 
Notice, that I didn't really fix many errors in this PR. 
Changes in source files are mainly from `--fix`. 
This is somewhat to prepare for the transition to TS and align `root` and `/example` a bit for that.
Lastly, the eslint rules in the rc files are kinda opinionated by me and the projects I …
> refactor(eslint): some updates to our linting workflow

- docs/BackgroundLayer.md
- docs/CircleLayer.md
- docs/FillExtrusionLayer.md
- docs/FillLayer.md
- docs/HeatmapLayer.md
- docs/ImageSource.md
- docs/LineLayer.md
- docs/RasterLayer.md
- docs/SymbolLayer.md
- docs/docs.json
- example/src/examples/ShowPointAnnotation.js
- index.d.ts
- javascript/components/BackgroundLayer.js
- javascript/components/CircleLayer.js
- javascript/components/FillExtrusionLayer.js
- javascript/components/FillLayer.js
- javascript/components/HeatmapLayer.js
- javascript/components/ImageSource.js
- javascript/components/LineLayer.js
- javascript/components/RasterLayer.js
- javascript/components/RasterSource.js
- javascript/components/ShapeSource.js
- javascript/components/SymbolLayer.js
- javascript/components/VectorSource.js
This PR replaces optional `id`s in 
* `TileSourceProps`
* `ShapeSourceProps`
* `LayerBaseProps`
* `ImageSourceProps`
with mandatory ones. 
Hopefully this will prevent people from running into any crashes when omitting `id`s.
-----------
PREVIOUS PR DESCRIPTION
Replacing the work done in #969.
@mfazekas, don't maybe all layers expect a present `id`?
Maybe we could change the optional `id` in the `LayerBaseProps` types to required instead of optional.
Thoughts?
> fix(layer, sources): id is required

- index.d.ts
`renderMode` and `androidRenderMode` were missing from `UserLocationProps` interface. 
This PR adds them.
> fix(types): add renderMode and androidRenderMode to index.d.ts

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java
App crashes when user is trying to set `androidRenderMode` as described in issue #1022.
I think I've tracked it down to a missing non-null check in `NativeUserLocation`.
In `setRenderMode` it attempts to call `getLocationComponentManager` on `mMapView` which seems to be `null` at that point in time.
This change fixes the crash. 
Two more things I noticed though:
* no types for `androidRenderMode` in `index.d.ts` (which I will address with a follow-up PR)
* the heading indicator doesn't seem to change when using `androidRenderMode="compass"`(from the short test I did 🤷 )
Feedback appreciated, thanks 🙇 
----
this resolves #1022
> fix(user-location): fix crash issue when using androidRenderMode

- __tests__/components/BackgroundLayer.test.js
- __tests__/components/CircleLayer.test.js
- __tests__/components/HeatmapLayer.test.js
- __tests__/components/SymbolLayer.test.js
Missed the now required IDs for layers. 
Were causing tests to fail
> test(layer-id): Add the now required ID for layers

- react-native-mapbox-gl.podspec
- scripts/autogenerate.js
Deprecates:
```
ENV["REACT_NATIVE_MAPBOX_MAPBOX_IOS_VERSION"] = "6.2.1"
```
New version:
```
$ReactNativeMapboxGLIOSVersion = "6.2.1"
```
> Support mapbox 6.0 and later and switch to $ReactNativeMapboxGLIOSVersion

- example/src/examples/FlyTo.js
- ios/RCTMGL/CameraUpdateItem.m
Potential fix for issue #1058. Happy to tweak as necessary.
> Make moveTo/flyTo work for coordinates with longitude/latitude of 0

- react-native-mapbox-gl.podspec
Latest Xcode 12 fails to build while without a module to depend on React-Core directly hence this change is necessary for all native modules on iOS. For more details please check: facebook/react-native#29633
Use this branch to install with an app running on Xcode 12.
| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ❌     |
> fix: Xcode 12 compatibility

- example/ios/RNMapboxGLExample.xcodeproj/project.pbxproj
- ios/RCTMGL/CameraStop.m
- ios/RCTMGL/CameraUpdateItem.m
- ios/RCTMGL/RCTMGLMapViewManager.m
Fixes: #1032, #841
Test code:
```js
import {View, Button} from 'react-native';
import MapboxGL from '@react-native-mapbox-gl/maps';
const latitude = 40.723279;
const longitude = -73.970895;
const boundsEdge = 0.002;
/*
The error is:
Mapbox error [event]:General [code]:-1 [message]:Unable to calculate
appropriate zoom level for bounds. Vertical or horizontal padding is
greater than map's height or width.
Tested on:
- iOS Simulator, iPhone 11
- iOS Simulator, iPhone SE
- Android Emulator, Pixel 3 (API 30)
*/
// iOS: No error, but padding has no effect.
// Android: No error, and padding works.
const padding1 = {
paddingTop: 0,
paddingBottom: 0,
};
// iOS: No error, but padding has no effect.
// Android: No error, and padding works.
const padding2 = {
paddingTop: 0, …
```
> Support edgePadding with camera, set initial frame to fullscreen

- javascript/utils/Logger.js
- react-native-mapbox-gl.podspec
It seems we need `React` in addition to `React-Core` as we're using `#import <React/RCTImageLoader.h>` (was an issue on RN0.60)
> Fixed doc typo, added React to podfile

- android/rctmgl/build.gradle
See: https://docs.mapbox.com/android/maps/overview/#configure-credentials for credential configuration.
Add following to `buildscipt/ext`
```gradle
rnmbglMapboxLibs = "com.mapbox.mapboxsdk:mapbox-sdk-services:5.1.0;com.mapbox.mapboxsdk:mapbox-android-sdk:9.5.0;com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0"
rnmbglMapboxPlugins = "com.mapbox.mapboxsdk:mapbox-android-gestures:0.6.0;com.mapbox.mapboxsdk:mapbox-android-plugin-localization-v9:0.12.0;com.mapbox.mapboxsdk:mapbox-android-plugin-markerview-v9:0.4.0;com.mapbox.mapboxsdk:mapbox-sdk-turf:5.1.0"
```
Add following to `allprojects/repositories`:
```gradle
maven {
url 'https://api.mapbox.com/downloads/v2/releases/maven'
authentication {
basic(BasicAuthentication)
}
credentials {
// Do not change the username below.
// …
```
> Android: Introduce gradle variables to customize mapbox lib versions

- ios/RCTMGL/RCTMGLLogging.m
Added check before emitting `LogEvent` messages via `RCTEventEmitter`.
On iOS each `RCTEventEmitter` module needs to track whether or not there are observers before sending events. Otherwise when events are emitted without observers a (console) warning is triggered by react-native, in this case: 
> Sending `LogEvent` with no listeners registered.
In practice I experienced Mapbox sending out messages after unmount causing the above warning.
Similar to https://github.com/react-native-mapbox-gl/maps/blob/f2eb9d7bb55cb3227b2ccc432de11e13246c689f/ios/RCTMGL/RCTMGLLocationModule.m#L85-L96
> Prevent emitting log events without listeners

- ios/install.md
Following ticket https://github.com/react-native-mapbox-gl/maps/issues/1103 to explain how to use a custom version of the Mapbox Maps SDK for iOS.
> Update install.md for ios: Mapbox Maps SDK

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTSource.java
Fixes/silences the following error:
```
java.lang.Error: Cannot remove detached source
at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRemoveSource(NativeMapView.java)
at com.mapbox.mapboxsdk.maps.NativeMapView.removeSource(NativeMapView.java:925)
at com.mapbox.mapboxsdk.maps.Style.removeSource(Style.java:175)
at com.mapbox.rctmgl.components.styles.sources.RCTSource.removeFromMap(RCTSource.java:158)
at com.mapbox.rctmgl.components.mapview.RCTMGLMapView.removeAllSourcesFromMap(RCTMGLMapView.java:1229)
at com.mapbox.rctmgl.components.mapview.RCTMGLMapView.setReactStyleURL(RCTMGLMapView.java:755)
at com.mapbox.rctmgl.components.mapview.RCTMGLMapViewManager.setStyleURL(RCTMGLMapViewManager.java:120)
at java.lang.reflect.Method.invoke(Method.java)
```
I could not reproduce the root cause, …
> Make errors during remove source a warning rather than a hard error

- react-native-mapbox-gl.podspec
We've used to use `~> 5.8`, wit #1052 we've replaced it with `~> 5.8.0`. But `~> 5.8` evaluates to `5.9.0` while `~> 5.8.0` evaluates to `5.8.0`.
> ~>5.9.0 is the equivalent for ~>5.8 dep we've used before

- javascript/components/UserLocation.js
Fixing https://github.com/react-native-mapbox-gl/maps/issues/854
There are two conditions where _LocationManager_ have to run:
- When user provides _onUpdate_ callback. 
- When _renderMode_ is _Normal_ and _UserLocation_ component is visible, then need _LocationManager_ running in order to update user location marker(blue dot) on the map.
_LocationManager_ in this context refers to JS _LocationManager_. In other words whether we need to push a stream of location changes over bridge.
> Fix: onUpdate not called when renderMode is native

- __tests__/components/UserLocation.test.js
- javascript/components/UserLocation.js
The change introduced by PR #1135 caused the `UserLocation` tests to fail.
This fixes the failing test
> fix failing #needsLocationManagerRunning tests

- index.d.ts
The example here uses a string for RasterLayer.sourceID:
https://github.com/react-native-mapbox-gl/maps/blob/397482d4adc7e34cea30b39151c638e418a66f89/example/src/examples/WatercolorRasterTiles.js#L62
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/react-native-mapbox-gl/maps/1142)
> RasterLayer.sourceID should be string

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocationManager.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLAndroidTextureMapView.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLAndroidTextureMapViewManager.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/layers/RCTLayer.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLImageSource.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLShapeSourceManager.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/events/EventEmitter.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/location/LocationManager.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/utils/BitmapUtils.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/utils/ConvertUtils.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/utils/DownloadMapImageTask.java
- example/android/app/build.gradle
Fixing issue https://github.com/react-native-mapbox-gl/maps/issues/1183 . This PR is just extending previous PR to one more file https://github.com/react-native-mapbox-gl/maps/pull/260.
And enabling ProGuard which was by accident switch off in https://github.com/react-native-mapbox-gl/maps/pull/432
> Fix: App crash when ProGuard is set to true

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
Fix inccorecct position of compass when `compassViewPosition` on `MapView` is set to `2`
> Fix inccorecct position of compass when `compassViewPosition` on `MapView` is set to `2`

- example/package.json
remove [`react-native-safe-area-view`](https://github.com/react-navigation/react-native-safe-area-view#react-native-safe-area-view), as it is deprecated and we do not need it
> build(react-navigation): remove react-native-safe-area-view

- javascript/components/UserLocation.js
`_onLocationUpdate`  would not check if the `location` was actual valide. 
Instead it would go though it's motions and set the state, thus calling listeners, like `UserLocation` components `onUpdate` callbacks. 
Instead we should check if there even is a proper location and exit early if there isn't
This superseeds #1170
> fix(user-location): exit early without proper location

- example/package.json
we have this `install` dependency and we don't seem to use it 🤷🏿 
removing
> build: remove install dependency

- javascript/components/HeadingIndicator.js
Fixes the bug described in this issues: https://github.com/react-native-mapbox-gl/maps/issues/1214 https://github.com/react-native-mapbox-gl/maps/issues/1023
> Fix heading indicator alignment

- index.d.ts
- Use the suggested definition for `ExpressionField` with a recursive type reference
> Fix: Improve ExpressionField type

- example/ios/Podfile
- example/ios/RNMapboxGLExample.xcodeproj/project.pbxproj
- ios/install.md
- react-native-mapbox-gl.podspec
Fixes: #1097 
This needs to be added to the Podfile:
```ruby
pre_install do |installer|
$RNMBGL.pre_install(installer)
...
end
```
```ruby
post_install do |installer|
$RNMBGL.post_install(installer)
....
end
```
> Use build_type to handle non use_frameworks

- ios/RCTMGL/RCTMGLMapViewManager.m
Fixes #1008
Thanks to @VladMatvei for the suggested solution!
See referenced issue for more context about the bug.
This is narrows down the check to see if it is not a cancelled pan by a user-interaction. In which case it does not short-circuit the method. A pan made by a user, which is cancelled, should still dispatch the `onRegionDidChange`-event.
> fix: No event on cancelled user pan

- example/ios/Podfile
as discussed [here](https://github.com/react-native-mapbox-gl/maps/pull/1262#issuecomment-791588054), 
ios builds with flipper integration won't build otherwise
> fix compile issues with flipper

- example/e2e/config.json
- example/e2e/environment.js
- example/e2e/firstTest.e2e.js
- example/package.json
This adds detox to the `/example` app. 
At the moment this only supports iOS. 
Next step: add github action
> feat(test): add detox

- index.d.ts
Adds a missing type definition for [MapboxGL.offlineManager.invalidatePack(name)](https://github.com/react-native-mapbox-gl/maps/blob/c42e96c3aee94758fe810a9fc06ade81d1352422/docs/OfflineManager.md#invalidatepackname)
> Fix type definition for OfflineManager

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLShapeSource.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLShapeSourceManager.java
- docs/ShapeSource.md
- docs/docs.json
- index.d.ts
- ios/RCTMGL/RCTMGLShapeSource.h
- ios/RCTMGL/RCTMGLShapeSource.m
- ios/RCTMGL/RCTMGLShapeSourceManager.m
- javascript/components/ShapeSource.js
This allows using the mapbox sdk to get the zoom needed to expand a cluster by adding  getClusterExpansionZoom to instances of ShapeSource.
The code is mostly adapted from a similar method `features` on ShapeSource.
Tested these changes in an app on iOS and android.
```js
const source = React.useRef(null);
...
<MapboxGL.ShapeSource
ref={source}
onPress={async (e) => {
const feature = e.features[0];
if (feature.properties?.cluster) {
const zoom = await source.current.getClusterExpansionZoom(
feature.properties.cluster_id,
);
// use zoom
}
}}
cluster
clusterMaxZoomLevel={13}
clusterRadius={40}
/>
```
> Add getClusterExpansionZoom to ShapeSource

- index.d.ts
I agree with some of the discussion in #1240 so I decided to keep things simpler. This just adds a basic type definition. There's a bit of a question of how to import `Animated` from React Native without conflicting with the `Animated` namespace defined in the types file, but I took a guess. Open to other suggestions.
> Add type definition for AnimatedPoint

- example/ios/Podfile
iOS build fine on CI for our detox builds (Release),  
however locally (debug) it expects flipper to be included. 
This is supposed to take care of this
> build(detox): disable flipper only on CI

- CHANGELOG.md
- android/install.md
- android/rctmgl/build.gradle
- example/android/build.gradle
- example/ios/Podfile
- ios/install.md
- react-native-mapbox-gl.podspec
This PR allows to specify the Mapbox library to be consumed via SwiftPackageManager. This means MapLibre for example can be used instead of Mapbox.
Fixes #1273 
Podfile:
```ruby
$RNMBGL_Use_SPM = {
url: "https://github.com/maplibre/maplibre-gl-native-distribution",
requirement: {
kind: "upToNextMajorVersion",
minimumVersion: "5.11.0"
},
product_name: "Mapbox"
}
pre_install do |installer|
$RNMBGL.pre_install(installer)
end
...
post_install do |installer|
flipper_post_install(installer)
$RNMBGL.post_install(installer)
end
```
Top level build.gradle:
```groovy
buildscript {
ext {
...
rnmbglMapboxLibs = {
implementation ("org.maplibre.gl:android-sdk:9.2.1")
implementation ("com.mapbox.mapboxsdk:mapbox-sdk-turf:5.3.0")
}
rnmbglMapboxPlugins = {
implementation …
```
> Allow Mapbox or MapLibre from SPM on iOS, and different libs on android

- CHANGELOG.md
- README.md
- docs/Logger.md
- index.d.ts
As the title implies, this adds types for the public methods of the `Logger` class. 
This should be enough to us it in a `.ts|x` file without it screaming in agony. 
Fixes #1289
* ~[ ] I have tested this on a device/simulator for each compatible OS~
* ~[ ] I added/ updated a sample  (`/example`)~
> feat(ts): add types for Logger class

- CHANGELOG.md
- RELEASE.md
- package.json
Preparation for release of `8.2.0-beta2`
Updates `Changelog` & adds a `RELEASE.md` file to share knowledge on how to prepare and publish a release
> chore: release 8.2.0 beta2

- CHANGELOG.md
- index.d.ts
This adds some missing props to the TypeScript lib def file that I have encountered. 
I am aware of #1067, but I guess it will still take some time before that one is merged and released.
I have not used `onImageMissing` myself, but from looking at the source code it seems like this function is called with the name of the missing image as a string. Please correct me if I'm wrong.
> Add some missing props to TypeScript lib def

- CHANGELOG.md
- android/rctmgl/build.gradle
- Fixes problem mentioned here https://github.com/react-native-mapbox-gl/maps/pull/1388#issuecomment-856194294
- Bumps okhttp default version which appears to be a flat fix for a handful of versioning issues: https://stackoverflow.com/a/65049690/4047926
> Bump okhttp to 4.9.0

- CHANGELOG.md
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
When dynamically changing a `MapView`s `styleURL` prop that is a locally defined style.json `setReactStyleURL` will call `MapboxMap`s `setStyle`.  
Without a passed in Builder, it'll use the default one - which assumes that the style stings is an URI (which it is not). 
To prevent a `Mapbox error [HTTP] Unable to parse resourceUrl` error  we need to pass in our own Builder that uses `fromJSON` instead `fromUri`
Note:
* this is not an issue on initial load - only on prop changes
* this is not an issue on iOS
@mattijsf, I've added you as a reviewer, because this is relevant to the changes we implemented
~* [ ] I updated the documentation `yarn generate`~
~* [ ] I updated the typings files (`index.d.ts`)~
~* [ ] I added/ updated a sample  (`/example`)~
> Support dynamically changing local JSON in styleURL

- .eslintignore
- .gitignore
- .npmignore
- CHANGELOG.md
- README.md
- app.plugin.js
- package.json
- plugin/install.md
- plugin/jest.config.js
- plugin/src/__tests__/__snapshots__/withMapbox-test.ts.snap
- plugin/src/__tests__/fixtures/cocoapodFiles.ts
- plugin/src/__tests__/withMapbox-test.ts
- plugin/src/withMapbox.ts
- plugin/tsconfig.json
With Expo SDK 41 we've rolled out an interface called [config plugins](https://docs.expo.io/guides/config-plugins/) which lets users add native modules that aren't in the Expo Go app to their native cloud builds and locally when [prebuilding](https://expo.fyi/prebuilding).
This is a [highly requested package](https://expo.canny.io/feature-requests/p/mapbox-gl) so I've created the plugin personally.
We’re still working on improving the development experience for config plugins and custom managed workflow, feel free to add any feedback. People won’t be able to use this in an Expo-Go-like-app until we release “Expo Development Client” ([more info](https://blog.expo.io/expo-managed-workflow-in-2021-d1c9b68aa10)). 
This plugin is a bit "dangerous" as it uses regexes to add podfile …
> Created Expo config plugin

- package.json
- plugin/src/withMapbox.ts
The android test seems to fail when the package.json cannot be resolved in the plugin, this wouldn't happen in practice and the package.json check is just to ensure colliding versions don't get [run more than once](https://docs.expo.io/guides/config-plugins/#adding-plugins-to-pluginhistory). Wrap the check in a try/catch and fallback on unversioned functionality.
> [expo][config plugin] fallback on unversioned if package.json cannot be found

- package.json
> Add compatibility with React 17

- android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLLocationModule.java
We got some issues with locations being probed while the app is in the background.  
This is one of those issues: https://github.com/react-native-mapbox-gl/maps/issues/1363#
And as mentioned in this comment: https://github.com/react-native-mapbox-gl/maps/issues/1363#issuecomment-852849109
The locationmanager is being started onHostDestroy.  
Probably a copy/ paste error from the big expression update.
> stopLocationManger on Destroy

- CHANGELOG.md
- index.d.ts
The textStyle prop is passed to a <Text/> component, not a <View/>.
Therefore its type must be of type TextStyle, not ViewStyle.
> Fix TypeScript type for Callout's textStyle prop

- babel.config.js
- package.json
I believe we don't need these anymore:
1. '@babel/plugin-transform-flow-strip-types'
2. '@babel/plugin-transform-exponentiation-operator'
<br>
1. we don't use `flow` anywhere
2. I've checked, and we're not using the exponentiation (`**`) operator anywhere
So, out they go 🤷🏿‍♀️
> build: remove obsolete babel plugins

- CHANGELOG.md
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/LocationComponentManager.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
- example/src/examples/UserLocation/SetTintColor.js
- example/src/scenes/Home.js
PR  #1465 added editing of tintColor for Android, unfortunately it didn't update dynamically.
This extends that PR with that functionality and adds a `Set Tint Color` example
red | yellow | green
---|---|---
read | yellow | green
---|---|---
> feat(android): dynamically update `tintColor` 

- example/README.md
tiny correction => Android **E**mulators
none
> fix(readme): correct typo for android emulator example

- CHANGELOG.md
- example/.gitignore
- example/README.md
During my first time setting-up the repository and the examples I stumbled over these minor improvements.
This PR does:
- align the example docs with `yarn` (and not `npm`)
- add the created env-files from the set-up to gitignore
> chore(example): align install steps with yarn, ignore created env files

- CHANGELOG.md
- __tests__/components/Light.test.js
- example/src/examples/LineLayer/GradientLine.js
- javascript/components/Light.js
Unit tests for the small component `Light.js` is a first step to contribute to missing component tests.
**Please note:**
When I tried to commit via the command line, the `pre-commit` linting step threw an error on `LineGradient`  because of inline styles. I fixed that by extracting the styles.
Please let me know if it would have been more appropriate to disabled the linting rule.
none
> test: add unit tests for component light

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLShapeSource.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLShapeSourceManager.java
- docs/ShapeSource.md
- docs/docs.json
- index.d.ts
- ios/RCTMGL/RCTMGLShapeSource.h
- ios/RCTMGL/RCTMGLShapeSource.m
- ios/RCTMGL/RCTMGLShapeSourceManager.m
- javascript/components/ShapeSource.js
Adds `getClusterChildren` method to `ShapeSource` that allows you to retrieve the features from a cluster by the cluster's ID.  (on the next zoom level)
Features may include nested clusters as well.
```javascript
shapeSourceRef.current.getClusterChildren(clusterId);
```
> Adds getClusterChildren for iOS and Android

- CHANGELOG.md
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLShapeSource.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLShapeSourceManager.java
- docs/ShapeSource.md
- docs/docs.json
- index.d.ts
- ios/RCTMGL/RCTMGLShapeSource.h
- ios/RCTMGL/RCTMGLShapeSource.m
- ios/RCTMGL/RCTMGLShapeSourceManager.m
- javascript/components/ShapeSource.js
Since current implementation of `getClusterExpansionZoom`, `getClusterLeaves` and `getClusterChildren` uses querySourceFeatures / featuresMatchingPredicate to get desired data, it sets a limitation on functionality provided by native (original) corresponding methods. For now, obtaining needed data from this method is only possible for the clusters that are currently rendered on the map. But according to docs of the SDK it should be possible to use it on any cluster ( even deeply nested )
**This PR updates these methods by passing the cluster itself not cluster_id**.
Possible use case:
To zoom or just find a cluster for any single point on the map. 
Solution:
Recursively use `getClusterChildren(rootCluster)` to find desired cluster and then with …
> Update ShapeSource methods to make it usable with any cluster

- example/package.json
- example/src/examples/SymbolCircleLayer/EarthQuakes.js
Adds `getCluserLeaves` functionality to our `Clustering Earthquakes` example.  
Questions about using this feature came up quite often, so there you go, now we have a usecase to point to.
* open example app
* select `Symbol/CirleLayer`
* select `Clustering Earthquakes`
* press on any earthquake cuslter
* observer the rendered Overlay with a list of useful informations about the individual earthquakes within the cluster
> feat(shapesource): add getClusterLeaves functionality to example

- CHANGELOG.md
- android/install.md
- android/rctmgl/build.gradle
As mentioned in
https://github.com/react-native-mapbox-gl/maps/pull/1376
https://github.com/react-native-mapbox-gl/maps/issues/1286
the missing dependency is leading to more and more headaches,  
especially for Expo user who can not change them manually.
Therefore - adding it to the default setup
> build(android): add telemetry dependency to default build setup

- __tests__/components/Camera.test.js
Fixes [test failures](https://github.com/react-native-mapbox-gl/maps/pull/1619#issuecomment-968646905) caused by #1619 . It wasn't an issue with the feature, just with the test - the default Camera props were not being used in the test configurations, meaning `allowUpdates` was not defaulting to `true`, as it would in actual usage.
> Spread default camera props into test configs

- package.json
=> this PR has to be merged first https://github.com/react-native-mapbox-gl/maps/pull/1638
----
Bumps [eslint-plugin-import](https://github.com/import-js/eslint-plugin-import) from 2.23.4 to 2.25.2.
- [Release notes](https://github.com/import-js/eslint-plugin-import/releases)
- [Changelog](https://github.com/import-js/eslint-plugin-import/blob/main/CHANGELOG.md)
- [Commits](https://github.com/import-js/eslint-plugin-import/compare/v2.23.4...v2.25.2)
---
updated-dependencies:
- dependency-name: eslint-plugin-import
dependency-type: direct:development
update-type: version-update:semver-minor
...
Signed-off-by: dependabot[bot] <support@github.com>
> build(deps-dev): bump eslint-plugin-import from 2.23.4 to 2.25.2

- CHANGELOG.md
- __tests__/__mocks__/react-native.mock.js
- __tests__/modules/location/locationManager.test.js
- __tests__/modules/offline/offlineManager.test.js
- android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLLocationModule.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLLogging.java
- android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLOfflineModule.java
- javascript/modules/location/locationManager.js
- javascript/modules/offline/offlineManager.js
Native `EventEmitters` api seems to have slightly changed. 
They expect a `addListener` `removeListener` method on the native modules. 
Would be showing warning messages like these:
`'new NativeEventEmitter() was called with a non-null argument without the required addListener method.'`
See: https://github.com/facebook/react-native/commit/114be1d2170bae2d29da749c07b45acf931e51e2
<br>
Additionally, `EventEmitter.js` itself does change `removeListener` => just `remove`, which is called on the return value of `addListener`. 
I've changed the code accordingly.
Would be showing warning messages like these:
`EventEmitter.removeListener(): Method has been deprecated. Please instead use remove() on the subscription returned by EventEmitter.addListener.`
What I didn't do where extensive test on …
> fix: EventEmitter warnings

- android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleValue.java
- example/src/examples/BugReportExample.js
Fixes a bug when setting transition-related style. (`duration` is always overwritten by `delay` value)
You can reproduce this using bug-report example.
Android (no animation)
https://user-images.githubusercontent.com/42024893/143579516-5531d406-f8a5-4ea3-a9d8-98176301260a.mp4
iOS (with animation)
https://user-images.githubusercontent.com/42024893/143580769-d3865954-5641-4fef-8ccc-7d37b6ab68e8.mp4
> fix: correct transition style value

- CHANGELOG.md
- example/ios/Podfile
- example/ios/RNMapboxGLExample/AppDelegate.m
Changes build configurations to allow the `example` project to build on M1 Macs.
> fix(build):allow running example on M1

- CHANGELOG.md
- index.d.ts
Hey,
I noticed there is no TypeScript typing for MapViews's preferredFramesPerSecond prop. TypeScript is giving me errors. This PR fixes the problem.
Cheers!
> fix: add TypeScript type for MapViews's preferredFramesPerSecond prop

- example/android/build.gradle
Try to fix build error on CI
```
> Task :rctmgl:compileDebugKotlin FAILED
[180](https://github.com/rnmapbox/maps/runs/5573673396?check_suite_focus=true#step:8:180)
class com.mapbox.rctmgl.components.mapview.RCTMGLMapView, unresolved supertypes: MapView, OnMapClickListener, OnMapLongClickListener, OnCameraIsChangingListener, OnCameraDidChangeListener, OnDidFailLoadingMapListener, OnDidFinishLoadingMapListener, OnWillStartRenderingFrameListener, OnDidFinishRenderingFrameListener, OnWillStartRenderingMapListener, OnDidFinishRenderingMapListener, OnDidFinishLoadingStyleListener, OnStyleImageMissingListener
[181](https://github.com/rnmapbox/maps/runs/5573673396?check_suite_focus=true#step:8:181)
class com.mapbox.rctmgl.components.annotation.MarkerViewManager, unresolved supertypes: …
```
> Fix kotlin error with - (1.6.* or 1.5.3*)

- android/rctmgl/src/main/java-maplibre/com/mapbox/rctmgl/impl/InstanceManagerImpl.java
Without this change the build in mapbox styles don't work anymore with a valid mapbox key.
Tested the example app with a valid access key and a custom titleserver without a custom key both work now.
Only getAccessToken will not work on MapLibre, i don't know how to fix that. 
- [x ] I have tested this on a device/simulator for each compatible OS
> Fix MapLibre with mapbox maps

- CHANGELOG.md
- android/rctmgl/build.gradle
- example/android/build.gradle
- rnmapbox-maps.podspec
check for Mapbox in SPM if we're using cocoapods
Fixes: #1806
Fixes: #1804
> Remove safeExtGet from buildscipt, 

- plugin/build/withMapbox.d.ts
- plugin/build/withMapbox.js
- plugin/install.md
- plugin/src/withMapbox.ts
- rnmapbox-maps.podspec
Normally credentials are configured via `.netrc` for downloading Mapbox. But with expo `eas` this is not possible. 
We now support `RNMapboxMapsDownloadToken` plugin config on both iOS and android for expo builds.
> Expo/ios RNMapboxMapsDownloadToken support

- example/src/examples/V10/CameraAnimation.js
- example/src/scenes/Home.js
- ios/RCTMGL-v10/MGLModule.swift
- ios/RCTMGL-v10/RCTMGLCamera.swift
Implements camera bounds-based animation and easing using the V10 SDK. Currently implemented only on iOS, and I can port it to Android if there's agreement that this can be merged into `main`.
https://user-images.githubusercontent.com/2423291/163045880-9d5c1ff3-741e-481f-9261-0f293d9f01b2.mov
> Implement camera bounds-based animation and easing with V10 SDK

- ios/RCTMGL-v10/RCTMGLCamera.swift
- ios/RCTMGL-v10/RCTMGLFillLayer.swift
- ios/RCTMGL-v10/RCTMGLImages.swift
- ios/RCTMGL-v10/RCTMGLLayer.swift
- ios/RCTMGL-v10/RCTMGLLight.swift
- ios/RCTMGL-v10/RCTMGLMapView.swift
- ios/RCTMGL-v10/RCTMGLMapViewManager.m
- ios/RCTMGL-v10/RCTMGLMapViewManager.swift
- ios/RCTMGL-v10/RCTMGLMarkerView.swift
- ios/RCTMGL-v10/RCTMGLPointAnnotation.swift
- ios/RCTMGL-v10/RCTMGLSource.swift
- ios/RCTMGL-v10/RCTMGLStyleValue.swift
- ios/RCTMGL-v10/RCTMGLTerrain.swift
- javascript/utils/index.js
v10 iOS, fixes the 2 examples `ShowAndHideLayer.js` and `SourceLayerVisibility`
1. Allow components (most of them for now except camera), to defer addToMap after style has loaded. This is required for layers referencing existing layers in the style
2. implement `setSourceVisibility`
3. Fix visibility style constant
> v10 iOS: Wait for style load before adding layers, show/hide layer implemented

- ios/RCTMGL-v10/RCTMGLMapView.swift
In the new swift implementation, the MapView's removeReactSubview is never called by the RTCManager, resulting in removed React Components not being unmounted from the map.
To solve this, the corresponding super methods are called resulting in the removeReactSubview method being called and layers removed from the map.
```javascript
const App = () => {
const [visible, setVisible] = useState(false)
return (
<MapView
onPress={() => setVisible(!visible)}
style={{flex: 1}}>
{visible && <RasterSource
id="source"
tileUrlTemplates={['https://stamen-tiles.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.jpg']}>
<RasterLayer
id="raster"
style={{rasterOpacity: 0.5}}
/>
</RasterSource>}
</MapView>
)
}
```
> Fixing unmounting of layers during runtime (v10, iOS)

- ios/RCTMGL-v10/RCTMGLMapView.swift
- ios/RCTMGL-v10/RCTMGLMapViewManager.m
Setting the MapView's ```zoomEnabled```, ```scrollEnabled```, ```rotateEnabled``` and ```pitchEnabled``` props was not handled by the swift side of things yet.
Reminder here: as soon as rnmapbox will migrate to the 10.4 sdk, additional [GestureOptions](https://docs.mapbox.com/ios/maps/api/10.4.0/Structs/GestureOptions.html) can be set (as prepared in the code)
```javascript
<MapView
rotateEnabled={false}
pitchEnabled={false}
zoomEnabled={false}
scrollEnabled={false}
/>
```
> Add handlers for MapViews zoom/scroll/rotate/pitchEnabled props (v10, iOS)

- index.d.ts
The typing file didn't include a couple of valid (and now with v10 working) filter expressions.
This PR adds them to the typing file.
* Types
* image
* number-format
* Feature data
*  accumulated
* Lookup
* in
* index-of
* slice
* Decisions
* within
* Color
* to-rgba
* Math
* distance
> Add missing filter expressions to type file

- .gitignore
- Ignores any project `Gemfile`s for anybody[0] who wants to install CocoaPods etc. project-locally
- Ignores the local directory created by running `bundle install` in a directory with a `Gemfile`
- Some very minor cleanup to the `.gitignore`
[0] me
> Ignore Ruby gems and local bundler files, cleanup

- docs/MapView.md
- docs/docs.json
- index.d.ts
- ios/RCTMGL-v10/RCTMGLMapView.swift
- ios/RCTMGL-v10/RCTMGLMapViewManager.m
- javascript/components/MapView.js
v10 comes with a scale bar in the top left - this PR adds a ```scaleBarEnabled``` prop handler to the MapView, allowing to enable or disable the scale bar.
```javascript
<MapView scaleBarEnabled={false} />
```
> Add handler and documentation for MapView's scaleBarEnabled prop

- ios/RCTMGL-v10/RCTMGLLayer.swift
Fixes a potential crash (not always reproducible, but reminiscent of crashes I used to get pre-v10) that generally has this shape
> Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: MapboxMaps.StyleError(rawValue: "my-cool-layer-id does not exist")
In general, I think this library should avoid crashing at all costs, meaning gracefully handling exceptions when possible.
> Prevent possible crash on add/remove layer

- .github/workflows/android-actions.yml
- .github/workflows/ios-actions.yml
- .github/workflows/on-push.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- ios/RCTMGL-v10/RCTMGLImageQueue.swift
Fixes: #1866 
It looks in production the block passed to loadImage is called immediately. That causes operation to be released, therefore weakSelf will be nil.
```swift
let cancellationBlock = loader.loadImage(with: weakSelf.urlRequest, size: .zero, scale: CGFloat(weakSelf.scale), clipped: true, resizeMode: .stretch, progressBlock: { _,_  in }, partialLoad: { _ in }) { error, image in
_ = weakSelf.setState(state:.Finished, except:.Finished) // <<<< - (1) this can result in self being destroyed
}
// <<<< -(2) weakSelf might be nil if (1) was executed before
weakSelf.cancellationBlock = cancellationBlock
```
Use this to reproduce in  BugReportExample in example app - needs to run in production.
```
import {MapView, ShapeSource, SymbolLayer, Camera} from …
```
> iOS, v10 Fix race condition in production with images

- ios/RCTMGL-v10/RCTMGLMapView.swift
When a tap happens we first try to see if any sources were hit with `queryRenderedFeatures`, and if none we'll generate an `onPress` for the map. 
If the `queryRenderedFeatures` returns 0 features we not consider that as a hit, so we can give it to the map.
Fixes the custom icon example
> V10, iOS: Only consider a source hit, when non empty features were hit

- example/ios/Podfile.lock
- example/src/examples/FillRasterLayer/QueryWithRect.js
- ios/RCTMGL-v10/Extensions/Array+asExpressions.swift
- ios/RCTMGL-v10/Extensions/CLLocationCoordinate2D+toArray.swift
- ios/RCTMGL-v10/Extensions/DefaultStringInterpolation+optional.swift
- ios/RCTMGL-v10/Extensions/Encodable+ToJSON.swift
- ios/RCTMGL-v10/RCTMGLFillLayer.swift
- ios/RCTMGL-v10/RCTMGLLogging.swift
- ios/RCTMGL-v10/RCTMGLMapView.swift
- ios/RCTMGL-v10/RCTMGLMapViewManager.m
- ios/RCTMGL-v10/RCTMGLMapViewManager.swift
- package.json
v10, iOS:
- implement queryRenderedFeaturesAtPoint, queryRenderedFeaturesInRect
- move extensions to `Extensions` folder
- do not shallow expecetions in `toJSON`, log the exceptions
- simplify `MapView` method implementation with `withMapView` and `withMapboxMap`
> iOS, v10: add queryRenderedFeaturesAtPoint/InRect

- ios/RCTMGL-v10/RCTMGLMapView.swift
- ios/RCTMGL-v10/RCTMGLMapViewManager.m
- ios/RCTMGL-v10/RCTMGLMapViewManager.swift
- ios/RCTMGL-v10/RCTMGLShapeSource.swift
- package.json
v10, iOS:
- Workaround for upstream issue that GeoJSONSourceData cannot decode a simple `.geometry`
- Implement `getCoordinateFromView`, `getPointInView`
> Allow geometry shapes, and impl getCoordinateFromView, getPointInView

- docs/MapView.md
- docs/docs.json
- ios/RCTMGL-v10/MGLModule.swift
- ios/RCTMGL-v10/RCTMGLEvent.swift
- ios/RCTMGL-v10/RCTMGLLogging.swift
- ios/RCTMGL-v10/RCTMGLMapView.swift
- ios/RCTMGL-v10/RCTMGLMapViewManager.m
- ios/RCTMGL-v10/RCTMGLMapViewManager.swift
- javascript/components/MapView.js
- onCameraChanged, onMapIdle is optional on v10 (now iOS only) and marked as experimental
- v10 will call onRegionIsChanging/onRegionDidChanging if those are defined (and no onCameraChanged, onMapIdle)
- since 1.5 now fixed https://github.com/mapbox/mapbox-maps-ios/pull/1275, use `layoutSubviews` 
- MapView.swift reorg
> Added RegionIs/DidChange compat to iOS,v10

- index.d.ts
Fixes: #1907 , #1901
Regression caused by this commit:
https://github.com/rnmapbox/maps/commit/2c7ad017233dcae10ddef2da45ed2ae0bd2a4347
> Added back default MapboGL export

- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt
Fixed null exception from JSONObject string.length introduced with the change to Kotlin and null variables
> Fix for android MapView styleurl error if null

- ios/RCTMGL-v10/MGLSnapshotModule.swift
- ios/RCTMGL-v10/RCTMGLLogging.swift
V10, iOS:
- Fix RCTMGL error description
- MGLSnapshotModule supports bounds now (previously only centerCoordinate was supported)
> Fix error to string conversion, support bounds for snapshotter

- index.d.ts
- ios/RCTMGL/MGLModule.m
[iOS, maplibre]
FixesiOS: #1861
Export `useWellKnownTileServer` as `setWellKnownTileServer`. Not yet implemented on Android or v10 versions (will be no-op on v10)
```jsx
MapboxGL.setWellKnownTileServer(MapboxGL.TileServers.Mapbox);
```
> [iOS, maplibre] add setWellKnownTileServer

- package.json
- scripts/autogenerate.js
This enables installing from GitHub, like `npm install rnmapbox/maps#chore/typescript`.
> Generate lib folder in prepare script

- ios/RCTMGL-v10/RCTMGLShapeSource.swift
- ios/RCTMGL-v10/RCTMGLShapeSourceManager.m
- ios/RCTMGL-v10/RCTMGLShapeSourceManager.swift
- ios/RCTMGL-v10/RCTMGLStyleValue.swift
iOS,v10: Fixes getClusterLeaves to use the new interface (see #1499), and fixes: #1930
> iOS,v10: ShapeSource#getClusterLeaves

- ios/RCTMGL/MGLModule.m
Adds a missing semicolon preventing a successful build on iOS.
> Add semicolon

- android/rctmgl/src/main/java-mapboxgl/common/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
I was getting an array-as-string type conversion error on the line with `mManager.receiveCommand(...)`. I don't have time to look more deeply into it, but this at least prevents a crash while delivering a warning.
> Warn instead of crashing on `onDidFinishRenderingMap` error

- CHANGELOG.md
- android/rctmgl/src/main/java-mapboxgl/common/com/mapbox/rctmgl/modules/RCTMGLModule.java
- android/rctmgl/src/main/java-mapboxgl/mapbox/com/mapbox/rctmgl/impl/InstanceManagerImpl.java
- android/rctmgl/src/main/java-mapboxgl/maplibre/com/mapbox/rctmgl/impl/InstanceManagerImpl.java
- docs/MapboxGL.md
- javascript/utils/Logger.js
Impemented setWellKnownTileServer for android.
*BREAKING CHANGE*: setWellKnownTileServer is now required on maplibre before setting access token. This is because consuming mapbox from maplibre will have different pricing. So user cannot consume mapbox with maplibre by mistake/without being aware of that.
See #1935
> android, maplibre,mapbox-gl: add setWellKnownTileServer impl

- ios/RCTMGL-v10/RCTMGLBackgroundLayer.swift
- ios/RCTMGL-v10/RCTMGLCircleLayer.swift
- ios/RCTMGL-v10/RCTMGLFillExtrustionLayer.swift
- ios/RCTMGL-v10/RCTMGLFillLayer.swift
- ios/RCTMGL-v10/RCTMGLHeatmapLayer.swift
- ios/RCTMGL-v10/RCTMGLLayer.swift
- ios/RCTMGL-v10/RCTMGLLineLayer.swift
- ios/RCTMGL-v10/RCTMGLMapView.swift
- ios/RCTMGL-v10/RCTMGLRasterLayer.swift
- ios/RCTMGL-v10/RCTMGLSkyLayer.swift
- ios/RCTMGL-v10/RCTMGLSymbolLayer.swift
- add layers/sources inside another view
- also remote `try!` from apply, and log errors instead
It seems that after onNext(.styleLoaded ... ) mapboxMap.style.isLoaded is not true. So this logic doesn't works:
```swift
if mapboxMap.style.isLoaded {
block()
} else {
mapboxMap.onNext(.styleLoaded) {
block() 
}
}
```
> v10, iOS: Implement own style.isLoaded, and onNext(.styleLoaded), 

- android/rctmgl/src/main/java-mapboxgl/mapbox/com/mapbox/rctmgl/impl/InstanceManagerImpl.java
> Add missing imports for Logger, Map and HashMap to mapbox-gl InstanceManagerImpl

- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt
Implemented missing onMapLongClick callback for android v10
> added onMapLongClick event (v10, android)

- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/modules/RCTMGLLocationModule.java
Adding `addListener` and `removeListeners` to remove the following warning: 
```
`new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
```
> Adding `addListener` and `removeListeners`

- setup-jest.js
Adding missing `DidFinishRenderingMapFully` EventType to setup-jest.js
Removes warning when running jest: 
```typescript
console.warn
rnmapbox maps: DidFinishRenderingMapFully is not supported
at warn (node_modules/@rnmapbox/maps/javascript/components/MapView.js:365:21)
at MapView.addIfHasHandler [as _setHandledMapChangedEvents] (node_modules/@rnmapbox/maps/javascript/components/MapView.js:386:7)
at MapView._setHandledMapChangedEvents [as UNSAFE_componentWillReceiveProps] (node_modules/@rnmapbox/maps/javascript/components/MapView.js:354:10)
at callComponentWillReceiveProps (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4114:14)
at updateClassInstance (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4312:7)
at updateClassComponent …
```
> Adding missing EventType

- docs/MapView.md
- docs/docs.json
- ios/RCTMGL-v10/RCTMGLMapView.swift
- ios/RCTMGL-v10/RCTMGLMapViewManager.m
- javascript/components/MapView.js
Support `compassViewMargins` and `compassViewPosition` for v10 on iOS
See #1837
> Support compassViewMargins and compassViewPosition in v10 as well

- ios/RCTMGL-v10/Extensions/CLLocationCoordinate2D+validate.swift
- ios/RCTMGL-v10/RCTMGLCamera.swift
- ios/RCTMGL-v10/RCTMGLLayer.swift
- ios/RCTMGL-v10/RCTMGLMarkerView.swift
- ios/RCTMGL-v10/RCTMGLSkyLayer.swift
Validate points on MarkerView add, to fix prevent exception `latitude must be between -90 and 90 but was -111.566000`. We should now log error, with rnmapbox error handler instead.
> fix(ios,v10): Do not specify source for SkyLayer, Validate points

- docs/Atmosphere.md
- docs/docs.json
- example/src/examples/V10/TerrainSkyAtmosphere.tsx
- example/src/scenes/Home.js
- javascript/components/Atmosphere.tsx
This changes `Atmosphere.tsx` to a functional component, and adds it to the sky/terrain example.
(I wanted to try the functional component syntax with a simpler Typescript component, before trying to update the much more complex `Camera`.)
https://user-images.githubusercontent.com/2423291/179558302-d2ba95f1-b4c8-4a5e-b503-f47c077b9539.mov
> Convert Atmosphere to FC and integrate into example

- ios/RCTMGL-v10/RCTMGLVectorSource.swift
Add support for attribution, maxZoomLevel, minZoomLevel, and tms props when making a vector source on iOS (v10). Prior to this change, trying to set the min/max zoom level would raise an exception.
> iOS (v10) VectorSource Props

- ios/RCTMGL-v10/RCTMGLRasterSource.swift
- Reference the correct variable names passed in from React to avoid the crash
Fixes an iOS crash when setting the min/max zoom level on a raster source.
> iOS: Fix Raster Source setZoomLevel crash

- ios/RCTMGL-v10/RCTLog.swift
- ios/RCTMGL-v10/RCTSwiftLog.h
- ios/RCTMGL-v10/RCTSwiftLog.m
- rnmapbox-maps.podspec
Fixes iOS build failures for duplicate symbols and file not found errors when use_frameworks! :linkage => :static is enabled and another module also defines RCTSwiftLog.
RCTSwiftLog's header was not public and therefore could not be found. The public_headers callout in the podspec was removed making all of the header files publicly accessible.
This then created a new issue which is also addressed here. react-native-video also has an RCTSwiftLog header and this was causing a duplicate symbol build failure. Therefore, RCTSwiftLog was simply renamed RCTMGLSwiftLog in the implementation to avoid the public header name collision.
> iOS: Resolve RCTSwiftLog duplicate symbols build failure

- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt
- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.kt
- docs/MapView.md
- docs/docs.json
- index.d.ts
- ios/RCTMGL-v10/RCTMGLMapView.swift
- ios/RCTMGL-v10/RCTMGLMapViewManager.m
- javascript/components/MapView.js
Added the ability to control whether or not the compass fades out when pointing north. On Android the default was true, and on iOS the default was false. This brings consistency across platforms by defaulting to true ("breaking" for iOS) and adds the ability to toggle this behavior on/off with a new prop
> Feature: compassFadeWhenNorth

- ios/RCTMGL-v10/RCTMGLCamera.swift
- javascript/components/Camera.tsx
Fixes: crash in Map/Source Layer Visibility for example. 
```jsx
<MapboxGL.Camera 
defaultSettings={{
centerCoordinate: [-74.005974, 40.712776],
zoomLevel: 13
}}
/>
```
Old implementation called `this._createStopConfig` for `defaultSettings`
https://github.com/rnmapbox/maps/blob/9148dd77d126c670308e79bb0bf6667c640d9a6a/javascript/components/Camera.js#L564-L569
The new implementation doesn't call it:
https://github.com/rnmapbox/maps/blob/120c375b65734c707b15b54a94f7bfc7e96fd39b/javascript/components/Camera.tsx#L226-L238
I think there is the same issue with `bounds` as unlike with `buildNativeStop` we're not calling `makeLatLngBounds` for bounds.
> fix(ios,v10): centerCoordinate should be converted to feature when passing to native layer

- javascript/components/Camera.tsx
`{ ...nativeDefaultStop };` was filling in `centerCoorditnate` from default settings, so with `fitBounds` bounds did not apply as center was already set.
Fixes: #2121
> fix(camera): do not use defaultSettings to fill in missing info

- ios/RCTMGL-v10/RCTMGLMapView.swift
Fixes an issue with adding/removing components to/from the map on iOS (v10) by correcting the style is loaded logic
Example: Rendering an array of user added point annotations with lines drawn between them would stop adding new elements to the map by the third point (or no lines drawn depending upon rendering order). Same code on v8 worked and is now working again with the changes proposed
> Fix: iOS v10 add/remove components from map

- package.json
* web version needs, mapbox-gl dependency, but we don't want to require it for native builds, so try it as an optional peer dependency.
> fix(web): add mapbox-gl as an optional peer dependency

- package.json
Use `react-native` in package.json to point to non web version.
Fixes: #2149
> fix: react-native used the web version

- index.d.ts
- javascript/types/index.ts
This PR doesn't have any functionality changes. It properly defines/exports `AnimatedPoint` and `AnimatedShape`, and pulls out the `Animated.Value` variants of the GeoJSON interfaces they rely on.
Note: Is `AnimatedShape` expected to support a shape other than `AnimatedLineString`? If so, I think we should define supported shapes explicitly.
> Update animated `GeoJSON` types and classes

- ios/RCTMGL-v10/RCTMGLOfflineModule.swift
[iOS only] Supports downloading of regions with raster styles (satellite).
Updated TilesetDescriptorOptions to use supported parameters (https://docs.mapbox.com/ios/maps/api/10.7.0/Extensions/TilesetDescriptorOptions.html#/s:So27MBMTilesetDescriptorOptionsC10MapboxMapsE8styleURI9zoomRange10pixelRatio0f4PackC0AbC05StyleG0V_SNys5UInt8VGSfSo08MBMStylel4LoadC0CSgtcfc).
Fixes #2169 
- [x ] I have tested this on a device/simulator for each compatible OS
> [v10; iOS] Support Offline Raster Styles

- docs/CustomHttpHeaders.md
- ios/RCTMGL-v10/CustomHttpHeaders.swift
- ios/RCTMGL-v10/MGLModule.m
- ios/RCTMGL-v10/MGLModule.swift
Implement for v10,ios:
- `Mapbox.addCustomHeader(key,value)`
- `Mapbox.removeCustomHeader(key)`
> feat(ios,v10): implement custom http headers

- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt
- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/styles/layers/RCTLayer.kt
The new v10 on Android throws an error when passing null values to the aboveLayerID and belowLayerID props on. This wasn't a problem on the pervious version.
Fixes #2158
> fix(android): Prevent Error thrown on null values for layer Id's

- package.json
Using the package with expo and running `doctor` throws the following warning:
```bash
$ expo-cli doctor                                                                                                                                                                    
Expected package @expo/config-plugins@^5.0.0
Found invalid:
@expo/config-plugins@4.1.5
```
Therefore I upgraded the dependecy. I guess it's safe as the plugin build output doesn't even change. Our Expo app runs fine with it.
> Upgrade to @expo/config-plugins@5

- javascript/utils/StyleValue.ts
The `@expo/config-plugins` module was recently removed from `devDependencies`, but it was still imported in `StyleValue`, which was causing a build error. This removes the unused import.
> Remove unused expo import

- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt
- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.kt
-  Call ON_DESTROY lifecycle when the map view is removed
- Make sure we remove features from map before the map is destroyed to avoid leak messages from Mapbox (`Mapbox SDK memory leak detected! Style object (accessing removeStyleLayer) should not be stored and used after MapView is destroyed or new style has been loaded.`)
> fix(v10,android): fix mapview removal

- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/styles/terrain/RCTMGLTerrain.kt
- ios/RCTMGL-v10/RCTMGLTerrain.swift
Fixes terrain exaggeration not changing after initial render if prop value is changed
> Change v10 Terrain Exaggeration on the fly

- docs/MapView.md
- docs/docs.json
- javascript/components/MapView.js
BREAKING CHANGE: experimental v10 ios only onCameraChanged, onMapIdle is deprecated, please use onRegionWillChange, onRegionDidChange
Closes: #2216
> refactor!: deprecate onCameraChanged, onMapIdle

- docs/Camera.md
- docs/docs.json
- index.d.ts
- ios/RCTMGL-v10/RCTMGLCamera.swift
- ios/RCTMGL-v10/RCTMGLLogging.swift
- javascript/components/Camera.tsx
- javascript/index.js
- javascript/types/index.ts
BREAKING CHANGE: Camera.UserTrackingModes is now only available as Mapbox.UserTrackingModes, (see #2057)
> fix: Added back Mapbox.UserTrackingModes

- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt
Fix v10, android. Queued features was not set to null, and it caused adding to queued features when the map is already loaded.
> fix(v10,android): clean queued features

- docs/docs.json
- scripts/autogenHelpers/DocJSONBuilder.js
`yarn generate` seems to be flaky, hopefully it's caused by the order of components. This PR attempts to fix that.
> chore: sort docs.json by key alphabetical order

- docs/SymbolLayer.md
- docs/docs.json
- javascript/components/AbstractLayer.tsx
- javascript/components/SymbolLayer.tsx
Fixes #2274
Is it right to also change the `filter` type on `AbstractLayer`?
> AbstractLayer and SymbolLayer filter as Expression

- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/images/RCTMGLImages.kt
- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/utils/DownloadMapImageTask.kt
Fixes: #2278 
Passing: `(1.0/((160.0/bitmap.density))).toFloat()` as scale to `addStyleImage` seems to solve the issue, but it's empirical rather than planned. There's no documentation on scale.
https://docs.mapbox.com/android/maps/api/10.8.1/mapbox-maps-android/com.mapbox.maps/-style-manager-interface/add-style-image.html
Tested on Simulator Pixel 4 API 26;
> fix(v10, android): fix image scale

- plugin/install.md
This is just a tiny change to the expo plugin instructions.
- Re-order expo plugin instructions so people blindly following and using mapbox (me😅) don't end up needing to build the expo dev client twice
> Re-order expo plugin instructions

- example/src/examples/V10/MapHandlers.js
- example/src/examples/V10/MapHandlers.tsx
- javascript/components/MapView.js
This corrects several incorrect deprecation notices, and updates the v10 map callbacks example to TS.
My intention was to fix an issue when rotating the map, where the iOS `.cameraChanged` callback alternately fires with the camera state at the moment of starting the gesture, and the actual state. For instance, here is a typical log from `RCTMGLMapView.swift` of the `bearing` value during a pinch-to-rotate gesture:
```
6.421815145278117
7.825208541100609
6.421815145278117
8.806056099882483
6.421815145278117
8.806056099882483
6.421815145278117
9.694378738066519
6.421815145278117
10.537850335944086
6.421815145278117
11.492506191828681
6.421815145278117
12.418379956915544
6.421815145278117
13.140272292955729
6.421815145278117
14.255771518591871
```
This is apparently a known bug in the iOS …
> Update map callbacks example

- javascript/components/SymbolLayer.tsx
Fixes #2312 
Unfortunately, the change I submitted in https://github.com/rnmapbox/maps/pull/2313 actually failed to handle a typing corner case (child can be null), so #2312 was not fully fixed.  However, I think the way this PR handles the typing of children makes more sense anyway.  Since `this.baseProps.children` has the typing described in the Props type (unfortunately `this.props.children` doesn't when @types/react is installed), referencing `this.baseProps.children` solves the problem automatically, and shouldn't change any behavior.
> (v10) Revert SymbolLayer children type checking and use baseProps instead

- ios/RCTMGL-v10/MGLModule.m
Fixes bug caused by https://github.com/rnmapbox/maps/pull/2343, with the `setAccessToken` interface signature no longer matching the implementation.
> Fix v10 interface signature

- javascript/index.js
Fixed UserTrackingModes reference is broken and `example/src/examples/Camera/SetUserTrackingModes.js` cannot be displayed
ref: https://github.com/rnmapbox/maps/pull/2242
> fix: MapboxGL.UserTrackingModes variable is undefined

- package.json
Fixes #2361
`app.plugin.js` is not published inside npm package.
> fix: publish app.plugin.js (#2361)

- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.kt
- ios/RCTMGL-v10/RCTMGLMapViewManager.swift
- Fixed: query method without filter params returns empty feature results. `map.queryRenderedFeaturesInRect(rect)`
N/A
> fix(v10): query method without filter params returns empty feature results

- example/src/examples/FillRasterLayer/QueryWithRect.js
- ios/RCTMGL-v10/RCTMGLMapViewManager.swift
Fixes 
- Fixed inconsistent order of rect bound values in iOS
- Updated example with correct order of Rect bounds (Fill/RasterLayer --> Query Features Bounding Box)
| Before Fix  | After Fix |
| ------------- | ------------- |
|  <video src="https://user-images.githubusercontent.com/28037630/199347813-7272bf15-47de-4232-abac-4b0cb2a61ba2.mov">  | <video src="https://user-images.githubusercontent.com/28037630/199348615-661d321a-deb5-4be8-9969-954e05188b4f.mov">  |
| <video src="https://user-images.githubusercontent.com/28037630/199350304-26574e19-4b72-42ed-a773-7354560c1abc.mov">  | <video src="https://user-images.githubusercontent.com/28037630/199350623-3f88e125-ff31-44fb-8c56-dbfbcbb41f3f.mov">  |
> fix(v10,ios): fixed inconsistent order of rect values in iOS

- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.kt
- ios/RCTMGL-v10/RCTMGLStyleValue.swift
- Color with alpha is always set to 1 in iOS
Note: The `fillColor` of the **selected** `FillLayer` is set as `"hsla(267, 72%, 63%, 0.2)"`
| Before fix  | After fix |
| ------------- | ------------- |
| <video src="https://user-images.githubusercontent.com/28037630/199795379-8d3f53e7-c230-45a8-a8a7-af0975f7a709.mov">  | <video src="https://user-images.githubusercontent.com/28037630/199795561-93892adb-03d9-48df-8142-4f195efbdfc3.mov">  |
> fix(v10,ios): color with alpha is always set to 1 in iOS

- example/package.json
At the end of last week, React Native [broke](https://github.com/facebook/react-native/issues/35210). This PR resolves the build error on Android.
> fix(android) Fix React Native build errors

- android/rctmgl/build.gradle
- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/annotation/RCTMGLMarkerView.kt
- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt
With 10.9 or later views are no longer directly added to the mapView but a annotationViewLayout subview. And our workaround one endViewTransition needs to be called on `annotationViewLayout` for the 10.9+ versions
> fix(v10,android): fix crash on view annotation removal

- javascript/components/Atmosphere.tsx
- javascript/components/MarkerView.tsx
- javascript/components/PointAnnotation.tsx
- javascript/components/ShapeSource.tsx
Fixes #2391
I only changed the typings from the variables over to the generic of the function. I still don't know why this behaves different after an Expo Upgrade because I couldn't find changes to the typings in `@types/react-native` but it fixes the problem anyway.
> fix: requireNativeComponent types

- ios/RCTMGL-v10/MGLModule.swift
Using the following snippet rendered the default style on iOS, not `satellite-streets-v11` as expected.
```ts
<MapboxGL.MapView styleURL={MapboxGL.StyleURL.SatelliteStreet} >
```
Logging the `MapboxGL.StyleURL` enum to the console:
```json
{
"Dark": "mapbox://styles/mapbox/dark-v10",
"Light": "mapbox://styles/mapbox/light-v10",
"Outdoors": "mapbox://styles/mapbox/outdoors-v11",
"Satellite": "mapbox://styles/mapbox/satellite-v9",
"SatelliteStreets": "mapbox://styles/mapbox/satellite-streets-v11",
"Street": "mapbox://styles/mapbox/streets-v11"
}
```
[ios/RCTMGL-v10/MGLModule.swift](https://github.com/rnmapbox/maps/blob/894f9a212b060d265e6cbe77748c4417d2d1812d/ios/RCTMGL-v10/MGLModule.swift#L23) exports `SatelliteStreets` - not `SatelliteStreet` like …
> fix(v10,ios) Populate StyleURL enum with correct key

- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt
- example/android/app/src/main/java/com/rnmapboxglexample/MainActivity.java
- example/package.json
- example/src/scenes/GroupAndItem.tsx
- fix(v10, android): force relayout of chllderns so ornaments can be updated (uses an ugly hack  - see`workaroundToRelayoutChildOfMapView`, but seems to work)
- feat(example): save last example, and show as first item
- feat(example): added `//react-native-screens override` so layout inspector can be used.
Closes: #2421 
Fixes: #2403
> fix(v10, android): fix android ornaments

- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/styles/RCTMGLStyleFactory.java
- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/styles/layers/RCTLayer.kt
- example/ios/Podfile.lock
- ios/RCTMGL-v10/RCTMGLBackgroundLayer.swift
- ios/RCTMGL-v10/RCTMGLCircleLayer.swift
- ios/RCTMGL-v10/RCTMGLFillExtrustionLayer.swift
- ios/RCTMGL-v10/RCTMGLFillLayer.swift
- ios/RCTMGL-v10/RCTMGLHeatmapLayer.swift
- ios/RCTMGL-v10/RCTMGLLineLayer.swift
- ios/RCTMGL-v10/RCTMGLRasterLayer.swift
- ios/RCTMGL-v10/RCTMGLSkyLayer.swift
- ios/RCTMGL-v10/RCTMGLSymbolLayer.swift
- scripts/templates/RCTMGLStyleFactoryv10.java.ejs
Fixes: #2432 
The cause of the issue is that UserLocation images in StyleLayer, and apply images in async manner first we get the image then we add to the map style, and finally we apple the resolved image to StyleLayer. Its possible that StyleLayer was disposed in the meantime. We now log those errors but they are no longer crashes
> fix(v10): change in style layer can cause crash in image properties

- ios/RCTMGL-v10/RCTMGLLocationModule.swift
- ios/RCTMGL/RCTMGLLocation.m
Fixes https://github.com/rnmapbox/maps/issues/1693
Before you receive in position timestamps for
* iOS: `1669105653.049532` (sec) 🔴 
* Android: `1669105653049.532` (ms) 🟢 
With this PR you receive in position timestamps for
* iOS: `1669105653049.532` (ms) 🟢 
* Android: `1669105653049.532` (ms) 🟢 
Timestamp is `1669105653049.532`.
Using this in the JS console, results in:
```Javascript
new Date(1669105653049.532)
`Date Tue Nov 22 2022 09:27:33 GMT+0100 (Central European Standard Time)` 
```
BREAKING CHANGE: iOS returns timestamp field in location as milliseconds instead of seconds
> fix!(ios): timestamp returns now milliseconds instead of seconds

- javascript/components/Camera.tsx
This only removes `const enum` since it is not compatible with `isolatedModules`. There is not a real need for having const enum as commented here - https://github.com/rnmapbox/maps/issues/2423#issuecomment-1323204764
Related to #2423
**Please note:**
I didn't test it. I only updated the file on GitHub and created this PR. But I don't think there is a need for any deep testing because of this change.
> fix: remove const enum that is in conflict with isolatedModules

- package.json
- plugin/build/withMapbox.d.ts
- plugin/build/withMapbox.js
- plugin/src/withMapbox.ts
See #2389 – this only fixes the dependencies and public APIs. Further changes will be necessary when the private APIs are exposed.
> feat: expo config-plugin update imports and dependencies

- ios/RCTMGL/RCTMGLLocation.m
Same as https://github.com/rnmapbox/maps/pull/2440
But just for `v8` branch.
Description of [2440](https://github.com/rnmapbox/maps/pull/2440)
> Fixes #1693
> ### Example
> #### Before
> 
> Before you receive in position timestamps for
> 
>     * iOS: `1669105653.049532` (sec) 🔴
> 
>     * Android: `1669105653049.532` (ms) 🟢
> 
> 
> #### After
> 
> With this PR you receive in position timestamps for
> 
>     * iOS: `1669105653049.532` (ms) 🟢
> 
>     * Android: `1669105653049.532` (ms) 🟢
> 
> 
BREAKING CHANGE: iOS returns timestamp field in location as milliseconds instead of seconds
> fix!(ios): timestamp returns now milliseconds instead of seconds (v8)

- ios/RCTMGL-v10/RCTMGLLayer.swift
- ios/RCTMGL-v10/RCTMGLLogging.swift
Fixes: #2477
2 Improvements:
- better log message
- don't set filter to `nil` on mapbox layer if it was `nil` in RCTMGLLayer. `nil` on RCTMGLLayer only means that the filter was not touched yet. Use something like `['all', 'true']` expression to change an existing filter to nil/all filter.
> fix: don't set filter, unless changed, improve error messages

- android/rctmgl/build.gradle
- example/ios/Podfile.lock
- rnmapbox-maps.podspec
Chore: upgrade Mapbox libraries to 10.10.0
https://github.com/mapbox/mapbox-maps-ios/blob/main/CHANGELOG.md
https://github.com/mapbox/mapbox-maps-android/blob/main/CHANGELOG.md
> Upgrade mapbox maps libraries to 10.10

- ios/RCTMGL-v10/RCTMGLMapView.swift
> fix(v10,ios): Reinsert style dependent components on style change

- __tests__/components/UserLocation.test.js
- ios/RCTMGL-v10/RCTMGLLocationModule.swift
- javascript/components/UserLocation.js
- javascript/modules/location/locationManager.js
We're now setting distanceFilter correctly on iOS but I still receive updates
```jsx
import { Camera, MapView, PointAnnotation, UserLocation } from '@rnmapbox/maps';
import { Feature, Point } from 'geojson';
import React, { useState } from 'react';
import { View, Text } from 'react-native';
const BugReportExample = () => {
const [count, setCount] = useState(0);
return (
<View style={{ flex: 1 }}>
<View>
<Text>Count: {count}</Text>
</View>
<UserLocation
visible
minDisplacement={1000}
onUpdate={(location) => {
setCount(count+1);
console.log('#=>', location);
}}
/>
<Camera
zoomLevel={16}
followUserMode={'normal'}
followZoomLevel={16}
followUserLocation
/>
</MapView>
</View>
);
};
export default BugReportExample;
```
> fix(iOS,v10): fix minDisplacement /distanceFilter on UserLocation

- ios/RCTMGL-v10/RCTMGLMapViewManager.swift
- javascript/components/MapView.js
This merge request only applies to iOS-specific codebase. Makes sure that the features list returned by the queryRenderedFeatureAtPoint method is not empty, if the user doesn't provide any value into the layerIDs parameter.
The withMapView method makes no more any force unwrap to prevent the application from crashing by checking the view existence and type casting performed safely
Fixes no known issue
This MR doesn't require any screenshot or video, because it simply makes sure that the data returned by the native method implementation is not an empty list, also when the expected result is not empty.
> fix queryRenderedFeaturesAtPoint iOS

- ios/RCTMGL-v10/RCTMGLOfflineModule.swift
Fixes: #2516 
It sounds like `loadTileRegion` callbacks not always called on main thread, causing multiple thread to access Dictionary at the same time. And although we only read from the `tileRegionPacks` it seems that it still causes race condition. 
https://docs.mapbox.com/ios/maps/api/10.10.1/Extensions/TileStore.html#/s:So12MBXTileStoreC10MapboxMapsE14loadTileRegion5forId0E7Options8progress10completionAC10Cancelable_pSS_So0ag4LoadJ0CySo0agN8ProgressCcSgys6ResultOySo0aG0Cs5Error_pGctF
> The user-provided callbacks will be executed on a TileStore-controlled worker thread; it is the responsibility of the user to dispatch to a user-controlled thread.
> fix(ios,v10): fix offline download, thread issue

- __tests__/modules/location/locationManager.test.js
- android/rctmgl/.settings/org.eclipse.buildship.core.prefs
- android/rctmgl/src/main/java-mapboxgl/common/com/mapbox/rctmgl/modules/RCTMGLLocationModule.java
- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/modules/RCTMGLLocationModule.kt
- docs/UserLocation.md
- docs/docs.json
- example/src/utils/index.js
- index.d.ts
- ios/RCTMGL-v10/RCTMGLLocationModule.m
- ios/RCTMGL-v10/RCTMGLLocationModule.swift
- javascript/components/UserLocation.js
- javascript/modules/location/locationManager.js
Added `requestsAlwaysUse` prop to the UserLocation component that allows choosing if we want to listen for the user location in the background or not.
It allows us to not ask for background location permission when we don't need it and still use the UserLocation component.
None for now.
> Add `requestsAlwaysUse` prop to the UserLocation

- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/camera/RCTMGLCamera.kt
Fixes: #2563
It seems that onAnimatedEnd might be called after map was disposed, so use optional chaining.
> fix(v10, android): allow nil mapView on onEnimationEnd

- javascript/components/Annotation.tsx
@mfazekas https://github.com/rnmapbox/maps/pull/2673#issuecomment-1462089857
Does this fix it? To be honest, the `import XY =` syntax is weird, might only be supported by a newer TS version? My IDE created it 😅.
> fix(ts): type import

- javascript/utils/geoUtils.ts
- package.json
The unused function `getOrCalculateVisibleRegion` and it's dependency on `@mapbox/geo-viewport` gives me missing types errors when using in a project:
```
node_modules/@rnmapbox/maps/javascript/utils/geoUtils.ts:17:25 - error TS7016: Could not find a declaration file for module '@mapbox/geo-viewport'. '/Users/finger/Development/rrph-app/node_modules/@mapbox/geo-viewport/index.js' implicitly has an 'any' type.
```
There fore I would like to get rid of the function and their dependencies. Otherwiese we have to move the `@types/mapbox__geo-viewport` dependency to `dependencies`, so they will be installed when used in a project.
> chore: remove unused getOrCalculateVisibleRegion

- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/events/PointAnnotationDragEvent.java
- docs/PointAnnotation.md
- docs/docs.json
- example/src/examples/Annotations/ShowPointAnnotation.tsx
- ios/RCTMGL-v10/RCTMGLMapView.swift
- javascript/components/PointAnnotation.tsx
`PointAnnotation` events are currently falsy typed, see also "Show Point Annotation" example is currently logging `undefined` on drag events. `id` was not yet implemented on iOS. I moved it on booth platforms to `feature.id` instead of `feature.properties.id` as that's part of the GeoJson spec.
> fix(ts): PointAnnotation FeaturePayload type

- plugin/build/withMapbox.d.ts
- plugin/build/withMapbox.js
- plugin/install.md
- plugin/src/withMapbox.ts
Fixes: #2618 (iOS only, as RNMapboxMapsVersion not yet implemented on Android)
> feat(expo,ios): add RNMapboxMapsVersion to Expo Plugin on iOS

- docs/UserLocation.md
- docs/docs.json
- javascript/components/UserLocation.tsx
I updated the type of the `children` props from UserLocation to `ReactElement | ReactElement[]`.
If you need to represent the UserLocation with multiple layers, you must pass them as an array of elements, similar to how the `normalIcon` function does:
```typescript
const normalIcon = (
showsUserHeadingIndicator?: boolean,
heading?: number | null,
): ReactElement[] => [
<CircleLayer
key="mapboxUserLocationPulseCircle"
id="mapboxUserLocationPulseCircle"
style={layerStyles.normal.pulse}
/>,
<CircleLayer
key="mapboxUserLocationWhiteCircle"
id="mapboxUserLocationWhiteCircle"
style={layerStyles.normal.background}
/>,
<CircleLayer
key="mapboxUserLocationBlueCircle"
id="mapboxUserLocationBlueCircle"
aboveLayerID="mapboxUserLocationWhiteCircle"
style={layerStyles.normal.foreground}
/>, …
```
> fix(v10): type of `children` props from UserLocation.tsx

- plugin/build/withMapbox.js
- plugin/src/withMapbox.ts
Fixes https://github.com/rnmapbox/maps/pull/2693#issuecomment-1469614936
I've successfully built without supplying RNMapboxMapsVersion.
> fix(expo,ios): add RNMapboxMapsVersion only when defined

- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/camera/CameraUpdateQueue.kt
- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/camera/RCTMGLCamera.kt
- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt
- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.kt
Fixes: #2591
The issue was that onDestroy we've removed all children, but RN needs the childrens to be reported correctly for correct cleanup, otherwise children such as Camera would be still kept in RN-s tagToView map, that prevented GC from freeing them. See:
https://github.com/facebook/react-native/blob/0a3c55562b5ba43b00c21ca4d7b2cba0c8eb6206/ReactAndroid/src/main/java/com/facebook/react/uimanager/ViewGroupManager.java#L74-L98
Example used:
```jsx
import { MapView, ShapeSource, LineLayer, Camera } from '@rnmapbox/maps';
const aLine = {
type: 'LineString',
coordinates: [
[-74.00597, 40.71427],
[-74.00697, 40.71527],
],
};
class BugReportExample extends React.Component {
render() {
return (
<Camera centerCoordinate={[-74.00597, …
```
> fix(android,v10): fix leak

- .github/workflows/ios-actions.yml
Add cache to yarn and pods to gh actions. Will require to check in yarn.lock and pods.lock file.
> chore(ghactions): add cache

- src/components/Terrain.tsx
Removes a `console.log` that I think was left in the code by mistake. It clutters the logs of any project using the `Terrain` component.
I did none of the things above because the PR is so simple.
> fix: remove console.log from Terrain.tsx

- android/rctmgl/src/main/AndroidManifest.xml
- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/AbstractEventEmitter.kt
Fixes a couple lint issues that were causing downstream build failures:
- Android builds could fail because only the `ACCESS_FINE_LOCATION` permission was granted in `AndroidManifest.xml`. I added the `ACCESS_COARSE_LOCATION` permission as well, which is required as described in the documentation here: https://developer.android.com/training/location/permissions#foreground
- Android builds could fail due to an erroneous use of the `@Nonnull` tag in Kotlin code
See the following failing builds, & one passing one using the code from this PR:
- https://github.com/techmatters/terraso-mobile-client/actions/runs/4681503761/jobs/8294181904
- https://github.com/techmatters/terraso-mobile-client/actions/runs/4681627748/jobs/8294453587
- https://github.com/techmatters/terraso-mobile-client/actions/ru …
> fix: two lint issues causing downstream build failures

- ios/RCTMGL-v10/RCTMGLOfflineModule.swift
This pull request addresses an issue with the getPacks method, where the nativeOfflinePacks array on the React Native side contained an empty object, even though the corresponding self.tileRegionPacks[region.id] on the iOS side had a valid value.
The issue was traced back to the convertRegionToJSON function, which incorrectly returned an empty dictionary [:] at the end, instead of the expected result object.
> fix(ios) Fix getPacks method returning an a array of empty object 

- ios/RCTMGL-v10/RCTMGLShapeSource.swift
This is a "funny" one. I created an issue for the exact same error ~4 years ago on the previous Mapbox GL impletementation. (Ref: https://github.com/rnmapbox/maps/issues/541)
So here we go again. When updating an url dynamically to a `ShapeSource`, the layer is not refreshed and the data is stale.
I must be the only one using the url prop 😅 
Without the patch (You can notice for the first loading it works but not for the updates afterward):
https://user-images.githubusercontent.com/937328/232230718-6afa3acf-38ee-4488-bc60-1e6c60ad8b76.mov
After the patch:
https://user-images.githubusercontent.com/937328/232230731-5e0fcc0f-90e6-4ff3-b0c0-8e79667dcf16.mov
> fix: update GeoJSONSource when updating url

- example/src/examples/BugReportExample.js
- example/src/examples/BugReportExampleTS.tsx
- Images were not showing on the bug report examples (JS/TS)
> fix: add image refs

- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt
- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.kt
- docs/MapView.md
- docs/OfflineManager.md
- docs/docs.json
- ios/RCTMGL-v10/RCTMGLMapViewManager.m
- ios/RCTMGL-v10/RCTMGLMapViewManager.swift
- ios/RCTMGL-v10/RCTMGLOfflineModule.swift
- src/components/MapView.tsx
- src/modules/offline/offlineManager.ts
- src/utils/index.ts
Fixes: #2797 
Unfortunately it's seems that CacheManger was removed from early iOS sdk. 
There is a new v10 only method `clearData` see https://docs.mapbox.com/ios/maps/api/10.12.2/Classes/MapboxMap.html#/s:10MapboxMaps0A3MapC9clearData10completionyys5Error_pSgc_tF
https://github.com/mapbox/mapbox-maps-ios/commit/5e79f92d061172998b583e00967a71d3c4c93d1d
https://docs.mapbox.com/ios/maps/api/10.0.0-beta.20/Extensions/CacheManager.html#/s:So15MBMCacheManagerC10MapboxMapsE17clearAmbientCacheyyys6ResultOyyts5Error_pGcF
> feat: add MapView.clearData

- README.md
- android/rctmgl/build.gradle
Change `minSdkVersion` for android.
Since Mapbox v10, we need to use the minimum version sdk 21 as describe here : https://docs.mapbox.com/android/maps/guides/migrate-to-v10/#requirements.
Since React Native 0.64, the min sdk version is 21 : https://reactnative.dev/blog/2021/03/12/version-0.64. It's already in the doc that we must use react native 0.64+.
Please let me know if there is any reasons why the following line : "On Android we support from version 6 (API 23) upwards" was written
> fix(android): change minSdkVersion to 21

- ios/install.md
setting is no longer optional and will throw the following error if left out
```
[!] Invalid `Podfile` file: 
[!] Invalid `rnmapbox-maps.podspec` file: Setting $RNMapboxMapsImpl is now required - https://github.com/rnmapbox/maps/wiki/Deprecated-RNMapboxImpl-Unset#ios.
```
also add a note for anyone encountering 
https://github.com/rnmapbox/maps/discussions/2830#discussioncomment-5762648
> Update install.md for more accurate ios 

- example/ios/Podfile
These [changes to fix running the example iOS on an M1 Mac](https://github.com/rnmapbox/maps/commit/7338e793#diff-4fb44f272217447e6b4b3580916d09d23b9055f6a217ad8b26269cfa6031203a) were reverted during the [latest example upgrade](https://github.com/rnmapbox/maps/commit/27d28066d2f506ce1977ce7ef5e435607bf611a5#diff-4fb44f272217447e6b4b3580916d09d23b9055f6a217ad8b26269cfa6031203aL89-L93). Without these lines `yarn ios` fails with: 
```
❌  fatal error: module map file '<some-path>/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
```
Therefore I added those lines again to make it work. To reproduce on a M1 Mac run the following in the `example` dir:
```
yarn purge:ios && yarn pod:install && yarn ios
```
> fix: example Podfile for arm64

- rnmapbox-maps.podspec
Fixes warning (see below) that causes builds to fail, when using a build system sensitive to `pod install` warnings (e.g. Nx).
```
[**]:95: warning: already initialized constant Pod::MapboxImplVersion
[**]:95: warning: previous definition of MapboxImplVersion was here
```
> Fix "already initialized constant" MapboxImplVersion

- android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt
The previous implementation has problems with locale strings with variants. e.g:
Settings locale to zh-Hant-HK will give errors like:
`[maps-android\LocalizationPluginImpl]: Locale: zh-hant-hk is not supported.`
Fixed by the following code.
> fix locale

- .github/workflows/publish.yml
Fixes: #2971 
Add ```--tag next``` to npm publish in case it's a prerelease version
> chore: publish preelease version with tag next to npm

- ios/RCTMGL-v10/RCTMGLLocationModule.swift
Fixes: #2919 
The issue is on initial update. These are the operations, normally
1.) subscribe to location updates from CoreLocation
2.) Mapbox maps viewport subscribes to locationProvider
3.) first update is received
Now when we use our own UserLocation component the order is (1) (3) (2), as we listen to updates a bit earlier,  so the first update might be received before Mapbox maps viewport subscribes to updates. Therefore the first update might be lost.
To fix this I've modified the code so when the delegate is attached to LocationProvider, and we have a location, we send this location to the delegate. 
To reproduce on iOS simulator set location to a static location like (Features/Location/Apple). Then run the following component:
```tsx
import React, { useState, useRef } from …
```
> fix(ios,v10): location manager race condition with initial location update

- example/README.md
While installing the example project, it was required to go in the iOS folder and run `pod install` to install the dependencies.
This PR adds this step to the README.
- [-] I have tested this on a device/simulator for each compatible OS
- [-] I added/updated a sample - if a new feature was implemented (`/example`)
`[-]` = not applicable
> Add pod install to example/README.md

- android/src/main/java-v10/com/mapbox/rctmgl/components/styles/layers/RCTLayer.kt
- example/ios/Podfile.lock
Fixes the following component not rendering on android:
```jsx
import {
MapView,
ShapeSource,
LineLayer,
Camera,
VectorSource,
FillLayer,
//The part which is commeted out works, triggers the on press. The other one doesnt though.
class BugReportExample extends React.Component {
render() {
return (
<Camera
centerCoordinate={[11.44274825303006, 49.4026975280301]}
zoomLevel={14}
/>
<ShapeSource
id="polygonSource"
onPress={() => {
console.log('pressed');
}}
shape={{
properties: {},
geometry: {
coordinates: [
[
[4.029480413140874, 49.4026975280301],
[4.029480413140874, 46.99045121353802],
[11.44274825303006, 46.99045121353802],
[11.44274825303006, 49.4026975280301],
[4.029480413140874, …
```
> fix: fix layer no appearing issue on android

- android/src/main/java/com/rnmapbox/rnmbx/components/styles/RNMBXStyleValue.kt
Fixes transition issue, on android.
```jsx
import {
Images,
MapView,
ShapeSource,
SymbolLayer,
CircleLayer,
Camera,
circleLayer: {
circleRadiusTransition: { duration: 5000, delay: 0 },
circleColor: '#ff0000',
},
};
const features = {
features: [
{
id: 'a-feature',
properties: {
icon: 'example',
text: 'example-icon-and-label',
},
geometry: {
type: 'Point',
coordinates: [-74.00597, 40.71427],
},
},
{
id: 'b-feature',
properties: {
text: 'just-label',
},
geometry: {
type: 'Point',
coordinates: [-74.001097, 40.71527],
},
},
{
id: 'c-feature',
properties: {
icon: 'example',
},
geometry: { …
```
> fix(android): fix transition duration is always 0 issue

- android/src/main/java/com/rnmapbox/rnmbx/RNMBXPackage.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/mapview/NativeMapViewModule.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/mapview/RNMBXAndroidTextureMapViewManager.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/mapview/RNMBXMapView.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/mapview/RNMBXMapViewManager.kt
- android/src/main/java/com/rnmapbox/rnmbx/utils/ViewTagResolver.kt
Fixes the folllowing warning on android:
Can be reproduce with this example:
```jsx
import { FlatList } from "react-native";
import { MapView, Camera, ShapeSource, LineLayer } from '@rnmapbox/maps';
const SHAPE = {
"type": "FeatureCollection",
"features": [
{
"type": "Feature",
"geometry": {
"type": "Polygon",
"coordinates": [
[
[
-105.02738295071447,
-74.41429582091831
],
[
-108.67784207799926,
-82.41571395310365
],
[
-117.5641615804278,
-71.45151781686236
],
[
-105.02738295071447,
-74.41429582091831
]
]
]
},
}
],
"properties": {
"bbox": [-117.5641615804278, -82.41571395310365, -105.02738295071447, -71.45151781686236],
}
};
const SHAPES = Array.from({ length: 10 }).map(() => SHAPE);
const Example = () => <FlatList data={SHAPES} renderItem={renderItem} />;
const …
```
> fix(android): sometimes view tag is not resolved immediately

- android/src/main/java/com/rnmapbox/rnmbx/location/LocationManager.kt
- android/src/main/mapbox-v11-compat/v10/com/mapbox/rnmbx/v11compat/Location.kt
- android/src/main/mapbox-v11-compat/v11/com/mapbox/rnmbx/v11compat/Location.kt
- example/android/build.gradle
> fix(android): fix negative minDisplacement, fix location on v10 and v11

- plugin/install.md
I noticed when integrating via Expo that the docs don't mention the scopes required for the `RNMapboxMapsDownloadToken` secret token. The iOS integration guide does, so I've adapted the copy from those docs to the main install docs here.
Edit: `yarn generate` is failing for me locally. Might have time to debug later, but will pry leave it for the maintainers if that's cool ✌️ 
Not applicable
> Add RNMapboxMapsDownloadToken required scopes to docs

- android/src/main/java/com/rnmapbox/rnmbx/components/images/RNMBXImages.kt
- android/src/main/java/com/rnmapbox/rnmbx/utils/BitmapUtils.kt
- android/src/main/java/com/rnmapbox/rnmbx/utils/DownloadMapImageTask.kt
Fixes: #3009 
So in production our assets looks like this:
```js
{icon1: {"scale":2,"height":64,"uri":"src_assets_scaletesticon","width":64,"__packager_asset":true}}
```
The issue was solved by using fresco to load images from resource in case of release mode. Previously we've loaded manually and we were using wrong combination of scale, [inDensity](https://developer.android.com/reference/android/graphics/BitmapFactory.Options?hl=en#inDensity), [inScreenDensity](https://developer.android.com/reference/android/graphics/BitmapFactory.Options#inScreenDensity), [inTargetDensity](https://developer.android.com/reference/android/graphics/BitmapFactory.Options#inTargetDensity). (tested with `yarn android --mode release `)
> fix: fix image scaling on android in production

- android/src/main/java/com/rnmapbox/rnmbx/components/camera/RNMBXCamera.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/location/LocationComponentManager.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/location/UserTrackingMode.kt
> fix(android): on user tracking mode change

- ios/install.md
- plugin/build/withMapbox.d.ts
- plugin/build/withMapbox.js
- plugin/install.md
- plugin/src/__tests__/__snapshots__/withMapbox-test.ts.snap
- plugin/src/__tests__/withMapbox-test.ts
- plugin/src/withMapbox.ts
Closes: #3120 
See #3120, thanks @balloman
> feat: Add expo plugin property for v11 on iOS 

- android/src/main/java/com/rnmapbox/rnmbx/components/styles/sources/RNMBXImageSourceManager.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/styles/sources/RNMBXRasterDemSourceManager.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/styles/sources/RNMBXRasterSourceManager.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/styles/sources/RNMBXShapeSource.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/styles/sources/RNMBXShapeSourceManager.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/styles/sources/RNMBXSource.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/styles/sources/RNMBXTileSourceManager.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/styles/sources/RNMBXVectorSourceManager.kt
- android/src/main/old-arch/com/facebook/react/viewmanagers/RNMBXShapeSourceManagerDelegate.java
- android/src/main/old-arch/com/facebook/react/viewmanagers/RNMBXShapeSourceManagerInterface.java
- fabricexample/ios/Podfile.lock
- src/specs/RNMBXShapeSourceNativeComponent.ts
PR fixing not implemented interfaces in `Source` components, adding not implemented setters for `existing` and removing unused `images` and `nativeImages` props
> fix: implement interfaces in Android sources

- example/src/examples/SymbolCircleLayer/CustomIconNativeAsset.tsx
- example/src/examples/SymbolCircleLayer/index.js
- ios/RNMBX/RNMBXImages.swift
Fixes an issue that the Image component would not show nativeImageAssets on iOS.
The bug was introduced with this commit: f5ae7849d63799271878d8501f1ceecfbf941f05 after resolving some merge issues.
> Fix missing images

- android/src/main/java/com/rnmapbox/rnmbx/utils/BitmapUtils.kt
This fixes a build failure - `bitmap.compress()` cannot accept an optional as the third argument.
> Null-check OutputStream

- android/src/main/AndroidManifest.xml
> Fix android build issue

- example/android/build.gradle
- example/android/gradle.properties
- example/ios/Podfile
Fixes: 
https://github.com/rnmapbox/maps/actions/runs/6941926774/job/18883872023
See: 
```
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> Failed to transform hermes-android-0.73.0-rc.4-debug.aar (com.facebook.react:hermes-android:0.73.0-rc.4) to match attributes {artifactType=android-aar-metadata, com.android.build.api.attributes.BuildTypeAttr=debug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
> Execution failed for JetifyTransform: /home/runner/.gradle/caches/modules-2/files-2.1/com.facebook.react/hermes-android/0.73.0-rc.4/c39b36896cb2df598cfa60a8cc0855e0a0b7e6de/her …
```
> chore: Android bump heap

- android/src/main/old-arch/com/rnmapbox/rnmbx/NativeMapViewModuleSpec.java
- android/src/main/old-arch/com/rnmapbox/rnmbx/NativeRNMBXImageModuleSpec.java
- android/src/main/old-arch/com/rnmapbox/rnmbx/NativeRNMBXMovePointShapeAnimatorModuleSpec.java
- android/src/main/old-arch/com/rnmapbox/rnmbx/NativeRNMBXPointAnnotationModuleSpec.java
- android/src/main/old-arch/com/rnmapbox/rnmbx/NativeRNMBXShapeSourceModuleSpec.java
- android/src/main/old-arch/com/rnmapbox/rnmbx/NativeRNMBXViewportModuleSpec.java
- example/.gitignore
- example/android/gradle.properties
- scripts/codegen-old-arch.js
> fix(rn-072): fix generated code to be compatible with <rn.073

- .github/workflows/update-docs.yml
- scripts/example-docs.ts
When main is updated we need to update documentation on maps-docs
> chore: update maps-docs repo when main is updated

- android/src/main/java/com/rnmapbox/rnmbx/components/location/RNMBXNativeUserLocation.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/location/RNMBXNativeUserLocationManager.kt
- android/src/main/old-arch/com/facebook/react/viewmanagers/RNMBXNativeUserLocationManagerDelegate.java
- android/src/main/old-arch/com/facebook/react/viewmanagers/RNMBXNativeUserLocationManagerInterface.java
- docs/NativeUserLocation.md
- docs/docs.json
- example/src/examples/UserLocation/CustomNativeUserLocation.tsx
- ios/RNMBX/RNMBXFabricPropConvert.h
- ios/RNMBX/RNMBXFabricPropConvert.mm
- ios/RNMBX/RNMBXNativeUserLocation.swift
- ios/RNMBX/RNMBXNativeUserLocationComponentView.mm
- ios/RNMBX/RNMBXNativeUserLocationViewManager.m
- src/components/NativeUserLocation.tsx
- src/specs/RNMBXNativeUserLocationNativeComponent.ts
Closes: #3161
Add  pushing options to RN interface for NativeUserLocation:
```jsx
<NativeUserLocation
visible={true}
pulsing={{
isEnabled: true,
color: 'teal',
radius: 50.0,
}}
/>
```
> feat(nativeUserLocation): implement customizable pusling

- android/src/main/java/com/rnmapbox/rnmbx/components/mapview/NativeMapViewModule.kt
Fixes: #3177
Component to reproduce:
```tsx
import {
MapView,
ShapeSource,
LineLayer,
Camera,
UserLocation,
const getBBox = (
screenPointX: number,
screenPointY: number,
tapMargin: number,
) => [
screenPointY + tapMargin,
screenPointX + tapMargin,
screenPointY - tapMargin,
screenPointX - tapMargin,
];
export default function BugReportExample() {
const mapRef = React.useRef<MapView>(null);
return (
<>
<MapView
style={{ flex: 1 }}
ref={mapRef}
onPress={async (event: any) => {
console.log('Map.onPress', event);
const { screenPointX, screenPointY } = event.properties as any;
const bbox = getBBox(screenPointX, screenPointY, 1);
const filter = ['==', 'type', 'Point'];
const featureCollection =
await mapRef.current?.queryRenderedFeaturesInRect( …
```
> fix(android): withLayerIDs: is optional

- android/src/main/java/com/rnmapbox/rnmbx/components/annotation/RNMBXPointAnnotation.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/mapview/RNMBXMapView.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/mapview/RNMBXMapViewManager.kt
- android/src/main/old-arch/com/facebook/react/viewmanagers/RNMBXMapViewManagerDelegate.java
- android/src/main/old-arch/com/facebook/react/viewmanagers/RNMBXMapViewManagerInterface.java
- docs/MapView.md
- docs/PointAnnotation.md
- docs/docs.json
- docs/examples.json
- example/src/examples/Annotations/ShowPointAnnotation.tsx
- ios/RNMBX/RNMBXMapView.swift
- ios/RNMBX/RNMBXMapViewComponentView.mm
- ios/RNMBX/RNMBXMapViewManager.m
- ios/RNMBX/RNMBXMarkerViewContentComponentView.mm
- src/components/MapView.tsx
- src/specs/RNMBXMapViewNativeComponent.ts
Fixes: #1723, #3111
Added new option `deselectAnnotationOnTap`. Deselect will hide the callout.
> fix: add deselectAnnotationOnTap to deselect and hide pointannotation callout on press, refactor point annotation manager or android

- ios/RNMBX/RNMBXMarkerViewComponentView.mm
- ios/RNMBX/RNMBXViewportComponentView.mm
This fixes an invalid return in a utility function, and a nonexistent property being used in `LayoutMetrics` init. Both were causing build errors.
> fix: invalid return and property errors

- ios/RNMBX/RNMBXModule.swift
Fixes: setTelemetryEnabled did not work in iOS
Tested on v10.1.3 and v11
To test:
`Mapbox.setTelemetryEnabled(false);`
or
`Mapbox.setTelemetryEnabled(true);`
and press attribution icon -> mapbox telemetry (text is "you are helping..." -> true or "you can help..." -> false)
> fix(ios): setTelemetryEnabled

- android/src/main/java/com/rnmapbox/rnmbx/components/camera/RNMBXCamera.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/camera/RNMBXCameraManager.kt
- android/src/main/java/com/rnmapbox/rnmbx/utils/extensions/Dynamic.kt
Render1:
```jsx
<Camera followUserLocation={false} ... />
```
Render2:
```jsx
<Camera />
```
Was causing exception on null on android:
> fix(android): error when clearing followUserLocation

- android/src/main/java/com/rnmapbox/rnmbx/components/annotation/RNMBXPointAnnotation.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/annotation/RNMBXPointAnnotationCoordinator.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/mapview/RNMBXMapView.kt
- example/ios/Podfile.lock
Fixes: #3299 + Refactor RNMBXPointAnnotationCoordinator out of RNMBXMapView.kt
> fix(andorid): fix error when clicking on a point annotation's callout

- android/build.gradle
- android/src/main/java/com/rnmapbox/rnmbx/components/styles/RNMBXStyleValue.kt
- android/src/test/kotlin/com/rnmapbox/rnmbx/components/styles/RNMBXStyleValueTest.kt
Fixed a bug affecting locales such as
Turkish, where lowercase 'i' was incorrectly converted to 'İ' instead of 'I'. Now, the US locale is explicitly used for enum name conversion to ensure correct character mapping.
Fixes #3255
> fix(android): uppercase conversion in getEnumName() method

- src/RNMBXModule.ts
When RNMBXModule that means the native lib is not built show and error related to that
> feat: show error when RNMBXModule is null

- android/src/main/java/com/rnmapbox/rnmbx/components/mapview/RNMBXMapView.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/mapview/RNMBXMapViewManager.kt
Fixes #3326 by waiting until mMapView has been initialized.
> fix(android): requestDisallowInterceptTouchEvent broken

- example/src/examples/FillRasterLayer/RasterSource.js
Fixed typo from titlesize to tilesize in RasterSource example
File: example\src\examples\FillRasterLayer\RasterSource.js
> chore: fixed typo from titlesize to tilesize in RasterSource example

- ios/RNMBX/RNMBXMarkerViewComponentView.mm
- ios/RNMBX/RNMBXMarkerViewContentComponentView.mm
> iOS(fabric): fix markerview

- ios/RNMBX/RNMBXNativeUserLocation.swift
Fixes:
- Incorrect puckBearing name in switch case
- Resolved warnings in Xcode
- Puck images not being fetched after initial addToMap
- Puck images not being correctly applied when changed on the fly
```jsx
<Mapbox.MapView>
<Mapbox.Images
images={{ mapNavPuck: media.mapNavigationPuck }}
onImageMissing={(imageKey: string) => console.log('=> on image missing', imageKey)}
/>
<Mapbox.LocationPuck
puckBearing={
USER_TRACKING_MODES[userTrackingMode].key === 'followCourse'
? 'course'
: 'heading'
}
puckBearingEnabled={true}
topImage={
USER_TRACKING_MODES[userTrackingMode].key === 'followCourse' ? 'mapNavPuck' : undefined
}
/>
</Mapbox.MapView>
```
> Fix - iOS NativeUserLocation puckBearing logic typo and puck image updates not being applied properly

- android/src/main/java/com/rnmapbox/rnmbx/components/camera/RNMBXCamera.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/camera/RNMBXCameraManager.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/location/RNMBXNativeUserLocation.kt
- android/src/main/java/com/rnmapbox/rnmbx/utils/ExpressionParser.java
- android/src/main/java/com/rnmapbox/rnmbx/utils/Logger.kt
- android/src/main/java/com/rnmapbox/rnmbx/utils/extensions/Dynamic.kt
- Fixed puck images not being fetched after initial addToMap
- Fixed puck images not being correctly applied when changed on the fly
- Fixed camera follow props not properly accepting null/undefined values
- Fixed crash in ExpressionParser by wrapping in a try/catch
> Fix: Android User Location / Camera issues

- android/src/main/java/com/rnmapbox/rnmbx/components/camera/RNMBXCamera.kt
Fixes: #3371
Uses this component to repro/test:
```jsx
import { MapView, ShapeSource, LineLayer, Camera } from '@rnmapbox/maps';
class BugReportExample extends React.Component {
state = {
center: [-74.00597, 40.71427],
count: 0,
};
render() {
return (
<>
<Button
title="Change location"
onPress={() => this.setState({ center: [-74.01597, 40.71427] })}
/>
<Button
title={`Counter: ${this.state.count}`}
onPress={() => this.setState({ count: this.state.count + 1 })}
/>
<Camera centerCoordinate={this.state.center} zoomLevel={14} />
</MapView>
</>
);
}
}
export default BugReportExample;
```
> fix(android): initial centerCoordinate should apply

- android/src/main/java/com/rnmapbox/rnmbx/components/camera/CameraStop.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/camera/CameraUpdateItem.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/camera/RNMBXCamera.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/camera/RNMBXCameraManager.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/camera/constants/CameraMode.java
- android/src/main/java/com/rnmapbox/rnmbx/modules/RNMBXModule.kt
- example/src/examples/V10/CameraAnimation.tsx
This is a refactor to fix bounds and zoom handling on Android, similar to #3354 on iOS.
There wasn't a double-padding issue like on iOS, but Android did have these problems:
- couldn't zero out min or max zoom levels
- the zoom value was getting overridden after setting bounds
- the "move" camera animation mode just fell back to easing
See before and after (using example at [this commit](https://github.com/rnmapbox/maps/blob/24edfeb19dd2666574684942958825b07810bc80/example/src/examples/V10/CameraAnimation.tsx)):
Before:
https://github.com/rnmapbox/maps/assets/2423291/1e47eda5-c455-4775-acb9-c5978f2fd4ed
After:
https://github.com/rnmapbox/maps/assets/2423291/0a9c6802-df32-444c-9344-86b7903de24c
> refactor(android): camera bounds, zoom, and animation mode handling

- android/src/main/old-arch/com/rnmapbox/rnmbx/NativeRNMBXCameraModuleSpec.java
- src/specs/NativeRNMBXCameraModule.ts
iOS and Fabric setCamera methods were not working due to `stop` and `stops` difference in signature. This was introduced in #3376
> fix(ios,fabric): fix set camera signature

- setup-jest.js
Fixes https://github.com/rnmapbox/maps/pull/3108#issuecomment-1953501271
> fix(tests): remove top level useFakeTimers call

- ios/RNMBX/RNMBXCircleLayer.swift
- ios/RNMBX/RNMBXFillExtrusionLayer.swift
- ios/RNMBX/RNMBXFillLayer.swift
- ios/RNMBX/RNMBXLineLayer.swift
- ios/RNMBX/RNMBXModelLayer.swift
- ios/RNMBX/RNMBXRasterLayer.swift
- ios/RNMBX/RNMBXSkyLayer.swift
- ios/RNMBX/RNMBXSymbolLayer.swift
- ios/RNMBX/codeparts/LayerPropsCommon.codepart-swift.ejs
- scripts/autogenerate.mjs
In V11 `sourceLayer` `source` and `filter` properties moved from base Layer to applicable Layer subclasses. So `setOptions` no longer applies those settings:
https://github.com/rnmapbox/maps/blob/f5bdc0443cb0537b5ca211a9029a2ff0feb00106/ios/RNMBX/RNMBXLayer.swift#L294-L314
See https://github.com/mapbox/mapbox-maps-ios/blob/main/CHANGELOG.md
> Remove source, sourceLayer, filter properties from the Layer protocol requirement.
Used the following component to test:
```jsx
import {
MapView,
ShapeSource,
CircleLayer,
Camera,
Models,
ModelLayer,
circleLayer: {
circleRadiusTransition: { duration: 5000, delay: 0 },
circleColor: '#ff0000',
},
};
const features = {
features: [
{ …
```
> fix(v11,ios): implement filter and sourceId for v11 layers

- android/src/main/java/com/rnmapbox/rnmbx/components/mapview/RNMBXMapViewManager.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/styles/layers/RNMBXLayer.kt
If a layer is removed, because of a style change for example, then on android setting property will fail with: 
```log
Failed to update: circleRadiusTransition Set layer property "circle-radius-transition" failed: Layer circle-layer-0 is not in style {duration=5000, delay=0}
```
Seems to be because of internal details of mapbox android. Once a layer is added to a map `bindTo` is called to set delegate. So if we change a layer property it'll be reflected on the map. But the mapbox api has no means of clearing the layer. 
https://github.com/mapbox/mapbox-maps-android/blob/0b0060cdf3849f6c32312faa456cfe331c17e794/extension-style/src/main/java/com/mapbox/maps/extension/style/layers/Layer.kt#L31
```jsx
import {
Images,
MapView, …
```
> fix(android): fix layer not present errors on style change

- ios/RNMBX/RNMBXCamera.swift
Fixes: #3413
Issue was caused by change: #3354
Example to repro was:
```jsx
import React, { useRef, useEffect } from 'react';
import { MapView, ShapeSource, LineLayer, Camera } from '@rnmapbox/maps';
const aLine = {
type: 'LineString',
coordinates: [
[-74.00597, 40.71427],
[-74.00697, 40.71527],
],
};
const BugReportExample = () => {
const cameraRef = useRef();
setTimeout(() => cameraRef.current?.setCamera({ heading: 90 }), 2000);
}, []);
return (
<>
<Button
onPress={() => cameraRef.current?.setCamera({ heading: 90 })}
title="Set heading to 90"
/>
<Camera
defaultSettings={{
centerCoordinate: [-74.00597, 40.71427],
heading: 30,
zoomLevel: 14,
}}
ref={cameraRef}
/>
<ShapeSource id="idStreetLayer" …
```
> fix(ios,camera): apply camera changes when no center or bounds specified

- ios/RNMBX/RNMBXCustomLocationProvider.swift
- ios/RNMBX/RNMBXLocationModule.swift
- ios/RNMBX/RNMBXLogging.swift
Closes: #3411
https://github.com/rnmapbox/maps/assets/52435/ed1419ca-90b0-42e7-8e33-3642f379614f
Example:
```jsx
import React, { useRef, useEffect } from 'react';
import { Switch, View, Text } from 'react-native';
import {
MapView,
Camera,
CustomLocationProvider,
LocationPuck,
Viewport,
export default function BugReportExample() {
const [location, setLocation] = React.useState([-74.00597, 40.71427]);
const [useCustomLocation, setUseCustomLocation] = React.useState(false);
const interval = setInterval(() => {
setLocation((location) => [location[0] + 0.0001, location[1] + 0.0001]);
}, 500);
return () => clearInterval(interval);
}, []);
const viewportRef = useRef();
return (
<>
<View style={{ flexDirection: 'row', alignItems: 'center' }}> …
```
> fix(ios): fix custome location provider add/remove

- .github/workflows/ios-actions.yml
- example/.detoxrc.js
Fix CI issue 
```
==> Installing applesimutils from wix/brew
==> Pouring applesimutils-0.9.10.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/applesimutils/0.9.10: 2 files, 646.3KB
xcbeautify 1.6.0 is already installed but outdated (so it will be upgraded).
xcbeautify: A full installation of Xcode.app 15.0 is required to compile
this software. Installing just the Command Line Tools is not sufficient.
Xcode 15.0 cannot be installed on macOS 12.
You must upgrade your version of macOS.
Error: xcbeautify: An unsatisfied requirement failed this build.
Error: Process completed with exit code 1.
```
> fix(ci,ios): use macOS-13 for ci

- README-v10.md
- rnmapbox-maps.podspec
Fixes #3432
```
[!] CocoaPods could not find compatible versions for pod "rnmapbox-maps":
In Podfile:
rnmapbox-maps (from `../node_modules/@rnmapbox/maps`)
Specs satisfying the `rnmapbox-maps (from `../node_modules/@rnmapbox/maps`)` dependency were found, but they required a higher minimum deployment target.
```
- Change the requirement of Mapbox v11 from iOS 13.0 down to 12.4
- Also changed the documentation to encourage supporting lower iOS versions. Each react-native release has a minimum predefined that we should use.
I don't see any downside to lowering the requirement yet.
> Support for iOS 12.4 with Mapbox Maps SDK v11

- android/src/main/java/com/rnmapbox/rnmbx/components/AbstractEventEmitter.kt
Fixes #3267
My impression is that Kotlin 1.9 got more strict with overrides, and [the react native source](https://github.com/facebook/react-native/blame/746ad378c7efe3ee2f4926ab30e5401407f8b3ba/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ViewManager.java#L242)  used `@NonNull` and we have to correspondingly do a non-null type. Tested it locally and it works. Got the inspiration from [this similar issue](https://github.com/invertase/react-native-google-mobile-ads/issues/511#issuecomment-1901281853)
See https://kotlinlang.org/docs/generics.html#definitely-non-nullable-types. I believe this is backwards compatible with most RN + Kotlin versions given that this definitely non-nullable syntax was introduced in 1.6.20
```jsx
```
> Update AbstractEventEmitter.kt to fix `'addEventEmitters' overrides nothing` issue

- android/build.gradle
- android/src/main/java/com/rnmapbox/rnmbx/components/images/RNMBXImages.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/styles/RNMBXStyle.kt
- android/src/main/java/com/rnmapbox/rnmbx/utils/DownloadMapImageTask.kt
- it was not possible before to change image for existing image ID contrary to iOS even though it's supported in the native component
- DownloadMapImageTask image loading was slightly improved to load images in parallel
Fixes #3331
```jsx
const Markers: React.FC<MarkersProps> = (props) => {
const { map } = useMap();
const boundsChanged = useMapCameraIdle().cameraIdleBounds;
const [renderedFeatureIds, setRenderedFeatureIds] = useState<string[]>([]);
if (!boundsChanged) return;
const func = async () => {
const renderedFeatures = await map.current?.queryRenderedFeaturesInRect(
[0, 0, 9000, 9000],
[],
[`SymbolLayer${props.layerId}Large`]
);
if (!renderedFeatures) return;
setRenderedFeatureIds([
...renderedFeatures.features.map((f) => `${f.id}`),
// keep image for previously …
```
> Android - make it possible to change image for existing image ID, improve performance of DownloadMapImageTask

- android/build.gradle
See https://github.com/rnmapbox/maps/pull/3431/files#r1581840316
> fix: fix kotlin corutines to 1.8.0 instead of binding to kotlin version

- ios/RNMBX/RNMBXMapView.swift
- ios/RNMBX/RNMBXMapViewManager.swift
Fixes: https://github.com/rnmapbox/sponsors/issues/4
Repo, thanks much: @benjamin-sweney 
```js
import React, { useEffect, useRef } from 'react';
import { View } from 'react-native';
import { MapView } from '@rnmapbox/maps';
const Example = () => {
const ref = useRef(null);
const check = async () => {
const center = await ref.current?.getCenter();
console.log(center);
};
setTimeout(check, 1000);
}, []);
return (
<View style={{ flex: 1, justifyContent: 'center' }}>
<MapView
ref={ref}
zoomEnabled={false}
scrollEnabled={false}
scaleBarEnabled={false}
style={{ height: 400 }}
/>
</View>
);
};
export default Example;
```
> fix(os): fix unavailable mapView on initialization

- src/web/components/Camera.tsx
Implemented all methods of CameraRef except SetCamera and implemented zoom CameraProps
> Improved web Camera

- ios/RNMBX/RNMBXCameraModule.mm
After moving the camera more than 500 times in quick succession, the native produces the warning
> Excessive number of pending callbacks
I discovered a missing invocation of the `resolve` callback in `updateCameraStop`. This change fixes the issue.
(Also see https://github.com/rnmapbox/maps/issues/2087).
> Call `resolve()` to fix pending callbacks warning

- setup-jest.js
This library includes an `AbortController` test mock, which doesn't work in places that expect a real one. For example, I was writing an unrelated test that tried to cancel a `fetch()` which failed because the `AbortController`'s `signal` property was invalid.
Because [`AbortController` is in all supported Node versions][0], we can safely remove this mock and rely on the real thing.
This should only affect tests.
This test fails before this change:
```js
test("AbortController has an AbortSignal", () => {
const abortController = new AbortController();
expect(abortController.signal).toBeInstanceOf(AbortSignal);
});
```
[0]: https://developer.mozilla.org/en-US/docs/Web/API/AbortController#browser_compatibility
> Remove AbortController test mock

- android/build.gradle
- android/install.md
- example/android/build.gradle
- example/ios/Podfile
- ios/install.md
- plugin/install.md
- rnmapbox-maps.podspec
Up android to 10.18.0 and iOS to 10.18.2
> chore: upgrade default mapbox maps releases - 10.18.0 and 10.18.2

- android/src/main/java/com/rnmapbox/rnmbx/components/mapview/NativeMapViewModule.kt
Fixes: #3518 , #3522 
Sound like an RN 0.74 Codegen bug to me.
For now adding a workaround implementing method with Double as first arg too.
In `/src/specs/NativeMapViewModule.ts`
```java
setHandledMapChangedEvents: (
viewRef: Int32 | null,
events: ReadonlyArray<string>,
) => Promise<Object>;
```
in android/build/generated/source/codegen/jni/rnmapbox_maps_specs-generated.cpp:
```cpp
static facebook::jsi::Value __hostFunction_NativeMapViewModuleSpecJSI_setHandledMapChangedEvents(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
static jmethodID cachedMethodId = nullptr;
return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "setHandledMapChangedEvents", …
```
> fix(andorid,newarch): setHandledMapChangedEvents issue

- src/web/index.js
Mapbox-gl needs its css to be loaded in order to display the attribution (and maybe other things) correctly.
> Fixed mapbox-gl style

- src/RNMBXModule.ts
- src/specs/RNMBXMapViewNativeComponent.ts
On RN 0.74 with new arch enabled (bridgeless) I encountered 2 errors.
The first one is because of the copy of the native module object. With new arch bridgeless the native module are proxy objects so copying it just results in an empty object, which resulted in my app crashing when calling `setAccessToken`.
The 2nd one is related to codegen: `Invariant Violation: Event cannot be both direct and bubbling: topPress`. This seems to happen because we extend `ViewProps` and it already defines a onPress prop that is a `BubblingEventHandler`. Changing it to `BubblingEventHandler` fixes it.
Tested in the example app by enabling bridgeless and testing that Show click example still works.
N/A
N/A
> Fix issues with rn 0.74 bridgeless

- src/types/Position.ts
I revised the doc comment of type `Position` because it caused confusing for me when using `coordinate` props of `MapMarker`. The current comment indicated `latitude and longitude` so I put the values as `[latitude, longitude]` which resulted in a crash in my Android app without any error. I was stuck for a while and later discovered that when running iOS app, it showed exceeded value range of `longitude`. I hope this minor update might help Maps newbies save their time on this one.
> chore: update Position type document with correct coordinate order

- ios/RNMBX/RNMBXFabricPropConvert.h
- ios/RNMBX/RNMBXMapViewComponentView.mm
This fixes `scaleBarEnabled={false}` on new arch. `RNMBXConvertFollyDynamicToId` converts to NSBoolean * so when assigning to a Bool prop it is always true. To fix it I used the `RNMBX_OPTIONAL_PROP_BOOL` macro which handles deferencing the pointer properly.
Tested in an app using new arch, before the change the scale bar is always visible even when setting `scaleBarEnabled={false}`. After the scale bar is properly hidden.
```jsx
```
> Fix scaleBarEnabled on new arch

- ios/RNMBX/RNMBXFabricPropConvert.h
- ios/RNMBX/RNMBXFabricPropConvert.mm
- ios/RNMBX/RNMBXShapeSourceComponentView.mm
On new arch when the map re-renders it causes the following error when using the `clusterMaxZoomLevel` prop. This is because this prop cannot be updated in mapbox-ios. This isn't a problem in the old architecture since the prop handler is only called when the prop changes, in the new arch it needs to be handled manually by comparing the props values.
```
Mapbox [error] RNMBXShapeSource | clusterMaxZoomLevel  Cannot set property clusterMaxZoom for the source symbolLocationSource
```
After this the error no longer appears, unless actually changing the value of `clusterMaxZoom`.
It might be a good pattern to adopt generally for all components and props, but I thought it was out of scope of this since it would become a pretty big refactor.
Tested this change in an app that makes use of …
> Fix error in clusterMaxZoomLevel on new arch

- docs/UserLocation.md
- docs/docs.json
- src/components/UserLocation.tsx
Follow-up for https://github.com/rnmapbox/maps/pull/3222
> refactor!:use LocationPuck instead of deprecated NativeUserLocation

- ios/RNMBX/Extensions/Array+asExpressions.swift
- ios/RNMBX/RNMBXLayer.swift
- ios/RNMBX/RNMBXStyleValue.swift
Fixes the issue where ‘Expression’ is ambiguous for type lookup in Xcode 16. This resolves compilation errors related to ‘Expression’ type ambiguities in RNMBXLayer, RNMBXStyleValue, and other affected components.
Run the RNMapbox in Xcode 16
> resolve ambiguous `expression` issue introduced in Xcode 16

- android/src/main/java/com/rnmapbox/rnmbx/components/camera/RNMBXCamera.kt
> fix(andorid): fix potential null mapView when applying camera

- CONTRIBUTING.md
- ios/RNMBX/RNMBXMapView.swift
Fixes #3614
The reason this function stopped working in Mapbox 11 seems because of the change [noted here](https://docs.mapbox.com/ios/maps/api/11.0.0/documentation/mapboxmaps/migrate-to-v11/#2123). This is my first attempt at fixing it. We are already using the fix in our project.
I'm on some hard deadlines, so need some external help with:
* Making this code more proper (I'm not a Swift developer, I'm sure there's lots I can improve here)
* Testing w/ the example app.
Also snuck in a typo fix in the docs, hopefully that's okay!
Please compare with the video in #3614 
https://github.com/user-attachments/assets/9cc40bcd-4e25-43d2-9434-6cf324671571
See the component in #3614
> feat(ios): enable setSourceVisibility for Mapbox 11

- android/src/main/java/com/rnmapbox/rnmbx/components/styles/sources/RNMBXRasterSourceManager.kt
- android/src/main/java/com/rnmapbox/rnmbx/events/constants/EventKeys.kt
- example/android/app/src/main/java/com/rnmapboxglexample/MainApplication.kt
We at [Software Mansion](https://swmansion.com/) have been working on [improving support](https://blog.swmansion.com/sunrising-new-architecture-in-the-new-expensify-app-729d237a02f5) for the new architecture for quite a while now. If you need help with anything related to New Architecture, like:
- [migrating your library](https://x.com/swmansion/status/1717512089323864275)
- [migrating your app](https://github.com/Expensify/App/pull/13767)
- [investigating issues](https://github.com/facebook/react-native/pulls?q=sort%3Aupdated-desc+is%3Apr+author%3Aj-piasecki+is%3Aopen)
- [improving performance](https://x.com/BBloniarz_/status/1808138585528303977)
or you just want to ask any questions, hit us up on [projects@swmansion.com](mailto:projects@swmansion.com)
---
Fixes events on bridgeless mode …
> fix: events in bridgeless mode

- android/build.gradle
- rnmapbox-maps.podspec
upgrade default mapbox ios to 10.19 and android to 10.18.4
> chore: up default mapbox ios to 10.19 and android to 10.18.4

- android/src/main/java/com/rnmapbox/rnmbx/modules/RNMBXModule.kt
Android crashes when calling `.clearData()` on v10
```
2024-10-20 16:41:04.051 17011-17011 System.err              com.rnmapboxglexample                W  java.lang.RuntimeException: Cannot convert argument of type class com.mapbox.bindgen.None
2024-10-20 16:41:04.053 17011-17011 System.err              com.rnmapboxglexample                W  	at com.facebook.react.bridge.Arguments.fromJavaArgs(Arguments.java:191)
2024-10-20 16:41:04.053 17011-17011 System.err              com.rnmapboxglexample                W  	at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:31)
2024-10-20 16:41:04.053 17011-17011 System.err              com.rnmapboxglexample                W  	at com.facebook.react.bridge.PromiseImpl.resolve(PromiseImpl.java:60)
2024-10-20 16:41:04.053 17011-17011 …
```
> fix(android): fix crash calling clearData

- ios/RNMBX/RNMBXRasterDemSource.swift
Fixes the DEM raster source layer in Mapbox V11 from being used
Fixes #3567
> fix: v11 Raster DEM source id

- ios/RNMBX/RNMBXMapViewManager.swift
- ios/RNMBX/RNMBXMapViewModule.mm
Fixes runtime exception in getVisibleBounds (iOS only)
```jsx
```
> Fix[iOS]: get visit bounds

- example/ios/Podfile
- ios/RNMBX/RNMBXMarkerView.swift
Fixes #3663
This means v11 will default to v10 behaviour where moving markar view out of paddings area will not change visibility.
> fix(v11): default to ignoreCameraPadding with view annotations 

- android/src/main/java/com/rnmapbox/rnmbx/components/styles/sources/RNMBXRasterSource.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/styles/sources/RNMBXRasterSourceManager.kt
- android/src/main/java/com/rnmapbox/rnmbx/components/styles/sources/RNMBXTileSource.kt
- android/src/main/old-arch/com/facebook/react/viewmanagers/RNMBXRasterSourceManagerDelegate.java
- android/src/main/old-arch/com/facebook/react/viewmanagers/RNMBXRasterSourceManagerInterface.java
- docs/RasterSource.md
- docs/docs.json
- example/src/examples/FillRasterLayer/RasterSource.js
- ios/RNMBX/RNMBXRasterSource.swift
- ios/RNMBX/RNMBXRasterSourceComponentView.mm
- ios/RNMBX/RNMBXRasterSourceViewManager.m
- src/components/RasterSource.tsx
- src/specs/RNMBXRasterSourceNativeComponent.ts
Added `bounds support for RasterSource` . Now, you can limit the bounds within which raster tiles will render.
> feat: Add bounds to raster source

- example/ios/Podfile
- ios/install.md
- plugin/install.md
- rnmapbox-maps.podspec
Fixes #3640 
Fixes #3688
```jsx
```
> Upgrade mapbox version 11.4.0 -> 11.8.0

- ios/RNMBX/RNMBXMapViewComponentView.mm
Fix applying of boolean properties: `attributionEnabled, logoEnabled, compassEnabled, compassFadeWhenNorth, zoomEnabled, rotateEnabled, pitchEnabled` to MapView component on iOS with New Architecture enabled. 
The bug has been caused by a boolean type casting mistake in RNMBXMapViewComponentView.mm class.
All boolean props were casting to `id` type that always cast to `true` when passing to Swift RNMBXMapView class. 
https://github.com/user-attachments/assets/e5072c75-eed1-4840-8fd5-600cacd3cd47
```
<MapView
ref={(c) => (this._map = c)}
onPress={this.onPress}
style={styles.mapView}
attributionEnabled={false}
logoEnabled={false}
scaleBarEnabled={false}
zoomEnabled={false}
rotateEnabled={false}
pitchEnabled={false}
>
<Camera zoomLevel={9} centerCoordinate={[-73.970895, 40.723279]} /> …
```
> Fix applying of bool properties for MapView component on iOS with New Arch enabled

- .eslintrc.js
- bob.config.js
- package.json
- plugin/copy-plugin.ts
- plugin/tsconfig.eslint.json
- yarn.lock
> chore(build): copy plugin to commonjs

- ios/RNMBX/RNMBXLocationModule.swift
Fix `[Bug]: (NOBRIDGE) WARN locationManager Error: [Error: RNMBXLocationModule.getLastKnownLocation()Objective C type was unsupported.` as in non bridge mode we cannot pass custom objc types but only objc primiitives including a dict
Fixes #3707
```jsx
```
> fix nobridge obj-c type unsupported

- android/src/main/java/com/rnmapbox/rnmbx/components/annotation/RNMBXMarkerViewContent.kt
I'm currently looking into reducing visibility to the public API surface of React Native. I've noticed you are one of the few repos using `com.facebook.react.uimanager.MeasureSpecAssertions`; this import is currently unused in this codebase hence I'd like to remove it to reduce breaking changes across the ecosystem.
N/A
N/A
> Remove unused com.facebook.react.uimanager.MeasureSpecAssertions import

- android/src/main/java/com/rnmapbox/rnmbx/modules/RNMBXLocationModule.kt
- android/src/main/old-arch/com/rnmapbox/rnmbx/NativeRNMBXLocationModuleSpec.java
- src/modules/location/locationManager.ts
Fixes [3796](https://github.com/rnmapbox/maps/issues/3796)
> Fix(android): Prevent crash in old architecture when updating user location

- android/src/main/java/com/rnmapbox/rnmbx/components/annotation/RNMBXMarkerView.kt
- android/src/main/mapbox-v11-compat/v10/com/rnmapbox/rnmbx/v11compat/Annotation.kt
Fixes #3887 
See demo GIFs in #3887. Android now behaves the same as iOS (_marker views don't disappear anymore_).
See demo code in #3887.
> fix(android): ignore camera padding for marker view

- .github/workflows/publish.yml
The publish workflow was using Node.js 14.x which is incompatible with react-native-builder-bob's arktype dependency. This causes the ERR_REQUIRE_ESM error during npm publish.
Changes:
- Remove duplicate Node.js setup that was overriding the .nvmrc version
- Update to actions/setup-node@v4 for better compatibility
- Use yarn install instead of npm install for better module handling
- Fix deprecated set-output syntax to use GITHUB_OUTPUT
This fixes the "Error [ERR_REQUIRE_ESM]: Must use import to load ES Module" error that was preventing successful npm publishes.
```jsx
```
> fix: Fix npm publish error by updating Node.js version in workflow

- android/src/main/java/com/rnmapbox/rnmbx/shapeAnimators/RNMBXChangeLineOffsetsShapeAnimatorModule.kt
- android/src/main/java/com/rnmapbox/rnmbx/shapeAnimators/RNMBXMovePointShapeAnimatorModule.kt
- android/src/main/old-arch/com/rnmapbox/rnmbx/NativeRNMBXChangeLineOffsetsShapeAnimatorModuleSpec.java
- android/src/main/old-arch/com/rnmapbox/rnmbx/NativeRNMBXMovePointShapeAnimatorModuleSpec.java
- src/shapeAnimators/ChangeLineOffsetsShapeAnimator.ts
- src/shapeAnimators/MovePointShapeAnimator.ts
- src/specs/NativeRNMBXChangeLineOffsetsShapeAnimatorModule.ts
- src/specs/NativeRNMBXMovePointShapeAnimatorModule.ts
Fixes #3938
The changes in this PR only pertain the issue and they are the bare minimum needed to fix the bug
**Spec update:**
- Renamed create(...) → createAnimator(...) in the TypeScript spec to prevent clashes with the base TurboModule::create method in C++/JSI.
- Regenerated code to reflect the new method name.
**Android modules:**
- Updated RNMBXChangeLineOffsetsShapeAnimatorModule.kt and RNMBXMovePointShapeAnimatorModule.kt to implement the new createAnimator(...) signatures generated by codegen.
- Removed obsolete override fun create(...) which no longer exists in the spec.
- Aligned parameter types (Double, ReadableArray, Promise) with the generated spec.
`JS API:`
- Calls now go through createAnimator(...)
**Motivation**
Prevents C++ build failure (-Woverloaded-virtual) caused by …
> Fix #3938 Android build issue happening when integrating @rnmapbox/maps with RN 0.81.0

- __tests__/components/Callout.test.js
- __tests__/components/UserLocation.test.js
- __tests__/utils/BridgeValue.test.js
Fixes #3943
- Corrected tests:
•	Wrapped state updates in act where required in UserLocation.test.js. UserLocation tests: all succeeding now, with no error thrown anymore.
•	Updated the `Callout.test.js` file because they were failing not because the components are built wrong, but because the test didn't take in consideration the way the style of the component is made based on different scenarios (Specifically the style is not always an array, but it could be a plain object).
•	Updated the `UserLocation` tests to make them more reliable in evaluating the proper conditions to expect.
•	Ensured generated docs (UserLocation.md) reflect the updated setLocationManager signature.
•	Removing empty test from `BridgeValue.test.ts` file
[Breaking change] Updating `UserLocation` …
> chore: Fixing Tests

- .github/workflows/ios-actions.yml
- example/.detoxrc.js
- example/ios/Podfile
- example/ios/Podfile.lock
- example/package.json
- rnmapbox-maps.podspec
Detox builds are broken on iOS. Try to fix them to make ci run on main again
```
<unknown>:0: error: module map file '/Users/runner/work/maps/maps/example/ios/build/Build/Products/Debug-iphonesimulator/rnmapbox-maps/rnmapbox_maps.modulemap' not found
```
> chore(ci): fix detox build

- ios/RNMBX/RNMBXShapeSourceComponentView.mm
Closes: #3866
Fixes #3863
```jsx
```
> fix(ios): support 'url' prop for ShapeSource on iOS

- android/src/main/mapbox-v11-compat/v11/com/rnmapbox/rnmbx/v11compat/Image.kt
Fixes #3830
Take snap on android was crashing on v11
```jsx
import { snapshotManager } from '@rnmapbox/maps';
import { useEffect, useState } from 'react';
import { View, Image } from 'react-native';
const MapboxBugTestComponent = () => {
const [snapshotURI, setSnapshotURI] = useState();
(async () => {
const uri = await snapshotManager.takeSnap({
centerCoordinate: [-74.12641, 40.797968],
});
console.log('uri', uri);
setSnapshotURI(uri);
})();
}, []);
return (
<View
style={{
flex: 1,
backgroundColor: 'blue',
justifyContent: 'center',
alignItems: 'center',
}}
>
{snapshotURI ? (
<View style={{ width: 300, height: 300 }}>
<Image
source={{ uri: snapshotURI }}
style={{ width: '100%', height: '100%', resizeMode: 'contain' }}
/>
</View>
) : null} …
```
> fix(android,v11): fix takeSnap

- android/src/main/java/com/rnmapbox/rnmbx/components/mapview/RNMBXMapView.kt
Fixes: getPointInView function return wrong point position on Android.
> Fix getPointInView function return wrong point position on Android
