ios/install.md

Fixed path to @react-native-mapbox/maps
Added additional visual elements to iOS installation documentation for added clarity during installation steps.

iOS Installation Docs Fixes & Enhancements

---

README.md

sorry, just noticed myself and wasn't fast enough before it got merged

fix(readme): add missing markdown extension

---

.travis.yml

Travis build configuration, doesn't do much yet, but builds the ios example.
Example build:
https://travis-ci.org/mfazekas/maps-1/jobs/526960739

Try travis CI

---

CONTRIBUTING.md

some minor updates to the contribution file
* adjust headings
* adjust init command
* replace project name
* adjust `link` command
* replace platform specific index files with typescript definition file

docs: update contribution file

---

README.md

[Doc] Add build badge to readme.md

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleFactory.java
docs/Annotation.md
docs/BackgroundLayer.md
docs/Camera.md
docs/CircleLayer.md
docs/FillExtrusionLayer.md
docs/FillLayer.md
docs/Light.md
docs/LineLayer.md
docs/MapView.md
docs/RasterLayer.md
docs/SymbolLayer.md
docs/UserLocation.md
docs/docs.json
ios/RCTMGL/RCTMGLStyle.h
ios/RCTMGL/RCTMGLStyle.m
javascript/components/MapView.js
javascript/utils/styleMap.js
scripts/autogenHelpers/DocJSONBuilder.js
scripts/autogenHelpers/globals.js
scripts/autogenerate.js
scripts/templates/component.md.ejs
style-spec/v8.json

updated + ran autogen scripts to update code prop-types and docs

Updated autogen scripts and ran on updated v8.json

---

ios/install.md

Made a change to install docs based on https://github.com/nitaliano/react-native-mapbox-gl/issues/1506. 
Needs reviewed by anyone that is using pods

Proposed Update To iOS Pod; RCTTest Removal

---

android/install.md

* add diff coloring
* adjust to newer react-native seed files
* align with files in example project
Feedback welcome - not really an android native crack here.

docs: adjust android install guide

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleValue.java

Fixed android transitions values

---

example/src/examples/SetUserTrackingModes.js
example/src/examples/common/MapHeader.js
example/src/scenes/Home.js

Unnecessary margin at the top of the list.

Small tweaks

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/light/RCTMGLLight.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLShapeSource.java

Fix style = null crashes

---

docs/StyleSheet.md

I just fixed a typo resulting in a pretty nasty Xcode crash

Updated StyleSheet.md typo

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/location/UserTrackingMode.java

Fix null in UserTrackingMode.fromString

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLShapeSource.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLShapeSourceManager.java

[android] fix ImageEntry map

---

docs/UserLocation.md
docs/docs.json
ios/RCTMGL/RCTMGLStyle.m
scripts/autogenHelpers/globals.js
scripts/templates/RCTMGLStyle.m.ejs
scripts/templates/RCTMGLStyleFactory.java.ejs

See: https://github.com/react-native-mapbox-gl/maps/pull/71#issuecomment-498647607

Fix autogen templates

---

ios/install.md

Added more info about how to resolve strip-frameworks.sh not being found.

Update iOS install docs

---

example/package.json
example/scripts/npm_pack_rngl.sh

Make build process independent on package.json version

7.0.0 rc2 release

---

README.md

Depfu is now enabled on the repo

Add depfu badge to readme

---

ios/RCTMGL/RCTMGLCircleLayer.m
ios/RCTMGL/RCTMGLFillExtrusionLayer.m
ios/RCTMGL/RCTMGLFillLayer.m
ios/RCTMGL/RCTMGLLineLayer.m
ios/RCTMGL/RCTMGLSymbolLayer.m

On filter parse errors show redbox messages instead of crashing

---

__tests__/__mocks__/react-native-mapbox-gl.mock.js
__tests__/interface.test.js
example/src/examples/common/MapHeader.js
example/src/scenes/Home.js
index.d.ts
ios/RCTMGL/MGLModule.m

Since the feature is not available on Android, I suggest we remove it fully from the code base.

Remove all instances of isTelemetryEnabled

---

example/src/examples/EarthQuakes.js

Replace deprecated filter syntax with new expression syntax - see https://github.com/react-native-mapbox-gl/maps/issues/70#issuecomment-499775185

Fixed EarthQuakes example

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleValue.java

[android] non url image fix

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleFactory.java
scripts/autogenHelpers/globals.js
scripts/templates/RCTMGLStyleFactory.java.ejs

Use prop.image instead of prop.name to determine if it's an image

---

example/src/examples/ShowPointAnnotation.js
ios/RCTMGL/RCTMGLCallout.m

Fixed callout on ios

---

README.md
android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleFactory.java
docs/HeatmapLayer.md
docs/docs.json
example/src/examples/Heatmap.js
example/src/scenes/Home.js

Minor updates to heatmap PR, added example, and reran generate scripts

Added example, updated docs

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/AbstractEventEmitter.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/events/EventEmitter.java

Droid: remove emitter.receiveEvent as it causes double events

---

ios/RCTMGL/CameraUpdateItem.m
ios/RCTMGL/RCTMGLMapView.h
ios/RCTMGL/RCTMGLMapView.m

Fixes an issue where a camera update is calculating the `altitude` using the current camera's `latitude` instead of the next camera's `latitude`. This could result in weird camera zoom behavior impacted by the latitude distance between current and the next camera.
Below I wrote some code to reproduce the issue. When swapping between the two destinations you'll see it zooms to the destination, however a second press on the same destination causes the zoom to slightly change a bit. 
<details>
<summary>Code</summary>
```jsx
import {View, StyleSheet, Text, TouchableOpacity} from 'react-native';
import MapboxGL from '@react-native-mapbox-gl/maps';
import Page from './common/Page';
const styles = StyleSheet.create({
container: {
flex: 1,
},
map: { …
```

Fixed inconsistent zoom / altitude camera behavior

---

ios/RCTMGL/RCTMGLCamera.m

Apply defaultSettings after map view is laid out

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
example/src/examples/ShowRegionDidChange.js
javascript/components/MapView.js

android onRegionIsChanging

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleValue.java
example/src/examples/ShapeSourceIcon.js
ios/RCTMGL/RCTMGLStyleValue.m

Images: fixed expressions as iconImage

---

javascript/utils/geoUtils.js
package.json

Fix turf dependency versions

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleValue.java

Fixed android images with expressions

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLShapeSourceManager.java
ios/RCTMGL/RCTMGLUtils.m
javascript/components/ShapeSource.js

Fixes: #68
See: https://github.com/react-native-mapbox-gl/maps/issues/68#issuecomment-506686029

Use proper image scale at Images component too

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleValue.java

Android: strings without :// should resolve to Images vs loaded directly

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/CameraStop.java

Adding contentInset to camera padding to align camera behavior with iOS

---

.gitignore
android/build.gradle
android/rctmgl/src/main/java/com/mapbox/rctmgl/http/CustomHeadersInterceptor.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLModule.java
index.d.ts
ios/RCTMGL/MGLModule.m

Add support for sending custom http headers from mapbox sdk 
Android only in this iteration

Implement support for sending custom headers for map resources

---

docs/MapView.md
javascript/components/Camera.js
javascript/components/MapView.js

As those functions are removed from MapView, I removed the doc and Proptypes

🔥 Removing old location parameters from MapView

---

javascript/components/MapView.js
javascript/components/NativeBridgeComponent.js

NativeBridgeComponent/ _runPendingNativeCommands fix

---

javascript/components/MapView.js

Fixes: #326 
Closes: #327
See: #272

Remove 2 arg _runNativeCommand

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/layers/RCTLayer.java

See https://github.com/react-native-mapbox-gl/maps/pull/197/files#r299395756

mMap.getStyle() => getStyle refactoring in RTCLayer

---

CONTRIBUTING.md
__tests__/modules/snapshot/SnapshotOptions.test.js
android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLSnapshotModule.java
docs/Annotation.md
docs/Camera.md
docs/MapView.md
docs/PointAnnotation.md
docs/VectorSource.md
docs/docs.json
docs/snapshotManager.md
example/package.json
example/src/examples/TakeSnapshot.js
ios/RCTMGL/MGLSnapshotModule.m
javascript/modules/snapshot/SnapshotOptions.js
javascript/modules/snapshot/snapshotManager.js
scripts/autogenHelpers/DocJSONBuilder.js

#236 iOS Snapshotter as __block variable

---

android/install.md

Corrected path to `settings.gradle` file for android setup

Update install.md, changed to correct file path

---

docs/StyleSheet.md

Changelog has gone from txt to Markdown

Fix broken link

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java

Only prevent propagation when scrolling is enabled

---

ios/RCTMGL/RCTMGLMapViewManager.m
package.json
react-native-config.js

Fix iOS programatic region did change and add react native config

---

ios/RCTMGL.xcodeproj/project.pbxproj
package.json

Fix missing rctmgltilesource

---

javascript/components/RasterSource.js

Improved detection when a tile template url is used as url props

---

ios/RCTMGL/MGLCustomHeaders.m

Fix case of import that breaks build in case sensitive environments

---

index.d.ts
package.json

Types: Use standard geojson types

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java

Add feature to queued features until all queued features are added

---

package.json

Increment version to 7.0.8

---

index.d.ts

fix(typescript): set filter type to array<any> to prevent false negtive

---

docs/UserLocation.md
docs/docs.json
javascript/components/UserLocation.js

Added some documentation for UserLocation
Additionally changed `get userIconLayers` to `_userIconLayers`.
Please let me know if I didn't get something...
Didn't make any sense to me and this way it's consistent with our private/ public method setup.
Looking forward to a review

docs: Add documentation for UserLocation

---

index.d.ts

Also added missing `resetDatabase` method to `OfflineManager`

Added typescript definitions for offlineManager / snapshotManager on MapboxGL

---

android/rctmgl/build.gradle
scripts/autogenerate.js

to latest stable as of 01.01.2020, issue #592 
https://github.com/mapbox/mapbox-gl-native-android/blob/android-v8.6.0/CHANGELOG.md
https://github.com/mapbox/mapbox-java/blob/master/CHANGELOG.md
https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-localization/CHANGELOG.md

upgrading mapbox core android libraries 

---

ios/RCTMGL/RCTMGLCamera.m

This is also needed on Android where the problem is bigger.

Stop followUserMode from changing with no manual changes [ios]

---

__tests__/components/BackgroundLayer.test.js
__tests__/modules/offline/OfflineCreatePackOptions.test.js
__tests__/modules/offline/OfflinePack.test.js
__tests__/modules/offline/offlineManager.test.js
__tests__/modules/snapshot/SnapshotOptions.test.js
__tests__/utils/BridgeValue.test.js
javascript/components/BackgroundLayer.js
javascript/utils/BridgeValue.js

This adds some unit tests for the `BackgroundLayer` component.
Basically just checking if passed in props are rendered correctly on the other side.

test: add some for backgroundlayer

---

index.d.ts

Forgot to add `minDisplacement` to `UserLocationProps` in `index.d.ts`.

chore(userlocation): update type with minDisplacement

---

docs/UserLocation.md
docs/docs.json
javascript/components/UserLocation.js

Fix typo in docs. Should be `whether` instead of `wheather`

docs(user-location): fix typo s/Wheather/Whether

---

package.json

* disable verbose: if something fails you will be notified where it is
* disable coverage: just clutters up travis log

test: reduce output

---

docs/MapView.md
docs/docs.json
javascript/components/MapView.js

Added compassViewPosition docs

---

javascript/components/AbstractLayer.js
javascript/components/SymbolLayer.js

Allow animated style values

---

ios/RCTMGL/RCTMGLShapeSource.m

[iOS] Allow url to change on the ShapeSource

---

example/src/App.js

Fixes: #668 
In particular: 
https://github.com/react-native-mapbox-gl/maps/issues/668#issuecomment-586370901

Fixed Unrecognized font familiy Material Icons

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleFactory.java
docs/BackgroundLayer.md
docs/FillExtrusionLayer.md
docs/FillLayer.md
docs/LineLayer.md
docs/SymbolLayer.md
docs/docs.json
ios/RCTMGL/RCTMGLStyle.h
ios/RCTMGL/RCTMGLStyle.m
ios/RCTMGL/index.d.ts
javascript/components/RasterSource.js
javascript/utils/styleMap.js
scripts/autogenHelpers/globals.js
scripts/autogenerate.js
style-spec/v8.json

Autogenerate now gets versions from `react-native-mapbox-gl.podspec` and `build.gradle`, also fixed broken vers number compare

Update style json, improve autogenerate

---

.gitignore
android/rctmgl/src/main/java/com/mapbox/rctmgl/components/annotation/RCTMGLPointAnnotation.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/CameraStop.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/CameraUpdateItem.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/RCTMGLCamera.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/constants/CameraMode.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyle.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleValue.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLShapeSource.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLVectorSource.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLVectorSourceManager.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTSource.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/events/LocationEvent.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/events/MapClickEvent.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/events/PointAnnotationClickEvent.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/events/PointAnnotationDragEvent.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLLocationModule.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/utils/ResourceUtils.java
package.json

[8.0.0] AndroidX

---

android/rctmgl/build.gradle
android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java

Upgrade android mapbox to 9.0.0

Upgrade android mapbox to 9.0.0

---

example/package.json

See https://github.com/react-native-mapbox-gl/maps/pull/659#issuecomment-588145155

Add jest.setupFilesAfterEnv to example jest config

---

react-native-mapbox-gl.podspec

Upgrade ios mapbox to 5.7.0

---

__tests__/interface.test.js
__tests__/modules/offline/OfflineCreatePackOptions.test.js
example/src/examples/CustomIcon.js
example/src/examples/DriveTheLine.js
example/src/utils/RouteSimulator.js
javascript/index.js

Dont export geoUtils

---

docs/Images.md
docs/docs.json
javascript/components/Images.js

The `onImageMissing` was not commited in #664

Added missing onImageMissing

---

__tests__/components/UserLocation.test.js
docs/UserLocation.md
docs/docs.json
javascript/components/UserLocation.js

Added tests for UserLocation methods.
Some minor refactoring

test(user-location): add missing method tests

---

javascript/components/Callout.js

Reverts react-native-mapbox-gl/maps#733
As needs to run generate script

Revert "Fix minor typo in Callout.js"

---

__tests__/components/HeatmapLayer.test.js

I grabbed a very small component to get started with contributing to this repo.
=> PR only adds 2 tests, no further changes.

test(heatmap-layer): add basic tests

---

__tests__/modules/location/locationManager.test.js
javascript/modules/location/locationManager.js

add some locationManager tests 
also some minor refactorings on `locationManager` itself
Review highly appreciated - especially on re refactorings, thanks 🙇

test(location-manager): add some

---

index.d.ts

While I was already looking into it, added some more types related to offline map packs.
See commits for further details.
I'm also thinking it would be good info to also add to the docs, but I'm still working on the formatting. May have another follow-up PR with those.

Improve types for offline map packs

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/annotation/RCTMGLPointAnnotationManager.java

Fixed RN 0.60 compat with compatible receiveComamnd

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.java
docs/MapView.md
docs/docs.json
example/src/examples/CompassView.js
example/src/scenes/Home.js
javascript/components/MapView.js

Implemented compass position for Android

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/annotation/RCTMGLPointAnnotation.java

Fixed screen point for android annotation drag event

---

example/src/examples/UserLocationChange.js
javascript/utils/animated/AnimatedPoint.js

This PR fixes an issue where the app crashes in some situations, as the location is updated.
Closes: #772

fix user location crash on location update

---

__tests__/components/Camera.test.js
android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/RCTMGLCamera.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/RCTMGLCameraManager.java
docs/Camera.md
index.d.ts
javascript/components/Camera.js

This pr adds pitch support for android and adds typings for the animated namespace

feat: add Animated Typings and fix error where pitch could not be set for android

---

javascript/components/Images.js

In Images nativeAssetImages were ignored unless images was also specified

Allow nativeAssetImages without images

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleValue.java
docs/BackgroundLayer.md
docs/Callout.md
docs/CircleLayer.md
docs/FillExtrusionLayer.md
docs/FillLayer.md
docs/HeatmapLayer.md
docs/Light.md
docs/LineLayer.md
docs/RasterLayer.md
docs/SymbolLayer.md
docs/docs.json
example/src/examples/BugReportExample.js
ios/RCTMGL/RCTMGLStyleValue.m
javascript/components/Callout.js
scripts/autogenHelpers/DocJSONBuilder.js
scripts/templates/component.md.ejs

Added docs to transition and unifed to milliseconds with default values

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/images/RCTMGLImages.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/components/images/RCTMGLImagesManager.java

Fixes: #813
Images#image propery refresh was not propagated images were only added to style on onImageMissing only.

Images: add image if new key in images hash

---

android/rctmgl/build.gradle

Fixes: #834 
Upgrade to android 9.1.0
https://github.com/mapbox/mapbox-gl-native-android/releases/tag/android-v9.1.0

Upgrade Android to mapbox 9.1.0

---

.travis.yml
android/rctmgl/build.gradle
example/ios/Podfile
example/ios/RNMapboxGLExample.xcodeproj/project.pbxproj
example/ios/RNMapboxGLExample.xcodeproj/xcshareddata/xcschemes/RNMapboxGLExample-tvOS.xcscheme
example/ios/RNMapboxGLExample.xcodeproj/xcshareddata/xcschemes/RNMapboxGLExample.xcscheme
ios/RCTMGL/MGLOfflineModule.m
ios/RCTMGL/RCTMGLCamera.h
ios/RCTMGL/RCTMGLImages.m
ios/RCTMGL/RCTMGLLayer.m
ios/RCTMGL/RCTMGLLocationManager.m
ios/RCTMGL/RCTMGLMapView.h
ios/RCTMGL/RCTMGLMapView.m
ios/RCTMGL/RCTMGLSource.h
ios/RCTMGL/RCTMGLSource.m
ios/RCTMGL/RCTMGLStyle.m
ios/RCTMGL/RCTMGLUtils.h
ios/RCTMGL/RCTMGLUtils.m
ios/RCTMGL/RCTMGLVectorSource.h
ios/RCTMGL/RCTMGLVectorSource.m
scripts/templates/RCTMGLStyle.m.ejs

Configure pods, so we only receive warnings from react-native-mapbox-gl.
Fix some of the warnings

Fix ios warning

---

ios/RCTMGL/RCTMGLCircleLayer.m
ios/RCTMGL/RCTMGLFillExtrusionLayer.m
ios/RCTMGL/RCTMGLFillLayer.m
ios/RCTMGL/RCTMGLHeatmapLayer.m
ios/RCTMGL/RCTMGLImageSource.m
ios/RCTMGL/RCTMGLLayer.m
ios/RCTMGL/RCTMGLLineLayer.m
ios/RCTMGL/RCTMGLRasterLayer.m
ios/RCTMGL/RCTMGLRasterSource.m
ios/RCTMGL/RCTMGLShapeSource.m
ios/RCTMGL/RCTMGLSource.h
ios/RCTMGL/RCTMGLSource.m
ios/RCTMGL/RCTMGLSymbolLayer.m

Do not crash if source cannot be resolved

---

react-native-mapbox-gl.podspec

Upgrade to ios 5.8.0
https://github.com/mapbox/mapbox-gl-native-ios/releases/tag/ios-v5.8.0

Upgrade iOS to 5.8.0

---

index.d.ts

Hey there,
first, thanks for the awesome lib!
building on @solinehayes PR (#840), I updated the TS typing of MarkerView
Fixes #829

fix: Update TS typing according to MarkerView introduction

---

ios/RCTMGL/RCTMGLLocationManager.m

Attempt to fix https://github.com/react-native-mapbox-gl/maps/issues/831

fix(ios): no update on heading change with displacement

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
ios/RCTMGL/RCTMGLMapViewManager.m

Fixes https://github.com/react-native-mapbox-gl/maps/issues/740
Used the earlier commits mentioned in the issue and the current Mapbox iOS/Android docs as a base for the changes. Tested on a local project on iOS and Android.
My first PR to this project, so please let me know if I've missed anything.

fix noop localizeLabels flag

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/annotation/RCTMGLPointAnnotation.java

Check for mMapView nil in RCTMGLPointAnnotation removeFromMap

---

example/package.json
example/src/examples/SymbolCircleLayer/ShapeSource.tsx
example/src/scenes/Home.js
example/tsconfig.json

Added a TS component to our example app, so editing/testing type definitions is easier

Ts example

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/CameraStop.java

Fixes, but only on anrdoid: #841

Fix android padding

---

ios/RCTMGL/RCTMGLPointAnnotation.m

Allow zPosition on PointAnnotation children

---

index.d.ts

This exposes the `refresh` method for PointAnnotation components

Expose refresh for PointAnnotation

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/http/CustomHeadersInterceptor.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/location/LocationManager.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLModule.java
ios/RCTMGL/MGLCustomHeaders.m

Never log user data or PII (Personal Identification Information) since other applications can access the log.
Android logs are not stripped unless using ProGuard, which not all apps use.

Don't log sensitive information

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLImageSource.java
example/src/examples/ImageOverlay.js
ios/RCTMGL/RCTMGLImageSource.m

This fixes #1013 
Additionally extends the example with a button that switches between dynamic and static coordinates.

fix(image-source): dynamically update ImageSource coordinates

---

index.d.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/react-native-mapbox-gl/maps/1050)

ShapeSourceProps.shape should accept GeoJSON.Geometry

---

javascript/components/PointAnnotation.js

Fixes refresh in PointAnnotations. See #972

Fix PointAnnotation refresh

---

example/src/examples/FlyTo.js
ios/RCTMGL/CameraUpdateItem.m

Reverts react-native-mapbox-gl/maps#1059

Revert "Make moveTo/flyTo work for coordinates with longitude/latitude of 0"

---

example/src/examples/FlyTo.js
ios/RCTMGL/CameraStop.m
ios/RCTMGL/CameraUpdateItem.m

Fix is coord valid

---

ios/RCTMGL/CameraStop.m

Set initial bounds to invalid instead of 0,0,0,0

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/CameraStop.java

Android edge padding limit to view size

---

ios/RCTMGL/RCTMGLBackgroundLayer.m
ios/RCTMGL/RCTMGLCircleLayer.m
ios/RCTMGL/RCTMGLFillExtrusionLayer.m
ios/RCTMGL/RCTMGLFillLayer.m
ios/RCTMGL/RCTMGLHeatmapLayer.m
ios/RCTMGL/RCTMGLLayer.h
ios/RCTMGL/RCTMGLLayer.m
ios/RCTMGL/RCTMGLLight.m
ios/RCTMGL/RCTMGLLineLayer.m
ios/RCTMGL/RCTMGLMapView.m
ios/RCTMGL/RCTMGLRasterLayer.m
ios/RCTMGL/RCTMGLStyle.h
ios/RCTMGL/RCTMGLStyle.m
ios/RCTMGL/RCTMGLSymbolLayer.m
scripts/templates/RCTMGLStyle.h.ejs
scripts/templates/RCTMGLStyle.m.ejs

iOS: Fixed race condition in setting an image and closing the map

---

index.d.ts

add types for textVariableAnchor & textRadialOffset

---

docs/Camera.md
docs/docs.json
javascript/components/Camera.js

* remove unnecessary/ obsolete props/ methods
* update docs

refactor(camera): alignment and docs

---

example/ios/RNMapboxGLExample.xcodeproj/project.pbxproj
example/package.json

Upgrade these two deps in tandem.
closes #1160
closes #1147

upgrade react-native 0.63.4 and metro 0.64

---

.github/dependabot.yml

decrease the interval of updates

build(dependabot): decrease schedule interval

---

__tests__/components/UserLocation.test.js
android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/RCTMGLCamera.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/events/LocationEvent.java
index.d.ts
ios/RCTMGL/RCTMGLLocation.m

This PR fixes the issue described in https://github.com/react-native-mapbox-gl/maps/issues/1213.
_Edit ferdicus:_
resolves #1213

Add course to the location event

---

example/package.json

Adding some scripts that I found myself using often when testing on the `example` app.

feat(build): add some convenience scripts

---

react-native-mapbox-gl.podspec

Make post-install noop

---

example/.gitattributes
example/.prettierrc.js
example/android/app/build.gradle
example/android/app/src/debug/AndroidManifest.xml
example/android/app/src/main/AndroidManifest.xml
example/android/app/src/main/res/values/styles.xml
example/android/build.gradle
example/android/gradle.properties
example/android/gradle/wrapper/gradle-wrapper.properties
example/android/gradlew.bat
example/ios/Podfile
example/ios/RNMapboxGLExample.xcodeproj/project.pbxproj
example/ios/RNMapboxGLExample.xcodeproj/xcshareddata/xcschemes/RNMapboxGLExample.xcscheme
example/ios/RNMapboxGLExample/AppDelegate.m
example/ios/RNMapboxGLExample/Info.plist
example/ios/RNMapboxGLExample/LaunchScreen.storyboard
example/metro.config.js
example/package.json
example/scripts/fix_nvm_issue.js

Upgrading the example app to react-native 0.64.1 based on [upgrade react native](https://react-native-community.github.io/upgrade-helper/?from=0.63.4&to=0.64.1)

build(example): upgrade rn 0.64.1

---

CHANGELOG.md
android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.java
docs/MapView.md
docs/docs.json
index.d.ts
ios/RCTMGL/RCTMGLMapView.h
ios/RCTMGL/RCTMGLMapView.m
ios/RCTMGL/RCTMGLMapViewManager.m
javascript/components/MapView.js

Added logoPosition props to `MapView` that allows to position the Mapbox logo

Added logoPosition props that allows to position the Mapbox logo

---

docs/Camera.md
docs/docs.json
javascript/components/Camera.js

`onUserTrackingModeChange` was wrongly scoped under `bounds`...

docs(camera): update documentation for onUserTrackingModeChange

---

README.md
example/.gitignore

PR adds `example/ios/Podfile` to gitignore 
and fixes minor points in root `README`
* Android ~Simulator~ => Emulator
* replace npm with yarn in comments regarding yarn
not applicable
not applicable

chore(example): add podfile to gitignore

---

docs/CustomHttpHeaders.md

Wrong order of lines of code in AppDelegate.m

Fix mistake in CustomHttpHeaders.md

---

docs/docs.json
javascript/modules/offline/offlineManager.js

Update offlineManager.js docs

---

docs/StyleSheet.md

missing comma
No issue Id , just README.MD

fix(comma): add comma

---

android/rctmgl/src/main/java/com/mapbox/rctmgl/components/annotation/MarkerViewManager.java
android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java

android fix for issue #1546 
update every marker in onCameraMove event at MapView.

fix(android):update MarkerView position on camera move

---

rnmapbox-maps.podspec
scripts/autogenerate.js

rename, and warning fixes to `.podspec`

Podspec rename + warning fixes

---

docs/BackgroundLayer.md
docs/CircleLayer.md
docs/FillExtrusionLayer.md
docs/FillLayer.md
docs/HeatmapLayer.md
docs/Light.md
docs/LineLayer.md
docs/RasterLayer.md
docs/SkyLayer.md
docs/SymbolLayer.md
scripts/templates/component.md.ejs

Fixed links in docs

---

android/install.md

Shouldn`t it be "any changes" instead of "and changes"?
Documentation review

Spelling check

---

.github/workflows/ios-actions.yml
CHANGELOG.md
example/ios/Podfile.lock
example/ios/RNMapboxGLExample.xcodeproj/project.pbxproj

Changelog update and podfile update

---

android/rctmgl/build.gradle
rnmapbox-maps.podspec

Change default v10 version 10.4.0 (from 10.3.0)

On V10 default to 10.4.0

---

README.md

Changed completeded to completed
Fixes spelling mistake in the Readme file.
- [ NA ] I have tested this on a device/simulator for each compatible OS
- [ NA ] I formatted JS and TS files with running `yarn lint:fix` in the root folder
- [ NA ] I updated the documentation with running `yarn generate` in the root folder
- [ NA ] I mentioned this change in `CHANGELOG.md`
- [ NA ] I updated the typings files (`index.d.ts`)
- [ NA ] I added/ updated a sample (`/example`)

Fixed spelling mistake.

---

.gitignore
ios/RCTMGL/RCTMGLStyle.m
plugin/build/withMapbox.d.ts
plugin/build/withMapbox.js
plugin/src/__tests__/__snapshots__/withMapbox-test.ts.snap
plugin/src/__tests__/withMapbox-test.ts
plugin/src/withMapbox.ts
scripts/autogenHelpers/globals.js
scripts/autogenerate.js

- Add RNMapboxMapsImpl to expo plugin (iOS only for now)
- Add prebuilt expo plugin to GitHub so it can be used from GitHub
- Add expo build compile to `yarn generate`

Add RNMapboxMapsImpl to expo plugin

---

android/rctmgl/build.gradle
plugin/build/withMapbox.d.ts
plugin/build/withMapbox.js
plugin/src/withMapbox.ts

Expo android plugin:
Config arguments;
- RNMapboxMapsImpl (mapbox,mapblire,mapbox-gl)
- RNMapboxMapsDownloadToken token to download mapbox libs

Expo plugin android

---

package.json

Use npm for prepare script

---

ios/RCTMGL-v10/RCTMGLCamera.swift
ios/RCTMGL-v10/RCTMGLEvent.swift
ios/RCTMGL-v10/RCTMGLMapView.swift
ios/RCTMGL-v10/RCTMGLSource.swift
ios/RCTMGL-v10/RCTMGLStyleValue.swift

v10/iOS:
- implement SourceLayer#onPress
- defaultStop for camera

Implement SourceLayer#onPress, defaultStop for camera

---

ios/RCTMGL-v10/RCTMGLMapView.swift

handle styleloaded components directly after style loaded
Closes: #1842

Pass map loaded error to RN,

---

CHANGELOG.md
android/install.md
android/rctmgl/build.gradle
ios/install.md
rnmapbox-maps.podspec

Update mapbox sdk to 10.4.3 on iOS and 10.4.1 on android

iOS: Mapbox v10.4.3, android: Mapbox v10.4.1

---

ios/RCTMGL-v10/RCTMGLBackgroundLayer.swift
ios/RCTMGL-v10/RCTMGLCircleLayer.swift
ios/RCTMGL-v10/RCTMGLFillExtrustionLayer.swift
ios/RCTMGL-v10/RCTMGLFillLayer.swift
ios/RCTMGL-v10/RCTMGLHeatmapLayer.swift
ios/RCTMGL-v10/RCTMGLLayer.swift
ios/RCTMGL-v10/RCTMGLRasterLayer.swift
ios/RCTMGL-v10/RCTMGLSkyLayer.swift
ios/RCTMGL-v10/RCTMGLSymbolLayer.swift

Refactor #1848
- `apply` applies changes made to  `self.styleLayer` to the style
- `optionsChanged` will set and apply changes in filter, minZoomLevel, maxZoomLevel, etc. to the style and then calls `apply` to apply changes to the style.

Refactor setOptions

---

.github/workflows/android-actions.yml
.github/workflows/ios-actions.yml
.github/workflows/on-push.yml

Reverts rnmapbox/maps#1865
See https://github.com/rnmapbox/maps/pull/1865#issuecomment-1109732146

Revert "chore: Set permissions for GitHub actions"

---

ios/RCTMGL-v10/DefaultStringInterpolation+optional.swift
ios/RCTMGL-v10/RCTMGLFillLayer.swift
ios/RCTMGL-v10/RCTMGLLayer.swift
ios/RCTMGL-v10/RCTMGLLogging.swift
ios/RCTMGL-v10/RCTMGLMapView.swift
ios/RCTMGL-v10/RCTMGLStyle.swift
scripts/templates/RCTMGLStyle.swift.ejs

Also added `optional:` for logging optional values without warning

Convert try! to logging in setSourceVisibility

---

android/rctmgl/build.gradle
example/ios/Podfile.lock
rnmapbox-maps.podspec

Upgrade to 10.5.0

---

ios/RCTMGL-v10/RCTMGLMapViewManager.m
ios/RCTMGL-v10/RCTMGLMapViewManager.swift

Added getCenter to iOS, v10 implementation

iOS, v10: added getCenter

---

ios/RCTMGL-v10/MGLModule.swift
ios/RCTMGL-v10/RCTMGLEvent.swift
ios/RCTMGL-v10/RCTMGLMapView.swift
ios/RCTMGL-v10/RCTMGLRasterLayer.swift
ios/RCTMGL-v10/RCTMGLStyleValue.swift

v10, iOS:
- Implemented more callbacks:
- DidFinishLoadingStyle
- DidFinishLoadingMap
- DidFinishRenderingFrameFully
- DidFinishRenderingFrame
- Fixed lot of unimplemented style values

iOS,v10: more callbacks, style values

---

ios/RCTMGL-v10/RCTMGLMapViewManager.m
ios/RCTMGL-v10/RCTMGLMapViewManager.swift
ios/RCTMGL-v10/RCTMGLSource.swift

iOS, v10:
- Remove source if view is removed and we created the source
- add `getZoom` to mapView

[iOS,v10] Remove source if view is removed

---

ios/RCTMGL-v10/RCTMGLLayer.swift

In a layer declaration `id` can refer to en existing layer.  See #425
This way we can change visibility of layers in the base style.
```jsx
<FillLayer id="building" style={{visibility: "none"}} />
```
In pre `v10` there we only set the sourceID on creation of a layer. But `v10` api allows to set `sourceID`-s after creation. 
Since we set `sourceID` to `composite` by default. The above example declaration would change sourceID of `building` which is not what anyone wants.
https://github.com/rnmapbox/maps/blob/4cf828180651b49e0847dedba6efcd5eea00e051/javascript/components/FillLayer.js#L77-L79
I'm planning to do the following changes related to this:
1.) introduce an `existing` property at layer declaration, so it's more explicit if we want to create a new layer or if we want to just change …

do not set default source id for existing layers

---

android/rctmgl/src/main/java-mapboxgl/common/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
android/rctmgl/src/main/java-mapboxgl/common/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.java

Fix: https://github.com/rnmapbox/maps/pull/1936#issuecomment-1139697492, see https://github.com/rnmapbox/maps/pull/1936#issuecomment-1139815319
Closes: #1938

android, mapbox-gl,maplibre: Fix receiveCommand for setCommandHandler

---

ios/RCTMGL-v10/RCTMGLCamera.swift
ios/RCTMGL-v10/RCTMGLMapView.swift

Fixes:  #1964
Fixes the following issues:
- allow to add components after style finished loading
- readd components when styleUrl is changed (reload)
- remove deferred components

Add components when style already loaded + reloaded, also fix remove

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/styles/sources/RCTMGLShapeSource.kt
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/styles/sources/RCTMGLShapeSourceManager.kt

v10, android: implement new cluster functions

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/images/RCTMGLImages.kt

v10,android: Fix download image task

---

.github/workflows/on-push.yml

Try to fix actions on main:
https://github.com/rnmapbox/maps/runs/6841702624?check_suite_focus=true

Use setup-node@v3

---

.eslintrc.js
__tests__/interface.test.js
setup-jest.js

add setWellKnownTileServer to jest

---

ios/RCTMGL/MGLOfflineModule.m

iOS,gl: call requestProgress if pack state is unknown

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.kt

Add implementation of map view queryRenderedFeaturesAtPoint for java-v10

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.kt

Implemented missing queryRenderedFeaturesInRect method for android v10

implemented queryRenderedFeaturesInRect method (android, v10)

---

android/install.md
android/rctmgl/build.gradle
example/Gemfile.lock
example/ios/Podfile.lock
example/ios/RNMapboxGLExample.xcodeproj/project.pbxproj
ios/install.md
rnmapbox-maps.podspec

Bumped mapbox version to 10.6.0 for android and ios

bumped mapbox version to 10.6.0 for ios and android

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.kt
ios/RCTMGL-v10/RCTMGLMapView.swift

Implement compassPosition, Margins on android,v10.
Support there properties on android,v10:
- compassEnabled
- compassViewPosition
- compassViewMargins
- compassPosition
also fixes compassViewPosition on iOS

feat(android,v10): compass position

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.kt

Added attribution and logo positioning for mapbox v10 implementation android
```
logoPosition={{ top: 0, right: 100 }}
attributionPosition={{ bottom: 50, left: 100 }}
```

[Android:V10] Add attribution and logo position handling

---

ios/RCTMGL-v10/RCTMGLMapView.swift

Fixes #2062
Add nil check when adding/removing map subviews to avoid crash

iOS: Fix crash when adding/removing map subview

---

ios/RCTMGL-v10/MGLModule.swift
ios/RCTMGL-v10/RCTMGLOfflineModule.swift

fix(ios,v10): fix offline packs enumeration after app reload

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/modules/RCTMGLOfflineModule.kt

Fixes #[2073](https://github.com/rnmapbox/maps/issues/2073)

implement android offlineManager.deletePack for v10

---

__tests__/modules/offline/offlineManager.test.js
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/modules/RCTMGLOfflineModule.kt
docs/OfflineManager.md
docs/docs.json
index.d.ts
ios/RCTMGL-v10/RCTMGLOfflineModule.m
ios/RCTMGL-v10/RCTMGLOfflineModule.swift
javascript/modules/offline/offlineManager.js
setup-jest.js

Added the migrate function for iOS and Android from the official Mapbox 'Migrate to v10' guides

Feature: Migration for offline cache (v10)

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/styles/sources/RCTMGLShapeSourceManager.kt
ios/RCTMGL-v10/MGLModule.swift
ios/RCTMGL-v10/RCTMGLOfflineModule.swift
ios/RCTMGL/MGLModule.m

Fix `Unkown` => `Unknown` typo and export `Unknown` constant on Mapbox/iOS version

fix(ios): add Unknown to OfflinePackDownloadState

---

android/rctmgl/build.gradle
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.kt
javascript/index.js

Fixes: #1932
feat(v10,android): upgrade to mapbox 1.7.0

fix(android,v10): fix getVisibleBounds, bounds in regionDidChange

---

ios/RCTMGL-v10/RCTMGLMapViewManager.swift

fix(ios,v10): added call to setHandledMapChangedEvents resolver

---

ios/RCTMGL-v10/RCTMGLStyleValue.swift

Return correct value for transition
Fixes: #2102

fix(v10,ios): implement transition style values

---

ios/RCTMGL-v10/RCTMGLNativeUserLocation.swift

Native render mode now works on iOS.

fix(ios,v10): fix native location indicator

---

ios/RCTMGL-v10/RCTMGLOfflineModule.swift

fix(ios,v10,offline): send errors to error listener not to promise rejecter

---

.gitignore
example/android/app/build.gradle
example/android/app/src/main/java/com/rnmapboxglexample/MainActivity.java
example/android/app/src/main/java/com/rnmapboxglexample/newarchitecture/MainApplicationReactNativeHost.java
example/android/app/src/main/jni/Android.mk
example/android/build.gradle
example/android/settings.gradle
example/ios/.xcode.env
example/ios/Podfile
example/ios/Podfile.lock
example/ios/RNMapboxGLExample.xcodeproj/project.pbxproj
example/ios/RNMapboxGLExample/AppDelegate.mm
example/package.json

chore(example): upgrade rn in example to 0.69.4

---

example/android/app/build.gradle
example/ios/Podfile.lock
example/package.json
ios/RCTMGL-v10/RCTMGLOfflineModule.swift
plugin/build/withMapbox.js
scripts/autogenerate.js

chore(example): fix example on android, fix offline pack latitude on ios

---

.github/workflows/ios-actions.yml
example/ios/Podfile
example/ios/Podfile.lock
example/package.json
rnmapbox-maps.podspec

Upgrade to macOS-12 to see if timeout errors with detox builds gets better

chore(actions): Upgrade to macos-12

---

CHANGELOG.md
README.md

Add information about `transforIgnorePatterns` so that the setup.js is transformed to avoid the following error:
```
● Test suite failed to run
Jest encountered an unexpected token
Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.
Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.
By default "node_modules" folder is ignored by transformers.
Here's what you can do:
• If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
• If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
• To have some of …
```

Update jest readme instruction for v10

---

javascript/web/MapContext.js
javascript/web/MapContext.ts
javascript/web/components/Camera.tsx
javascript/web/components/MapView.tsx
package.json

fix(web): fix lint errors

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt

Fixes onDrag, onDragEnd, and onDragStart not firing on Android (v10)

Fix: Point Annotation onDrag event callbacks (Android v10)

---

.husky/pre-commit
package.json

Properly upgrade to husky v8 as [described here](https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v8).

Upgrade husky to v8

---

example/src/examples/BugReportExampleTS.tsx
example/src/scenes/GroupAndItem.tsx
index.d.ts

Add a separate BugReportExampleTS done in TS.

chore(ts): add separate bugreport exmple with ts

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/camera/CameraStop.kt
example/package.json
example/src/scenes/GroupAndItem.tsx

Fixes: #2170
Android:
iOS:
Component used for testing:
```typescript
import React, { useRef } from 'react';
import { Button, StyleSheet, View } from 'react-native';
import { MapView, Camera, ShapeSource, LineLayer } from '@rnmapbox/maps';
import bboxPolygon from '@turf/bbox-polygon';
const ne = [30.382347106933594, 59.9522034];
const sw = [30.4136494, 59.98061460864758];
const polygon = bboxPolygon([sw[0], sw[1], ne[0], ne[1]]);
const BugReport = () => {
const camera = useRef<Camera>(null);
return (
<View
style={{
flex: 1,
alignItems: 'center',
justifyContent: 'flex-end',
paddingBottom: 40,
}}
>
<MapView style={{ ...StyleSheet.absoluteFillObject }}>
<Camera
ref={camera}
defaultSettings={{
bounds: {
ne: [29.87488244318364, 59.68250669940879],
sw: [30.952489630943578, 60.22209891764351],
}, …
```

fix(v10,android,camera): fix padding

---

android/install.md

This change is a simple update to the android installation documentation.

Updated type in android install documentation

---

README.md

I added a functional component example to the `README.md `and simplified the styles within the class component example. Specifically removing the background colors. Concerning the checklist below, I did not think this small change was worth adding to the `CHANGELOG`, but if ye moderators of this repository deem otherwise I would be more than happy to add it. As for the last two checkboxes I didn't touch anything concerning types nor samples, hence why I left them unchecked. 
https://user-images.githubusercontent.com/76987846/188775442-7f3e2e15-58ae-4dfb-99fa-17b7fc8c5b88.mov

adds functional component example and simplifies styles for class component

---

ios/RCTMGL-v10/RCTMGLCamera.swift

Fixes user tracking mode on iOS v10

Fix: iOS v10 user tracking mode

---

android/rctmgl/build.gradle
example/ios/Podfile.lock
ios/install.md
rnmapbox-maps.podspec

Upgrade native mapbox libraries for v10

chore(v10): upgrade mapbox v10 on android to 10.8.0 and 10.8.1 on ios

---

ios/RCTMGL-v10/RCTMGLMapView.swift
ios/RCTMGL-v10/RCTMGLPointAnnotation.swift

fix(v10,ios,pointannotation): refresh annotation on coordinate update

---

.github/workflows/ios-actions.yml
ios/RCTMGL-v10/RCTMGLImages.swift
ios/RCTMGL-v10/RCTMGLMapView.swift

fix(ios,v10): "isUserInteraction" always is "false"

---

ios/RCTMGL-v10/RCTMGLCamera.swift

refactor(iOS, v10): remove unneeded changePadding from camera

---

android/rctmgl/src/main/java-mapboxgl/common/com/mapbox/rctmgl/components/camera/CameraStop.java
android/rctmgl/src/main/java-mapboxgl/common/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
android/rctmgl/src/main/java-mapboxgl/common/com/mapbox/rctmgl/modules/RCTMGLSnapshotModule.java
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/camera/CameraStop.kt
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/modules/RCTMGLSnapshotModule.java

fix(android): used density instead of scaledDensity

---

ios/RCTMGL-v10/RCTLog.swift
ios/RCTMGL-v10/RCTMGLMapViewManager.swift
ios/RCTMGL-v10/RCTMGLShapeSourceManager.swift
ios/RCTMGL-v10/RCTMGLUtils.swift
ios/RCTMGL-v10/RCTMGLVectorLayer.swift

Replace RCTLog with RCTMGLLog to resolve naming conflict

---

docs/PointAnnotation.md
docs/docs.json
javascript/components/AbstractLayer.tsx
javascript/components/PointAnnotation.tsx
javascript/utils/index.d.ts
scripts/autogenHelpers/DocJSONBuilder.js

chore: fix ts issue + doc gen updates

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/annotation/RCTMGLMarkerView.kt

Workaround for: https://github.com/mapbox/mapbox-maps-android/issues/1723

fix(android,v10): fix marker view crash on marker view removal

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/camera/CameraStop.kt
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/styles/RCTMGLStyle.kt

fix(v10,android): fix padding order

---

ios/RCTMGL-v10/RCTMGLMapView.swift

fix(ios,v10): MapView onPress should be not called for touches on MarkerView

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/modules/CustomHttpHeaders.kt
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/modules/RCTMGLModule.kt

feat(android,v10): implement CustomHeaders

---

ios/RCTMGL-v10/RCTMGLMapView.swift

Fixes: #2286 
tap was called from mapbox's annotationMan

fix(ios,v10): PointAnnotation onSelect was called twice

---

docs/docs.json
ios/RCTMGL-v10/RCTMGLShapeSource.swift
ios/RCTMGL-v10/RCTMGLShapeSourceManager.m
ios/RCTMGL-v10/RCTMGLShapeSourceManager.swift
javascript/components/MarkerView.tsx
javascript/components/ShapeSource.tsx

fix(ios,v10): fix getClusterExpansionZoom to accept featureJSON

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.kt
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/utils/extensions/CoordinateBounds.kt

WIP only, somehow position doesn't seems to work correctly...

refactor(v10,andorid): make logic common for logo and compass settings

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.kt

feat(android,v10): ScaleBar: Allow user to show in Android v10

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/camera/RCTMGLCamera.kt
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.kt
ios/RCTMGL-v10/RCTMGLCamera.swift

feat(v10,android): implement min/maxZoomLevel for android/v10

---

javascript/components/MarkerView.tsx

Fixes [this comment](https://github.com/rnmapbox/maps/commit/c9403765efabd85f063241d93ee3f13ecb6a945b#commitcomment-87041050)

Remove leftover console logs

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt

Align Android toGravity with iOS toOrnamentPosition

---

ios/RCTMGL-v10/RCTMGLMapView.swift

Basic cleanup:
- Update deprecated syntax
- Remove unused code

MapView cleanup & deprecation fixes

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt

Fix: Unable to set styleURL in android version

fix setting styleURL for android

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt
javascript/components/SymbolLayer.tsx

Fixes #2312 
This change fixes SymbolLayer.tsx type checking in projects with `@types/react` installed.

Add stronger type checking to SymbolLayer.tsx children

---

android/rctmgl/build.gradle
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/styles/RCTMGLStyleFactory.java
docs/FillExtrusionLayer.md
docs/docs.json
example/ios/Podfile.lock
ios/RCTMGL-v10/RCTMGLStyle.swift
javascript/utils/MapboxStyles.ts
javascript/utils/styleMap.ts
rnmapbox-maps.podspec
scripts/autogenerate.js
style-spec/v8.json

feat(v10): upgrade to 10.9.0

---

ios/RCTMGL-v10/MGLModule.m
ios/RCTMGL-v10/MGLModule.swift

feat(v10, ios): setTelemetryEnabled
fix(v10,ios): fix LineJoin on iOS
Fixes: #2010
Fixes: #2326 
Closes: #2327

feat(v10, ios): setTelemetryEnabled

---

android/rctmgl/src/main/java-mapboxgl/common/com/mapbox/rctmgl/modules/RCTMGLModule.java
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/modules/RCTMGLModule.kt
index.d.ts
ios/RCTMGL-v10/MGLModule.swift
ios/RCTMGL/MGLModule.m

change setaccesstoken to return a promise

---

index.d.ts
ios/RCTMGL-v10/MGLModule.m
ios/RCTMGL-v10/MGLModule.swift

fix(ts): added TileServers, OfflinePackDownloadState to ts

fix: add v10 ios setWellKnownTileServer

---

ios/RCTMGL-v10/RCTMGLCamera.swift
ios/RCTMGL-v10/RCTMGLInteractiveElement.swift
ios/RCTMGL-v10/RCTMGLMapView.swift

fix(v10,ios): fix leaked RCTMLGMapView caused by strong retain cycles

---

ios/RCTMGL-v10/RCTMGLCircleLayer.swift
ios/RCTMGL-v10/RCTMGLInteractiveElement.swift
ios/RCTMGL-v10/RCTMGLLayer.swift
ios/RCTMGL-v10/RCTMGLSource.swift
ios/RCTMGL-v10/RCTMGLVectorLayer.swift

Layers were kept in RN-s registeredViews so it was leaking as well.

fix(ios,v10): fix leaking layers, and smaller refactorings

---

ios/RCTMGL-v10/RCTMGLCamera.swift
ios/RCTMGL-v10/RCTMGLImages.swift
ios/RCTMGL-v10/RCTMGLLayer.swift
ios/RCTMGL-v10/RCTMGLLocationModule.swift
ios/RCTMGL-v10/RCTMGLMarkerView.swift
ios/RCTMGL-v10/RCTMGLPointAnnotation.swift
ios/RCTMGL-v10/RCTMGLSingletonLayer.swift

Fixed additional vars that should be weak

v10 iOS: Fix additional memory leaks

---

plugin/build/withMapbox.js
plugin/src/withMapbox.ts

`addMapboxMavenRepo` was inserting at the wrong position

Fixed expo plugin for android

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/annotation/RCTMGLMarkerViewManager.kt
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt

fix(v10,android): show up markerview on mapbox android 10.9+

---

plugin/build/withMapbox.d.ts
plugin/build/withMapbox.js
plugin/src/__tests__/__snapshots__/withMapbox-test.ts.snap
plugin/src/__tests__/fixtures/buildGradleFiles.ts
plugin/src/__tests__/withMapbox-test.ts
plugin/src/withMapbox.ts

Fixes #2393
- Test cases added for android.

fix(v10,android) Broken build.gradle plugin patching

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt

fix(v10, android): fix getCoordinateFromView

---

android/rctmgl/build.gradle
example/ios/Podfile.lock
rnmapbox-maps.podspec

feat(v10): upgrade to 10.9.1

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/utils/extensions/CoordinateBounds.kt

fix(android,v10): fix getVisibleBounds format

---

package.json
plugin/build/generateCode.d.ts
plugin/build/generateCode.js
plugin/build/withMapbox.js
plugin/src/generateCode.ts
plugin/src/withMapbox.ts

Fixes #2389
I'v successfully built with our expo project.

Include private Expo generateCode

---

ios/RCTMGL-v10/RCTMGLStyle.swift
scripts/templates/RCTMGLStyle.swift.ejs

Removed try! and added logged when setting Pattern, etc after image has downloaded

removed try! and added logging to image url setters

---

ios/RCTMGL-v10/MGLModule.swift
ios/RCTMGL-v10/RCTMGLAtmosphere.swift
ios/RCTMGL-v10/RCTMGLCircleLayer.swift
ios/RCTMGL-v10/RCTMGLEvent.swift
ios/RCTMGL-v10/RCTMGLFillExtrustionLayer.swift
ios/RCTMGL-v10/RCTMGLFillLayer.swift
ios/RCTMGL-v10/RCTMGLHeatmapLayer.swift
ios/RCTMGL-v10/RCTMGLMapView.swift
ios/RCTMGL-v10/RCTMGLRasterLayer.swift
ios/RCTMGL-v10/RCTMGLSymbolLayer.swift
ios/RCTMGL-v10/RCTMGLTerrain.swift

fix(iOS,v10): reactStyle, in addStyles implement willStartLoadingMap

---

android/rctmgl/src/main/java-mapboxgl/common/com/mapbox/rctmgl/components/styles/RCTMGLStyleFactory.java
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/styles/RCTMGLStyleFactory.java
docs/BackgroundLayer.md
docs/FillExtrusionLayer.md
docs/FillLayer.md
docs/LineLayer.md
docs/docs.json
ios/RCTMGL-v10/RCTMGLStyle.swift
ios/RCTMGL/RCTMGLStyle.h
ios/RCTMGL/RCTMGLStyle.m
javascript/utils/MapboxStyles.d.ts
javascript/utils/styleMap.ts
scripts/autogenHelpers/globals.js
style-spec/v8.json

chore: update v8.json, fix type for iconTranslateAnchor, etc.

---

ios/RCTMGL-v10/RCTMGLLocationModule.swift

If update comes from heading use the heading timestamp

fix(iOS,v10): use timestamp from heading if update was from heading

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt

This merge request only applies to Android-specific codebase. Makes sure that the features list returned by the queryRenderedFeatureAtPoint method is not empty, if the user doesn't provide any value into the layerIDs parameter.
In addition, the previous implementation was making use of a deprecated method of the Mapbox SDK for Android. This is not the case anymore.
Fixes no known issues
This MR doesn't require any screenshot or video, because it simply makes sure that the data returned by the native method implementation is not an empty list, also when the expected result is not empty.

fix queryRenderedFeaturesAtPoint Android

---

ios/RCTMGL-v10/RCTMGLMapView.swift

fix(ios,v10): fix compassViewPosition

---

ios/RCTMGL-v10/RCTMGLMapView.swift
ios/RCTMGL-v10/RCTMGLPointAnnotation.swift

fix(ios,v10): fix point annotation drag events with 10.10 or later

---

ios/RCTMGL-v10/RCTMGLMapView.swift
ios/RCTMGL-v10/RCTMGLPointAnnotation.swift
ios/RCTMGL-v10/RCTMGLPointAnnotationManager.m

fix(ios,v10): fix point annotation anchor

---

ios/RCTMGL-v10/RCTMGLMarkerView.swift

Fix: Mapbox error [MarkerView] Error updating annotation when the list of marker changes

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/modules/RCTMGLLocationModule.kt
docs/OfflineManager.md
docs/docs.json
ios/RCTMGL-v10/RCTMGLOfflineModule.swift
javascript/modules/offline/offlineManager.js

Implement progress event throttle for iOS.

fix(ios, v10, offline): implement progress event throttling

---

example/src/examples/Map/CreateOfflineRegion.js
ios/RCTMGL-v10/RCTMGLLogging.swift
ios/RCTMGL-v10/RCTMGLOfflineModule.swift

and store nessesary data in metadata/_rnmapbox

feat(v10,ios,offile): implement offline resume for v10 

---

javascript/modules/location/locationManager.js

Location Manager Object Initialisation removed

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/annotation/RCTMGLMarkerView.kt

fix: Markers disappear on Android

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/modules/CustomHttpHeaders.kt

Fixes #2568 
Tested on Android
Not required
Not required
It's a networking hotfix only

fix(v10,android): Android Custom HTTP Headers

---

android/rctmgl/build.gradle
example/ios/Podfile.lock
ios/install.md
rnmapbox-maps.podspec

feat(v10): upgrade mapbox to 10.11.0

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/camera/RCTMGLCamera.kt
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/location/LocationComponentManager.kt
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.kt
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocationManager.kt
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/location/LocationManager.kt

feat(v10,android): rework location manager to provide bearing arrow

---

index.d.ts
javascript/modules/location/locationManager.ts

Export type `Location` and `Coordinates`.

chore: export Location and Coordinates type

---

javascript/components/annotations/Annotation.js

fix: crash when animated prop changes in Annotation.js

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/styles/layers/RCTLayer.kt
index.d.ts
javascript/components/AbstractLayer.tsx
javascript/components/AbstractSource.tsx
javascript/components/Atmosphere.tsx
javascript/components/Images.tsx
javascript/components/PointAnnotation.tsx
javascript/components/Terrain.tsx
javascript/types/BaseProps.ts
javascript/utils/MapboxStyles.d.ts
scripts/templates/MapboxStyles.ts.ejs

fix(ts): allow string (url or imageName) for images & add BasePorps with testID

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/camera/CameraStop.kt

Fixes #2339
https://user-images.githubusercontent.com/18724559/223556338-7c28fe0a-a5ce-4099-ba53-646e6b52284b.mp4
Example used:
```tsx
import React, { useRef, useState } from 'react';
import { Button, View } from 'react-native';
import MapboxGL, {
Camera,
CircleLayer,
MapView,
ShapeSource,
import { Point, Polygon } from 'geojson';
import FillLayer = MapboxGL.FillLayer;
const CENTER_POINT: Point = { type: 'Point', coordinates: [8.5, 50.5] };
const BOUNDS: Polygon = {
type: 'Polygon',
coordinates: [
[
[9.0, 50.0],
[8.0, 50.0],
[8.0, 51.0],
[9.0, 51.0],
[9.0, 50.0],
],
],
};
};
const BugReportExample = () => {
const cameraRef = useRef<Camera>(null);
const [mode, setMode] = useState<'center' | 'bounds'>('center');
const [padding, …
```

fix(android,v10): setCamera padding with center

---

ios/RCTMGL-v10/RCTMGLMapView.swift

fix(ios,v10): try to get source wich has highest layer associated

---

README.md
docs/Images.md
docs/docs.json
example/src/examples/SymbolCircleLayer/SdfIcons.tsx
ios/RCTMGL-v10/RCMTGLImage.swift
ios/RCTMGL-v10/RCTMGLImages.swift
ios/RCTMGL-v10/RCTMGLUtils.swift
javascript/Mapbox.ts
javascript/components/Images.tsx

Fixes: #2497 
Implement stretchable images in iOS:
```jsx
import { View } from 'react-native';
import Mapbox, { type ImageEntry } from '@rnmapbox/maps';
import sheet from '../../styles/sheet';
import exampleIcon from '../../assets/example.png';
import { BaseExampleProps } from '../common/BaseExamplePropTypes';
import Page from '../common/Page';
icon: {
iconImage: ['get', 'icon'],
iconColor: ['get', 'color'],
textField: ['get', 'name'],
iconTextFit: 'both',
iconSize: [
'match',
['get', 'icon'],
'example',
1.2,
'airport-15',
1.2,
/* default */ 1,
],
},
} as const;
const featureCollection: GeoJSON.FeatureCollection = {
features: [
{
id: '9d10456e-bdda-4aa9-9269-04c1667d4552',
properties: {
icon: 'popup', …
```

feat(iOS, images): support strechable images in images component

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.kt
docs/Camera.md
docs/MapView.md
docs/docs.json
example/src/examples/Map/LocalizeLabels.tsx
example/src/scenes/GroupAndItem.tsx
ios/RCTMGL-v10/RCTMGLMapView.swift
ios/RCTMGL-v10/RCTMGLMapViewManager.m
src/components/Camera.tsx
src/components/MapView.tsx

Closes: #2633 
```jsx
<MapView style={{ flex: 1 }} localizeLabels={{ locale: 'es' }}>
<Camera centerCoordinate={CENTER_COORD} zoomLevel={14} />
</MapView>
```

feat: add localizeLabels

---

ios/RCTMGL-v10/RCTMGLInteractiveElement.swift
ios/RCTMGL-v10/RCTMGLPointAnnotation.swift
src/components/PointAnnotation.tsx
src/utils/checkRequiredProps.ts

chore: check that required props id is present in PointAnnotation

---

ios/RCTMGL-v10/RCTMGLCamera.swift
ios/RCTMGL-v10/RCTMGLInteractiveElement.swift
ios/RCTMGL-v10/RCTMGLLocationModule.swift
ios/RCTMGL-v10/RCTMGLOfflineModule.m
ios/RCTMGL-v10/RCTMGLOfflineModule.swift
ios/RCTMGL-v10/RCTMGLPointAnnotation.swift

feat(iOS,v10): implement offlineManger.resetDatabase on ios
See: #2706
Fixes: #2703

fix(iOS, v10): don't stop location updates, if locationManager still subscribes

---

ios/RCTMGL-v10/RCTMGLNativeUserLocation.swift
src/components/MapView.tsx

fix(ios): MapIdle, MapChanged events fixed, user location heading fixed

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/modules/RCTMGLOfflineModule.kt
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/utils/GeoJSONUtils.kt
docs/SymbolLayer.md
docs/docs.json
example/src/examples/Camera/TakeSnapshotWithMap.js
src/components/MapView.tsx
src/components/SymbolLayer.tsx

Fixes: #2706 
Also deprecate children in SymbolLayer - see https://github.com/rnmapbox/maps/wiki/Deprecated-SymbolLayerChildren

fix(android): implement offlineManger.resetDatbase

---

ios/RCTMGL-v10/RCTMGLImages.swift
ios/RCTMGL-v10/RCTMGLMapView.swift

fix: avoid adding multiple onEvery listener

---

ios/RCTMGL-v10/RCTMGLCamera.swift
src/components/MapView.tsx
src/components/NativeUserLocation.tsx
src/components/Terrain.tsx

fix: changing tracking mode should not affect pluck heading indicator

---

src/components/Terrain.tsx

Fixes some grammar issues found in warning message about Terrain depreciation.

chore: fix warning

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/modules/RCTMGLOfflineModule.kt
ios/RCTMGL-v10/RCTMGLEvent.swift
ios/RCTMGL-v10/RCTMGLOfflineModule.swift

android offline percentage typo

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/modules/RCTMGLModule.kt

Implement setTelemetryEnabled on android
Fixes: https://github.com/rnmapbox/maps/issues/2010#issuecomment-1505836776

fix(android,v10): implement setTelemetryEnabled

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/modules/RCTMGLOfflineModule.kt

fix(android,offline): fix getPacks/writableMapOf crash

---

ios/RCTMGL-v10/RCTMGLShapeSource.swift

Fix a small typo on the "featureCollection" name

fix: small typo in featureCollection name

---

README.md

v10 has been released, and the discussion matters in the "future of the repo" thread have been resolved.

docs: remove no longer used lines from README

---

example/src/examples/Map/DynamicUrl.tsx
example/src/scenes/GroupAndItem.tsx

Follow up on this https://github.com/rnmapbox/maps/pull/2796 to add an example
https://user-images.githubusercontent.com/937328/232437009-10b88b3c-f6ff-44c2-8017-892b4874f620.mov

docs: add example for dynamic url

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/modules/RCTMGLOfflineModule.kt
ios/RCTMGL-v10/RCTMGLOfflineModule.swift

fix(offline,android): fix getPackState on android

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/images/RCTMGLImages.kt
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/styles/sources/RCTSource.kt

Fixes: #2824 
Also fixes extra android warning about existing introduced in https://github.com/rnmapbox/maps/pull/2815/files#diff-3f74b276287f0afd56e79228ce50a3a570c7c58e2925c23143d62a36fe5fe66eR120

fix(android,v10): fix existing warning, fix images on stylereload

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt

fix(android,v10): implement isGestureActive on MapChange, MapIdle events

---

.github/check-code-example-in-issue.yml
scripts/actions/lint-code-example-in-issues/.eslintrc.js
scripts/actions/lint-code-example-in-issues/lint-code-example-in-issues.js
scripts/actions/lint-code-example-in-issues/package-lock.json
scripts/actions/lint-code-example-in-issues/package.json

Add action lint-code-example-in-issues to run lint on code examples posted in issues.

chore: add github actions to run eslint on code example in issues

---

ios/RCTMGL-v10/RCMTGLImage.swift
ios/RCTMGL-v10/RCTMGLImages.swift
ios/RCTMGL-v10/RCTMGLUtils.swift

fix(ios,v10): scale strechX with image's scale factor

---

docs/PointAnnotation.md
docs/docs.json
example/src/examples/Annotations/ShowPointAnnotation.tsx
src/components/PointAnnotation.tsx

docs: add PointAnnotation animation remarks

---

scripts/actions/lint-code-example-in-issues/lint-code-example-in-issues.js

attempt to fix label not found issue

lint code example in issues

---

android/rctmgl/build.gradle
example/ios/Podfile.lock
rnmapbox-maps.podspec

feat: update versions to 10.14.0

---

ios/RCTMGL-v10/RCTMGLMapView.swift

fix: implement coalescingKey for RCTMGLCameraChange

---

ios/RCTMGL-v10/RCTMGLAtmosphere.swift
ios/RCTMGL-v10/RCTMGLCamera.swift
ios/RCTMGL-v10/RCTMGLImages.swift
ios/RCTMGL-v10/RCTMGLInteractiveElement.swift
ios/RCTMGL-v10/RCTMGLLayer.swift
ios/RCTMGL-v10/RCTMGLLight.swift
ios/RCTMGL-v10/RCTMGLMapView.swift
ios/RCTMGL-v10/RCTMGLMarkerView.swift
ios/RCTMGL-v10/RCTMGLNativeUserLocation.swift
ios/RCTMGL-v10/RCTMGLPointAnnotation.swift
ios/RCTMGL-v10/RCTMGLSource.swift
ios/RCTMGL-v10/RCTMGLTerrain.swift

fix(v10,ios): duplicate warn on style reload

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/images/RCTMGLImages.kt
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/images/RCTMGLImagesManager.kt
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/styles/RCTMGLStyleValue.kt
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/utils/DownloadMapImageTask.kt
android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/utils/ImageEntry.kt

fix(android,v10): use 1.0 as fallback scale

---

ios/RCTMGL-v10/RCTMGLStyleValue.swift

fix(v10,ios): allow expression for enum style values

---

ios/RCTMGL-v10/RCTMGLImages.swift
ios/RCTMGL-v10/RCTMGLUtils.swift

On iOS changing images property of the `Images` component won't update the images.
I've used the following component to reproduce:
```jsx
import {
Images,
MapView,
ShapeSource,
SymbolLayer,
CircleLayer,
Camera,
circleLayer: {
circleRadiusTransition: { duration: 5000, delay: 0 },
circleColor: '#ff0000',
},
};
const features = {
features: [
{
id: 'a-feature',
properties: {
icon: 'example',
text: 'example-icon-and-label',
},
geometry: {
type: 'Point',
coordinates: [-74.00597, 40.71427],
},
},
{
id: 'b-feature',
properties: {
text: 'just-label',
},
geometry: {
type: 'Point',
coordinates: [-74.001097, …
```

fix(ios,v10): update to Images/images should cause refresh

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt

fix(v10, android): add onStyleReload callback

---

android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt

Component to reproduce the issue:
```jsx
import {
Images,
MapView,
ShapeSource,
SymbolLayer,
CircleLayer,
Camera,
circleLayer: {
circleRadiusTransition: { duration: 5000, delay: 0 },
circleColor: '#ff0000',
},
};
const features = {
features: [
{
id: 'a-feature',
properties: {
icon: 'example',
text: 'example-icon-and-label',
},
geometry: {
type: 'Point',
coordinates: [-74.00597, 40.71427],
},
},
{
id: 'b-feature',
properties: {
text: 'just-label',
},
geometry: {
type: 'Point',
coordinates: [-74.001097, 40.71527],
},
},
{
id: 'c-feature',
properties: {
icon: 'example',
},
geometry: { …
```

fix(v10, android): implement on did finish rendering fully on android

---

plugin/build/withMapbox.d.ts
plugin/build/withMapbox.js
plugin/src/withMapbox.ts

fix(expo): revert exclude arm64 for simulator builds

---

ios/RCTMGL-v10/RCTMGLLayer.swift

feat(ios,v10): warn if both above and below layer id is specified

---

android/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt
android/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.kt

refactor(android): refactor MapView commands

---

android/src/main/java-v10/com/mapbox/rctmgl/components/styles/layers/RCTLayer.kt
example/src/examples/Annotations/MarkerView.js

Fixes Show Point Annotation set above/bellow fill layer example on android

fix(android): fix showPointAnnotation above/below issue

---

android/build.gradle
example/ios/Podfile.lock
rnmapbox-maps.podspec

Upgrade iOS and android to 10.16.
Changelogs:
- https://github.com/mapbox/mapbox-maps-android/blob/v10.16/CHANGELOG.md
- https://github.com/mapbox/mapbox-maps-ios/blob/release/v10.16/CHANGELOG.md

feat: upgrade to mapbox 10.16

---

.eslintrc.js
.github/workflows/android-actions.yml
.github/workflows/ios-actions.yml
.github/workflows/on-push.yml
.gitignore
example/android/app/src/main/java/com/rnmapboxglexample/MainActivity.java
example/android/build.gradle
example/android/gradle.properties
example/android/gradle/wrapper/gradle-wrapper.properties
example/android/gradlew
example/android/gradlew.bat
example/android/settings.gradle
example/ios/.byebug_history
example/ios/Podfile
example/ios/Podfile.lock
example/ios/RNMapboxGLExample.xcodeproj/project.pbxproj
example/ios/RNMapboxGLExample/AppDelegate.mm
example/metro.config.js
example/package.json
example/react-native.config.js
package.json

Upgrade example to RN 0.72.4 and Fabric build variation to CI

chore: upgrade example to  0.72.4

---

example/src/examples/UserLocation/UserLocationUpdates.tsx
example/src/examples/V11/StyleImportConfig.tsx
example/src/scenes/GroupAndItem.tsx
ios/RNMBX/RNMBXCamera.swift
ios/RNMBX/RNMBXLocationModule.swift
ios/RNMBX/RNMBXLocationModuleV11.swift

Implemented locationManager on v11

fix(ios, v11): v11 location manager

---

android/build.gradle
android/src/main/AndroidManifest.xml

See: https://github.com/react-native-community/discussions-and-proposals/issues/671

fix: rn 0.73 compat - specify namespace in build.gradle

---

android/src/main/java/com/rnmapbox/rnmbx/utils/PropertyChanges.kt

Fixes: #3144 
Issue was caused by: #3138

fix: clear changes when applying it

---

android/src/main/java/com/rnmapbox/rnmbx/utils/PropertyChanges.kt
ios/RNMBX/RNMBXCamera.swift
ios/RNMBX/RNMBXMapView.swift
ios/RNMBX/RNMBXMarkerView.swift
ios/RNMBX/RNMBXNativeUserLocation.swift
ios/RNMBX/Uitls/PropertyChanges.swift

Implement latent on iOS so that:
- created MapView instance can be based on properties ([NavigationMapView](https://docs.mapbox.com/ios/navigation/api/2.17.0/Classes/NavigationMapView.html) for example)
- related properties can be applied together

refactor(iOS): ios lateinit

---

ios/RNMBX/RNMBXMapView.swift

fix: iOS gesture settings is only applied when mapView is already there

---

android/src/main/java/com/rnmapbox/rnmbx/components/images/RNMBXImagesManager.kt

Fixes an issue, where vector drawables are not displayed on Android. When adding vector drawables to iOS it immediately works, on Android unfortunetaly not. So i added some logic, to convert vector drawables into bitmap drawables. This is inspired by this mapbox util function:
https://github.com/mapbox/mapbox-maps-android/blob/7a701e241ca03b7178152ceb9c160d1fa67d712b/plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/utils/BitmapUtils.kt#L24-L41

Fix: Allow vector drawables as native images on Android

---

.github/workflows/ci-for-forked-repos.yml

fix typo in ci for forked repos

---

__tests__/interface.test.js
docs/docs.json
docs/examples.json
example/src/examples/UserLocation/CustomNativeUserLocation.tsx
src/Mapbox.ts
src/components/LocationPuck.tsx
src/components/UserLocation.tsx

Use `LocationPuck` instead of `NativeUserLocation`.
Going forward we'll recommend `LocationPuck` instead of `UserLocation`

refactor!:NativeUserLocation is deprecated use LocationPuck

---

docs/VectorSource.md
docs/examples.json
example/src/examples/BugReportExample.js
example/src/examples/LineLayer/DrawPolyline.tsx
example/src/examples/LineLayer/GradientLine.js
example/src/examples/LineLayer/ThirdPartyVectorSource.js
example/src/examples/LineLayer/index.js

doc: 3rd party vector source example

---

README.md
__tests__/interface.test.js
android/src/main/java/com/rnmapbox/rnmbx/modules/RNMBXModule.kt
android/src/main/mapbox-v11-compat/v10/com/rnmapbox/rnmbx/v11compat/MapboxMap.kt
android/src/main/mapbox-v11-compat/v11/com/rnmapbox/rnmbx/v11compat/MapboxMap.kt
docs/Mapbox.md
ios/RNMBX/RNMBXModule.m
ios/RNMBX/RNMBXModule.swift
setup-jest.js
src/RNMBXModule.ts

feat: clearData on Mapbox module

---

android/src/main/java/com/rnmapbox/rnmbx/components/annotation/RNMBXPointAnnotation.kt
android/src/main/java/com/rnmapbox/rnmbx/components/mapview/RNMBXMapView.kt
android/src/main/java/com/rnmapbox/rnmbx/utils/GeoJSONUtils.kt
ios/RNMBX/RNMBXEvent.swift
ios/RNMBX/RNMBXMapView.swift
ios/RNMBX/RNMBXPointAnnotation.swift

fix: send correct point anntoation events on iOS

---

ios/RNMBX/RNMBXMapView.swift
ios/RNMBX/RNMBXPointAnnotation.swift

fix(v11,ios): work around the userInfo issue in point annotation in v11

---

src/modules/offline/offlineManager.ts

Fix bug can not get full information offline pack

---

README.md

Fix typo in README. Change `insructions` to `instructions`

doc: Fix README typo

---

ios/RNMBX/RNMBXMapView.swift

fix(ios): localizeLabels when changing styleURL

---

README.md
android/build.gradle

fix(android): fix namespace build error on rn 0.66

---

example/ios/RNMapboxGLExample.xcodeproj/project.pbxproj
example/ios/RNMapboxGLExample/DebugWorkaround.swift

Implement main in swift, to fix swift debugging:
Before:
After:

chore(ios): fix swift debugging in example by implementing main in swift

---

setup-jest.js

Add missing MapIdle event in setup-jest.js

---

README.md

Update README.md LocationPuck typo

---

android/src/main/java/com/rnmapbox/rnmbx/components/annotation/RNMBXPointAnnotationCoordinator.kt

fix(android):drag callbacks for PointAnnotation

---

ios/RNMBX/RNMBXCircleLayer.swift
ios/RNMBX/RNMBXFillExtrusionLayer.swift
ios/RNMBX/RNMBXFillLayer.swift
ios/RNMBX/RNMBXLineLayer.swift
ios/RNMBX/RNMBXModelLayer.swift
ios/RNMBX/RNMBXRasterLayer.swift
ios/RNMBX/RNMBXSkyLayer.swift
ios/RNMBX/RNMBXSymbolLayer.swift
ios/RNMBX/codeparts/LayerPropsCommon.codepart-swift.ejs

Regression was introduced in #3390
Fixes: #3400

fix(ios,v10): call super.setOptions, to set common layer options on v10

---

android/src/main/java/com/rnmapbox/rnmbx/components/annotation/RNMBXPointAnnotation.kt
android/src/main/java/com/rnmapbox/rnmbx/components/annotation/RNMBXPointAnnotationManager.kt

fix(android): fix point annotation child view management

---

.github/workflows/ios-actions.yml
android/build.gradle
android/install.md
docs/GettingStarted.md
example/android/build.gradle
example/ios/Podfile
example/ios/Podfile.lock
ios/install.md
plugin/install.md
rnmapbox-maps.podspec

Update default mapbox version to 10.17.0

feat: upgrade default mapbox version to 10.17.0

---

android/build.gradle

Fixes: #3480
See https://github.com/rnmapbox/maps/issues/3267#issuecomment-2099945549

fix(android): use kotlinVersion to determine default corutines version

---

example/src/examples/Animations/AnimatedLine.js
example/src/examples/Animations/AnimatedLineOffsets.tsx
example/src/examples/Animations/AnimatedPoint.tsx
example/src/examples/Animations/DriveTheLine.js
example/src/examples/Animations/index.js
example/src/examples/Web/MarkerView.js
example/src/examples/Web/index.js
example/src/scenes/GroupAndItem.tsx
package.json
src/web/components/MarkerView.tsx
src/web/index.js

feat(web): MarkerView POC

---

.github/pull_request_template.md

Fil typo in PR description template.

docs: fix typo in PR template

---

CONTRIBUTING.md

Fix spelling of `PRs` in CONTRIBUTING.md.

docs: fix typo in CONTRIBUTING document

---

ios/RNMBX/RNMBXMapView.swift

refactor(ios): init waiter

---

example/android/app/src/main/java/com/rnmapboxglexample/MainApplication.kt
example/ios/Podfile
example/package.json

chore: disable brideless on android

---

ios/RNMBX/RNMBXMapView.swift

fix(ios): fix callOrWait callback can be reentrant

---

src/web/components/Camera.tsx

Right now when calling:
```ts
const cameraRef = useRef<Camera>(null);
...
cameraRef.current?.setCamera(config);
```
The mobile version works just fine but web version will crash with:
```
Uncaught Error
cameraRef.current.setCamera is not a function
```
As I had need for it, I added the missing `setCamera` method that should mimic the mobile version fairly closely.
[Screencast from 2024-08-05 19-19-43.webm](https://github.com/user-attachments/assets/68432da5-96c6-41ff-959c-2a3e83e7260a)
```jsx
import React, { useEffect, useRef } from 'react';
import { View, Text } from 'react-native';
import { MapView, Camera, MarkerView } from '@rnmapbox/maps';
function MarkerViewExample() {
const cameraRef = useRef(null);
setTimeout(() => {
console.log('Setting camera'); …
```

feat(web): add missing setCamera method to Camera component

---

android/build.gradle
android/src/main/java/com/rnmapbox/rnmbx/components/AbstractEventEmitter.kt
android/src/main/java/com/rnmapbox/rnmbx/components/annotation/RNMBXPointAnnotationManager.kt
android/src/main/java/com/rnmapbox/rnmbx/components/camera/RNMBXCameraManager.kt
android/src/main/java/com/rnmapbox/rnmbx/components/camera/RNMBXVIewportManager.kt
android/src/main/java/com/rnmapbox/rnmbx/components/images/RNMBXImagesManager.kt
android/src/main/java/com/rnmapbox/rnmbx/components/mapview/RNMBXMapViewManager.kt
android/src/main/java/com/rnmapbox/rnmbx/components/styles/sources/RNMBXRasterDemSourceManager.kt
android/src/main/java/com/rnmapbox/rnmbx/components/styles/sources/RNMBXRasterSourceManager.kt
android/src/main/java/com/rnmapbox/rnmbx/components/styles/sources/RNMBXTileSourceManager.kt
android/src/main/java/com/rnmapbox/rnmbx/components/styles/sources/RNMBXVectorSourceManager.kt

fix(android): android build on pre 0.75

---

android/src/main/java/com/rnmapbox/rnmbx/utils/ViewTagResolver.kt
example/android/app/src/main/java/com/rnmapboxglexample/MainApplication.kt
example/android/build.gradle
example/android/gradle/wrapper/gradle-wrapper.properties
example/android/gradlew
example/android/gradlew.bat
example/ios/Podfile
example/ios/Podfile.lock
example/ios/RNMapboxGLExample.xcodeproj/project.pbxproj
example/package.json

chore(example): update example to rn 0.76

---

ios/RNMBX/RNMBXStyleImport.swift
ios/RNMBX/RNMBXStyleImportComponentView.mm

Fix StyleImport for New Architecture on iOS

---

.gitignore
package.json
scripts/autogenHelpers/DocJSONBuilder.mjs
yarn.lock

chore: use documentation node api, gitignore tsconfig.tsbuildinfo

---

android/src/main/java/com/rnmapbox/rnmbx/components/mapview/NativeMapViewModule.kt
android/src/main/java/com/rnmapbox/rnmbx/components/mapview/RNMBXMapView.kt
android/src/main/java/com/rnmapbox/rnmbx/utils/extensions/Map.kt
android/src/main/java/com/rnmapbox/rnmbx/utils/writeableMapArrayOf.kt
android/src/main/mapbox-v11-compat/v10/com/rnmapbox/rnmbx/v11compat/MapboxMap.kt
android/src/main/mapbox-v11-compat/v11/com/rnmapbox/rnmbx/v11compat/MapboxMap.kt
android/src/main/old-arch/com/rnmapbox/rnmbx/NativeMapViewModuleSpec.java
docs/MapView.md
docs/docs.json
docs/examples.json
example/src/examples/V10/FeatureState.tsx
example/src/examples/V10/index.js
ios/RNMBX/RNMBXMapViewManager.swift
ios/RNMBX/RNMBXMapViewModule.mm
setup-jest.js
src/components/MapView.tsx
src/specs/NativeMapViewModule.ts

This branch is just running ci for #3741
Fixes #3741
```jsx
```

feat: feature state

---

android/src/main/java/com/rnmapbox/rnmbx/utils/ViewTagResolver.kt

Fixes #3756
On android when trying to resolve a view that's not there yet, in recent rn versions it returns null instead of IllegalViewOperationException, we now do the same wait for tag to appear on IllegalViewOperationException and with null check. We also add a timeout so we warn the user if the waiter timeoutedd
```jsx
```

fix(android): Fix null ViewTagResolver issue, wait until there is a view

---

docs/GettingStarted.md

Update GettingStarted.md:
- Update Mapbox account links. The old links still work, but are not according to the new url schema.
- Remove legacy componentDidMount reference.
- Typo fixes and some text formatting.

Docs: Update GettingStarted.md

---

docs/LocationPuck.md
docs/NativeUserLocation.md
docs/docs.json
src/components/LocationPuck.tsx

chore: puckBearing typo

---

example/README.md
example/android/gradle.properties
example/e2e/docScreenshots.e2e.js
example/src/examples/Annotations/MarkerView.tsx
example/src/examples/Annotations/PointAnnotationAnchors.js
example/src/examples/Camera/GetCenter.js
example/src/examples/FillRasterLayer/IndoorBuilding.js
example/src/examples/FillRasterLayer/WatercolorRasterTiles.js
src/components/MarkerView.tsx

PointAnnotation examples uses `collapsable={false}` so the work on react 19.0 with new arch view folding.
```jsx
```

chore: example fixes

---

.github/workflows/publish.yml
.github/workflows/update-docs.yml

Fix doc puslbish and nom publish commands
```jsx
```

fix: fixed dummytoken/accestoken dir
